### ISSUE TITLE
Nova launcher

### ISSUE THREAD

**Issue by ippocratis** [ImranR98/Obtainium#1048]
Nova releases are in the https://teslacoilapps.com/apk/NovaLauncher_x.y.z.apk endpoint

No api

https://teslacoilapps.com/apk  endpoint is not accessible

Obtainium cant grab apk in the https://teslacoilapps.com and the  above url's

**Comment by ImranR98** [comment]
You could use `https://novalauncher.com/beta` as the source, with `packageName=com.teslacoilsw.launcher$` as the custom apk link filter. But you won't be notified of updates because the 'latest stable' link doesn't change. If you don't mind using betas, you could use the filter `packageName=com.teslacoilsw.launcher&betaType=public&versionCode=` and that should get you update notifications.

**Comment by ImranR98** [comment]
For more details on the HTML source, see https://github.com/ImranR98/Obtainium/issues/954#issuecomment-1745970526

**Comment by ippocratis** [comment]
> You could use `https://novalauncher.com/beta` as the source, with `packageName=com.teslacoilsw.launcher$`

This worked but https://teslacoilapps.com/beta as source

 > `packageName=com.teslacoilsw.launcher&betaType=public&versionCode=` 

Cant get a valid release using versionCode
`packageName=com.teslacoilsw.launcher&betaType=public$` works thoug


Thanks

**Comment by ImranR98** [comment]
The teslacoil url just redirects to the nova one. Also, using your link filter (without versioncode) will result in no update notifications because the link will never change. I just tried the settings from my previous comment and it does work. Are you entering the regex in the right input field?

**Comment by ippocratis** [comment]
>  Are you entering the regex in the right input field?

Was using the wrong field. 

Thanks again for clarification and your awesome app.

Cheers
