### ISSUE TITLE
App already installed but showing as not installed 

### ISSUE THREAD

**Issue by mjain234** [ImranR98/Obtainium#105]
Before the recent update, i just added the app GitHub url in "add url section" and when that app imported, it is showing me as "App not installed" but as you can see [here](https://user-images.githubusercontent.com/70900505/201145868-a2c5128d-33f1-4cb0-a793-e6fd03f7d234.mp4), the app is already installed. And also after updating, the issue still persists.

Device - Realme 2 Pro

Android - v13

ROM - Arrow OS

Obtainium version - v0.6.10

**Comment by ImranR98** [comment]
Was the App added through the 'Add App' page? Or the Import/Export page (URL or GitHub Stars import)?

**Comment by ImranR98** [comment]
If you used URL or GitHub star imports, then this is expected behaviour (Obtainium can't detect whether Apps imported with those methods are already installed). To fix this, you'd need to select all those Apps and "re-install" them through Obtainium (this doesn't actually re-install the Apps, but it will fix the "not installed" status). BUT make sure you are on the latest version [v0.6.11](https://github.com/ImranR98/Obtainium/releases/tag/v0.6.11-beta) as the previous versions have a bug that would cause this re-install process to fail.

**Comment by mjain234** [comment]
I was getting this ![error](https://user-images.githubusercontent.com/70900505/201232464-ad901c3a-de82-4ad0-83ec-e25e58a63f3e.png) before but after uninstalling the mentioned app, and then installing the same from GitHub fixed the issue.
Now the app is showing perfectly :-⁠)
