### ISSUE TITLE
Prefer Author name instead of "F-Droid Official"

### ISSUE THREAD

**Issue by foxjaw** [ImranR98/Obtainium#1076]
Each & every F-Droid application entried says **"by F-Droid Official"**. I know it's by F-Droid, but can you please use the Author Name of the app ? Just like how GitHub/Lab & other sources have their repo owners ?

I think the same goes with other F-Droid repos like IzzyOnDroid, etc. If it's an f-droid repo, please use the Author's name instead of the F-Droid Repo.

**Comment by foxjaw** [comment]
I would not think web scraping would be error prone. But it's upto you to implement it or not.  
For ex, take droidify  
view-source:https://f-droid.org/en/packages/com.looker.droidify/  
Line 178 is just a plane one liner, which would be easy to scrape to.

**Comment by ImranR98** [comment]
Web scraping in general is unreliable because you will not be notified or warned of website changes. APIs are meant to be used programmatically so they are always going to be the same - whenever changes do need to be made, those changes will be made in a new version of the API, while the old version will continue to work  or you will be given a warning in advance before it stops working.

**Comment by foxjaw** [comment]
Oh. I'm not a dev but, [is this the documentation](https://f-droid.org/en/docs/Build_Metadata_Reference/#AuthorName) for it ?

**Comment by ImranR98** [comment]
No that's not the API documentation. That is the documentation for the file that developers are supposed to provide to F-droid when they submit their apps.

**Comment by cvoges12** [comment]
@ImranR98 How do other F-Droid apps get the Author name and other metadata then?

**Comment by ImranR98** [comment]
@cvoges12 no idea

**Comment by cvoges12** [comment]
Yeah, it isn't impossible. I see AuroraDroid and such doing this too. I guess the answer to how to do this is just less obvious. But I don't think that's a good reason to close the issue since that doesn't necessarily make the issue impossible. I could go ask the AuroraDroid devs or whatever if need be.

**Comment by cvoges12** [comment]
@ImranR98 What do you think?

**Comment by ImranR98** [comment]
Sure, hopefully there's some other API w more info

**Comment by jollySleeper** [comment]
@foxjaw I just created a Issue somewhat Related to this #

This discovery of yours could be great for automating tracking packages from source repos

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.38-beta

**Comment by jollySleeper** [comment]
Thanks @ImranR98 for this feature. 
 
As far as I know this API will help in fetching the source repo too. So, can you add the source repo link for the particular app in App Detail Section of Obtanium
