### ISSUE TITLE
HTML app source problem: Could not get ID from APK

### ISSUE THREAD

**Issue by custompyramidfellow** [ImranR98/Obtainium#1077]
**Describe the bug**
I want to use Obtanium to download latest TOR browser apk aarch64 for Android from
https://torproject.org/download/
But I can't get it to work. 

Thanks for your help.

**To Reproduce**
1. If I just add the URL via Add App it takes a while to scrape and gets added to Obtanium but if I hit Install it just gives error "Incompatible App"

2. If I add the URL and Custom APK link filter "tor-browser-android-aarch64" it gives me immediately error: "Could not get ID from APK" and doesnt even get added to Obtanium

3. If I add the URL, and Custom APK link filter "tor-browser-android-aarch64", and version extraction "aarch64-([0-9]+\.)*[0-9]+" same error: "Could not get ID from APK"

**Please complete the following information:**
 - Device: Pixel 7
 - OS: GrapheneOS
 - Obtainium Version: 0.14.32

**Comment by ImranR98** [comment]
Observations explained:
1. The default APK being picked is the last one after sorting alphabetically which is x86_64 which isn't compatible with your phone.
2. Since you've used your own link filter, the default filter (which filters out all links not ending in `.apk`) is no longer used. So the filter matches two links on the page - the `.apk` link you need, but also the `.apk.asc` link ("Sig" button on the page). The latter is picked since it is the last one after sorting.
3. Same as 2.

So the solution is to use a regex like `aarch64.*apk$` which will filter out the `.asc` link. For version extraction, `([0-9]+\.)*[0-9]+` will work.
