### ISSUE TITLE
At add app. Expected: 1st add repo.  Then start downloading 

### ISSUE THREAD

**Issue by blackholeearth** [ImranR98/Obtainium#1080]
**Prerequisites**

**Current behavior:**
At add app page . 
When i press add.
1)it stays on same page.
2)İt starts download,
3)Then it checks version.

Order is  out of whack.

**Expected:**
At add app page . 
When i press add.
1) İt should  navigate apps list page.
2) version check happens (installed vs latest)
3) it should not download without asking me.
4) in app list page  if i press download, then it should download 

-------
**Note: error**
İ can trigger  error "download not found".

**error  scenario:**
1)Go to add app page . 
2) search seal   author: junkfood 
2a) enable prerelease 
3)  press add.
4)it stays on same page.
5)İt starts downloading 30mb
6) while it's still downloading.
7)  Goto1 , add the same app seal
8) downloader progress will jump between 1st n 2nd progress . After download complieted it will give error.  File not found.
.

--------
You can  avoid this by . Adding repo  instantly to applist . 
İf i do it again you can say already in the applist.

The expected behavior.

**Comment by ImranR98** [comment]
For apps to be added, we must know their package ID (this enables version detection, icon extraction, etc). For some sources (like specific github repos, f-droid repos, etc.) this can be done easily. But for others, the only way to get the package ID is to extract it from the APK. That's why APKs sometimes must be downloaded before an app can be added. This has been covered in an earlier issue too.
