### ISSUE TITLE
moving repo data to internal data from android/data folder for easier backup

### ISSUE THREAD

**Issue by rezad1393** [ImranR98/Obtainium#1100]
**Describe the feature**
I use neo backup to backup apps and move them between ROMS. I have set it to backup "app" (which is apk) and "data".
most apps work correctly with this. and they don't need "device protected data" or external data or obb or media folder.

but I noticed that this app uses android/data/appid folder for repo json storage and this cause the backup of obtanuim to be restored with no repo.

can you move the repo part (which is the only part saved there)  to internal data folder from there? so that it can be back upped just like other apps?

I lost all my repos saved there after backup and remembering to treat this app differently from other apps is a bit of burden.

**Comment by ImranR98** [comment]
I don't think this is worth the tradeoff. Having the data be accessible via a file manager has been very useful for debugging/troubleshooting issues and for testing, since it's possible to manually edit the files. If Neo-backup supports backing up files (or you have another solution for that), you can enable auto-export in Obtainium and point it to any custom directory - then back that up.

**Comment by rezad1393** [comment]
where is the auto export?

**Comment by ImranR98** [comment]
Import/export page. Pick a directory and enable the toggle.
