### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by popogomo** [ImranR98/Obtainium#1134]
Thanks for maintaining this great app!

Not a big issue, but can you please make scrolling more smooth? When I scroll through apps in the main screen, the scrolling is a little chobby (120hz screen), not as smooth as scrolling in other apps / settings. Can you please fix it? Thanks.

**Comment by ThreeDeeJay** [comment]
Wasn't this already fixed a while ago?
120hz does make it scroll smoother on my end which wasn't the case a long time ago, though it can still be a bit choppy, especially when updating.

**Comment by ImranR98** [comment]
Yeah, smoothness has been an issue for a while, but I don't think there's anything I can do on my end. Certain actions like updating and loading icons initially seem to slow things down and I haven't been able to make any improvements. I think it makes sense to close this issue since it's unlikely to be resolved.
