### ISSUE TITLE
Ability to Track Source Code Repos For F-Droid Packages

### ISSUE THREAD

**Issue by jollySleeper** [ImranR98/Obtainium#1138]
**Prequisites**
Can't add two different repos(fdroid & github) with same package signature. Obtanium says that the current app has been already.
For Example: If I'm tracking Aurora Store from F-Droid. Obtanium won't allow me add Aurora Store Gitlab Repo which would be Track Only Repo for seeing if F-Droid builds are lagging behind.

**Describe the feature**
Can We Get an option to add the Source Repos(Github/Gilab) for F-Droid Packages so that we don't have to add Two repos for the same Package. Like in detail page can we get the info and changelog of latest Github/Gitlab/Codeberg release of the same package.

That would be great. Also, thanks for this app. Much appreciated <3

**Comment by jollySleeper** [comment]
Fair Enough, got your point.

If Obtanium can figure out source code repos of Fdroid Apps at least a link to it Might Help

**Comment by jollySleeper** [comment]
> You can manually go check the source repos on your browser btw. This is not much of a concern & need not to code anything.

This is the exact thing that would be automated. The same way we can go to the Repo and check for releases and download the latest release for each app.
A little bit of Automation makes our life easy.

**Comment by ImranR98** [comment]
Yes, App IDs must be unique in Obtainium.

> For Example: If I'm tracking Aurora Store from F-Droid. Obtanium won't allow me add Aurora Store Gitlab Repo which would be Track Only Repo for seeing if F-Droid builds are lagging behind.

You can still do this, just make sure the track-only app was set to track-only from the beginning instead of adding it normally and then switching on the track-only mode. This way, the app would be added with a randomly generated ID instead of the real package ID. Then you can add the F-Droid version which would use the real ID.

Note: The use of randomly-generated IDs when adding an app as track-only is not consistent for all sources. This will be fixed in the next release.

In general, I think it should be up to the user to add the F-Droid and original source repos separately - it would only need to be done once so I don't think the added complexity to automate it would make sense.

**Comment by jollySleeper** [comment]
Thank You Soo Much for This <3
