### ISSUE TITLE
Use F-Droid Data repo instead of scraping F-Droid website

### ISSUE THREAD

**Issue by faustaahmad** [ImranR98/Obtainium#114]
F-Droid URL (packages) contain `packageName` at the end of URL

- [Metadata](https://gitlab.com/fdroid/fdroiddata/-/tree/master/metadata/)
Application's `VersionCode` & `VersionName` (latest version at the very bottom) for comparing & getting direct download link
`https://gitlab.com/fdroid/fdroiddata/-/raw/master/metadata/<packageName>.yml`

- Direct download
`https://f-droid.org/repo/<packageName>_<versionCode>.apk`

**Comment by ImranR98** [comment]
Thanks! This will make fdroid more reliable once implimented.

**Comment by ImranR98** [comment]
Ugh, just wasted a bunch of time on this. Turns out F-Droid doesn't keep the APKs on their website in line with the YAML file. So for example, the latest version of [VLC declared in the YAML is 3.5.3](https://gitlab.com/fdroid/fdroiddata/-/raw/master/metadata/org.videolan.vlc.yml), but [the website only has 3.5.2](https://f-droid.org/packages/org.videolan.vlc/) (APKs for 3.5.3 don't exist).

There's doesn't seem to be any way to tell what the latest version actually is without scraping the website, which defeats the purpose of using the YAML first.

**Comment by faustaahmad** [comment]
@ImranR98 there's actually a way to query *active* package with [FDroid API](https://f-droid.org/docs/All_our_APIs/)
I'm blind because I didn't read it's documentation first

**Comment by ImranR98** [comment]
Ah, I didn't think to check their docs. Thanks for the research, will give it another try later this week.

**Comment by faustaahmad** [comment]
I realized that Izzysoft has almost the same [API](https://gitlab.com/IzzyOnDroid/repo/-/wikis/API) as FDroid after reading it's docs

**Comment by rancidfrog** [comment]
@ImranR98
For VLC releases directly from the devs are here:
Stable:
get.videolan.org/vlc-android/
Beta:
get.videolan.org/testing/android/

However, one of the devs need to unhide latest releases manually each time a new release.
Sometimes, either intentionally or not they forget, there is a delay for when it is available

**Comment by ImranR98** [comment]
> @ImranR98 For VLC releases directly from the devs are here: Stable: get.videolan.org/vlc-android/ Beta: get.videolan.org/testing/android/

That would mean adding the VLC website as an app source, a new issue entirely.

**Comment by ImranR98** [comment]
Done: https://github.com/ImranR98/Obtainium/releases/tag/v0.7.4-beta

Signal and Mullvad are now the only sources that rely on web scraping (might be an API or something for those too, haven't looked into it).

**Comment by S7venLights** [comment]
Nice work guys
