### ISSUE TITLE
Android update dialogues interfere with each other

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#118]
I just installed updates for two apps.
When they had finished downloading both update dialogues pop up, i clicked update on the first app,  then it was like it dropped into the background and  i could click update on the other app when in fact the first app was still busy installing.
I didn't start updating the 2nd app, because i knew the first was still busy, but it's an easy mistake to make. When the first app did finish installing, it popped up again saying done.

If there's a way to time update dialogues popping up that could help.
But not a big issue and i don't know what would have happened if i had clicked update on the 2nd app too soon.
Most people should catch this issue.

**Comment by ImranR98** [comment]
I haven't seen this. Could you see what happens next time and report here.

**Comment by S7venLights** [comment]
Different issue to the first, but I feel the two are related.

**Comment by ImranR98** [comment]
Haven't been able to replicate this, but I'm guessing it's another installer plugin related issue. The installer plugin is definitely this app's biggest weak point - like 4 or so issues caused by it.

Unfortunately we can't add a simple delay between installs because we don't know how long any given install may take or how long the user will wait before clicking install. Once the install command is sent out, Obtainium is blind - no way to know anything about the result. May not be fixable without a better plugin.

**Comment by ImranR98** [comment]
I think this should be tracked as part of #99 as they are similar, and the solution to that issue (an install plugin we can get results from) would fix this one too.

**Comment by S7venLights** [comment]
Okay well it's not a big issue for users who know what they're doing and the reset install status button helps when mistakes happen

**Comment by S7venLights** [comment]
I came across this today: https://github.com/jroddev/android-oss-release-tracker
Maybe you can combine forces to figure out or code a a solution to plugin issues?

**Comment by ImranR98** [comment]
Honestly I'm not sure I'd have much to contribute since making a new plugin would require someone who is familiar with both Android and Flutter plugin development.

**Comment by ImranR98** [comment]
I did look into it briefly, but it seems like something that would take focused effort to learn - not something I'm likely to do anytime soon. Especially since from what I found, it seems like the way Flutter makes native Android API calls is meant to be asychronous by design, so returning the results of an APK install via a Flutter plugin might be complicated.

**Comment by S7venLights** [comment]
Yeh but I was thinking, maybe he can help with that. Anyhow just thought I'd share. No stress
