### ISSUE TITLE
support GCAM link.

### ISSUE THREAD

**Issue by az-my** [ImranR98/Obtainium#1182]
https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/
is it possible to add this? and get latest version of apk

**Comment by ImranR98** [comment]
It should be possible to add it using some of the HTML source's filtering options (see https://github.com/ImranR98/Obtainium/wiki#html), but it seems like there's a bug in generating a version string for this. Will look into it.

**Comment by ImranR98** [comment]
Yeah for some reason this source provides APKs where the hash seems to change every time. So you need to turn off the "support fixed link" toggle. You can also use the version extraction option if you want (not required). The following settings should work (I made some assumptions about which variant you want, you can modify accordingly):

![Screenshot_1703471558](https://github.com/ImranR98/Obtainium/assets/30463115/0378cd04-a47a-451f-bc9c-545d1aacfe28)

However, one strange thing about this app is that the app ID seems to contain the version number. You cannot update an app with one ID using an APK that has another ID. So installing updates won't really work through Obtainium (you can still add the app as track-only). I see no reason for the developer to do it this way.

**Comment by ulil-azmy** [comment]
really appreciated it. thanks really fast responses. again, thanks so much

**Comment by ThatOneCalculator** [comment]
Awesome, thank you so much! I'd love if this was mentioned in documentation somewhere, as I've been searching for literal years for a good way to keep gcam ports updated.

**Comment by ThatOneCalculator** [comment]
Can I ask what URL you put for the App Source URL? @ImranR98

**Comment by ThatOneCalculator** [comment]
For SGCAM, they publish both 8.x and 9.x versions. Could you recommend a filter for only 9.x versions?

![Screenshot_20231226-172900.png](https://github.com/ImranR98/Obtainium/assets/44733677/e7d9a585-14b8-4106-b153-5fbcdbdfe73a)

![Screenshot_20231226-172903.png](https://github.com/ImranR98/Obtainium/assets/44733677/dbd3ac39-3481-4132-a2de-fce72ea0a7cf)

**Comment by ThatOneCalculator** [comment]
I'm having some trouble with the filters for Shamim's releases:

## `SGCAM_(.+)_S` 

Works, but matches 8.x and 9.x versions (both are published actively). In this case, 8.5 was published after 9.1

![image](https://github.com/ImranR98/Obtainium/assets/44733677/823c4bdb-f05f-460a-a54b-8a7d0357cfd1)

![image](https://github.com/ImranR98/Obtainium/assets/44733677/a2342272-770a-421f-ab7b-42b3463d3ebb)

## `SGCAM_(9.+)_S`

Shows an error in the app, but *should* be valid RegEx.

![image](https://github.com/ImranR98/Obtainium/assets/44733677/69d7bbaf-2555-4f8e-8586-0fa6bb8baafa)

![image](https://github.com/ImranR98/Obtainium/assets/44733677/f0ed4455-767f-4497-94a1-7d98998c0f2d)

**Comment by ImranR98** [comment]
@ThatOneCalculator there's no way to grab 9.X releases only. Here's some documentation on the HTML source: https://github.com/ImranR98/Obtainium/wiki#html

The problem is that the "intermediate links" on the main page (https://www.celsoazevedo.com/files/android/google-camera/dev-shamim/) contain version numbers only in the text, not the actual URL itself. For example:
```html
<a href="https://www.celsoazevedo.com/files/android/google-camera/dev-shamim/f/dl63/">SGCAM_9.1.098.24_STABLE_V10</a>
```
Right now Obtainium only has an option to filter by URL, not link text. But that can be added.

**Comment by ThatOneCalculator** [comment]
That'd be amazing :pray:

They also have an RSS feed, would this be useful? https://www.celsoazevedo.com/files/android/google-camera/dev-feed.xml

**Comment by ImranR98** [comment]
Doesn't seem to be valid XML. Besides it would have the same issue - no way to filter URLs by version since the URL itself doesn't contain the version (and there's no current filter by the version text associated with each URL).

**Comment by ThatOneCalculator** [comment]
> Doesn't seem to be valid XML

Weird, it shows up in my RSS reader fine

**Comment by ImranR98** [comment]
Hmm, yes it shows up fine in Chrome and Curl but not Firefox.

**Comment by ImranR98** [comment]
Done: https://github.com/ImranR98/Obtainium/releases/tag/v0.15.0-beta

This release also lets you now have any number of intermediate links.

**Comment by ThatOneCalculator** [comment]
Nice! What would the filter look like for SGCAM?

**Comment by az-my** [comment]
Below is what worked for me.

Base URL
https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/

intermediate Link
f/dl(\d+)

version extraction
(\d+\.\d+\.\d+)

Filtey by Link Text
MGC\.apk

As of this writing, this config will grab MGC_9.1.098_A11_V5_MGC.apk

**Comment by az-my** [comment]
https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/ 

Latest 9.1 version is https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/f/dl185/
Latest 8.9 version is https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/f/dl184/

in above link there is 2 version with same structure of intermediate link. 
how can we target to only specific version only? for example we only want to add 8.9 version only.

**Comment by ImranR98** [comment]
@az-my try clicking this link from your phone: <a href="obtainium://app/%7B%0A%20%20%20%20%22id%22%3A%20%22com.android.MGC_8_9_097%22%2C%0A%20%20%20%20%22url%22%3A%20%22https%3A%2F%2Fwww.celsoazevedo.com%2Ffiles%2Fandroid%2Fgoogle-camera%2Fdev-bsg%22%2C%0A%20%20%20%20%22author%22%3A%20%22www.celsoazevedo.com%22%2C%0A%20%20%20%20%22name%22%3A%20%22Camera%22%2C%0A%20%20%20%20%22latestVersion%22%3A%20%221034353095%22%2C%0A%20%20%20%20%22apkUrls%22%3A%20%22%5B%5B%5C%22https%3A%2F%2F1-dontsharethislink.celsoazevedo.com%2Ffile%2Ffilesc%2FMGC_8.9.097_A11_V21_MGC.apk%5C%22%2C%5C%22https%3A%2F%2F1-dontsharethislink.celsoazevedo.com%2Ffile%2Ffilesc%2FMGC_8.9.097_A11_V21_MGC.apk%5C%22%5D%5D%22%2C%0A%20%20%20%20%22preferredApkIndex%22%3A%200%2C%0A%20%20%20%20%22additionalSettings%22%3A%20%22%7B%5C%22intermediateLink%5C%22%3A%5B%7B%5C%22customLinkFilterRegex%5C%22%3A%5C%22_8.9%5C%22%2C%5C%22filterByLinkText%5C%22%3Atrue%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%7D%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22MGC.apk%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22supportFixedAPKURL%5C%22%3Atrue%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionDetection%5C%22%3A%5C%22noVersionDetection%5C%22%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22%5C%22%7D%22%2C%0A%20%20%20%20%22overrideSource%22%3A%20%22HTML%22%2C%0A%20%20%20%20%22allowIdChange%22%3A%20false%0A%7D">Add to Obtainium (com.android.MGC_8_9_097)</a>

Raw config:
```json
{
    "id": "com.android.MGC_8_9_097",
    "url": "https://www.celsoazevedo.com/files/android/google-camera/dev-bsg",
    "author": "www.celsoazevedo.com",
    "name": "Camera",
    "latestVersion": "1034353095",
    "apkUrls": "[[\"https://1-dontsharethislink.celsoazevedo.com/file/filesc/MGC_8.9.097_A11_V21_MGC.apk\",\"https://1-dontsharethislink.celsoazevedo.com/file/filesc/MGC_8.9.097_A11_V21_MGC.apk\"]]",
    "preferredApkIndex": 0,
    "additionalSettings": "{\"intermediateLink\":[{\"customLinkFilterRegex\":\"_8.9\",\"filterByLinkText\":true,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":false}],\"customLinkFilterRegex\":\"MGC.apk\",\"filterByLinkText\":false,\"skipSort\":false,\"reverseSort\":false,\"sortByLastLinkSegment\":false,\"versionExtractionRegEx\":\"\",\"matchGroupToUse\":\"\",\"versionExtractWholePage\":false,\"supportFixedAPKURL\":true,\"trackOnly\":false,\"versionDetection\":\"noVersionDetection\",\"apkFilterRegEx\":\"\",\"autoApkFilterByArch\":true,\"appName\":\"\",\"exemptFromBackgroundUpdates\":false,\"skipUpdateNotifications\":false,\"about\":\"\"}",
    "overrideSource": "HTML",
    "allowIdChange": false
}
```

Keep in mind you will not be able to update this app since the version is part of the App ID for some reason.

**Comment by ThatOneCalculator** [comment]
Interestingly, I was able to add MGC, but when I wanted to add AGC/BigKaka, it said that the app was already added

**Comment by Durstronaut** [comment]
> Below is what worked for me.
> 
> Base URL https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/
> 
> intermediate Link f/dl(\d+)
> 
> version extraction (\d+.\d+.\d+)
> 
> Filter by Link Text MGC.apk
> 
> As of this writing, this config will grab MGC_9.1.098_A11_V5_MGC.apk

Would you be able to assist me in setting this up for 

https://www.celsoazevedo.com/files/android/google-camera/dev-BigKaka/

I tried the same set up, but it would grab the 8.5 release and I am hoping for the 9.2

**Comment by fabian-st** [comment]
> > Below is what worked for me.
> > Base URL https://www.celsoazevedo.com/files/android/google-camera/dev-bsg/
> > intermediate Link f/dl(\d+)
> > version extraction (\d+.\d+.\d+)
> > Filter by Link Text MGC.apk
> > As of this writing, this config will grab MGC_9.1.098_A11_V5_MGC.apk
> 
> Would you be able to assist me in setting this up for
> 
> https://www.celsoazevedo.com/files/android/google-camera/dev-BigKaka/
> 
> I tried the same set up, but it would grab the 8.5 release and I am hoping for the 9.2

Have you found any solution yet?

**Comment by master-bob** [comment]
I struggled a bit setting this up for BSG's MGC 9.4, so @Redu667, @fabian-st  & any others here are step by step instructions on setting this up for Obtanium 1.6.11 (slight details may change for other versions):

1. Grab the appropriate /dev-XXX/ link for your modded version, in this example it'll be:
`https://www.celsoazevedo.com/files/android/google-camera/dev-BigKaka/` but it could another and all the modder's link end in `dev-MODDER_NAME`.
2. In Obtanium "Add App" by selecting the "+ Add" button on the main screen at the bottom
3. Paste the link from numba-1 in the first box, "App source URL"
4. Under "Additional Options for HTML" tap the "+ Intermediate link"
5. Within the first box labeled "Filter for an 'intermediate' link to visit *" add a custom string
5b. This string will change depending on the version you want. The typical format is some string of letters followed by a more particular version, XXX_Y.Z - there may be an underscore or not. The basic format is the same. In this case add `\bAGC8.8\b` for 8.8 or change the numbers to another version, say 9.6 - `\bAGC9.6\b`.
6. Select the "Filter links by link text" radio button
7. Select "APK link hash" under "Default psuedo-versioning method" (Optional)
8. Add a custom "Version string extraction RegEx"
8b. This string will be based on the string from 5b. In this case it'll be `\bAGC8.8\b\.[A-Z0-9]+_V[0-9]+`. Some basic regex tips are generally a `.` must be escaped by using a `\` prior, so `\.` Any amount of numbers is `[0-9]+`. If you need to test it grab a test string and use a tester like https://regex101.com/.
9. Customize which APK version you want by modifying the "filterAPKsByRegEx" box
9b. This will be something like `scan3d\.apk$` or `[0-9]+\.apk$`. The `$` tells the regex to search at the end of a string.
10. Add appropriate "App name", "Author", and "About" boxes as you please
11. Scroll up to the top and tap the "+" next to the "App source URL" box

Okay. I hope that helps the next person!!
