### ISSUE TITLE
Option to edit link.

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1203]
When projects fork, eg. on github, it becomes necessary to edit the link.  Perhaps you'd consider making that a possibility rather than having to delete the app and then recreate.

Your work is greatly appreciated!

**Comment by ImranR98** [comment]
This would not be worth the added complexity since changing the link would mean having to change the source, which would also mean changing to a completely different set of source-specific additional settings for the app. It's much simpler for the user to just remove and add the app again (I'm guessing this isn't something that needs to be done often).
