### ISSUE TITLE
Support `/tags/<tag>` in the GH API

### ISSUE THREAD

**Issue by brian6932** [ImranR98/Obtainium#1245]
**Prerequisites**
- [x] Ensure your request is not part of an existing issue.
- [x] Ensure you have checked the Obtainium Wiki.

**Describe the feature**

Well at the moment, you can regex filter releases for `Titles` and `Release Notes`. This is pretty expensive just for when a repo has a tag with a specific release schedule.
Basically instead of going to https://api.github.com/repositories/299354207/releases/latest or https://api.github.com/repositories/299354207/releases and choosing the first index (for pre-release inclusions), and/or filtering, I would like to be able to just go to https://api.github.com/repositories/299354207/releases/tags/nightly and pick the first index.

**Describe alternatives you've considered (if applicable)**

Not good imo
![](https://github.com/ImranR98/Obtainium/assets/18603393/a1ef183a-9b89-4673-a7c1-02272f43a0c7)

**Comment by ImranR98** [comment]
[Tags are meant to be unique](https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#about-git-tags) so it doesn't matter how you add it, you will not be notified of updates since the tag never changes.

If you really want to add this specific tag and don't care about updates, you can just add the API URL as an HTML app: `https://api.github.com/repositories/299354207/releases/tags/nightly`

**Comment by brian6932** [comment]
> [Tags are meant to be unique](https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28#about-git-tags) so it doesn't matter how you add it, you will not be notified of updates since the tag never changes.

If you're using `Release Date as Version`, why does that matter?

**Comment by ImranR98** [comment]
Ah, that's a good point. You should be notified of updates in that case. I still don't think this warrants any changes in the app though. The only extra "expense" with using a release title filter is that the app will loop through a few other releases first - negligible performance wise. You could use the new "version extraction" field to filter by tags instead, but this would be effectively the same thing.

If you add the API URL directly as an HTML source, you could use version extraction with that too since the link contains a version number. Then you wouldn't need to loop/filter through anything, but again it is not worth worrying about.

**Comment by brian6932** [comment]
> The only extra "expense" with using a release title filter is that the app will loop through a few other releases first

If this wasn't done on phones where battery life's important, then I'd agree, but doing this many times a day doesn't really make any sense to me, especially when there are first party options that don't require nearly as much computation. And honestly, I expect such a feature in an app that's intended for version tracking, when doing package management there are often times where I use the tag API personally.

> If you add the API URL directly as an HTML source, you could use version extraction with that too since the link contains a version number. Then you wouldn't need to loop/filter through anything, but again it is not worth worrying about.

The problem is `Use Release Date as Version` is unsupported in this format.
![](https://github.com/ImranR98/Obtainium/assets/18603393/ad00dbab-04e6-40c4-ba7f-2cdd0e6f51ee)

**Comment by ImranR98** [comment]
> If this wasn't done on phones where battery life's important, then I'd agree ... especially when there are first party options that don't require nearly as much computation.

I think you are vastly overestimating the cost here. We are talking no more than a difference of a few clock cycles among billions. On top of that, nightly releases come out every day, so the release you want would always be within the first few entries - it's not like we're looping through all releases the API returns. I wouldn't be surprised if the HTTP request library turned out to use more compute just to make the API request.

> And honestly, I expect such a feature in an app that's intended for version tracking

The reason GitHub tags were used as a version indicator is because they are meant to be unique. For developers who don't follow this standard, you can still track their apps using the release dates like you mentioned.

What you need is already possible with no real compromise. It's not worth creating an entirely separate source type which would be redundant and would only serve a tiny minority of use cases.

**Comment by brian6932** [comment]
> What you need is already possible with no real compromise. It's not worth creating an entirely separate source type which would be redundant and would only serve a tiny minority of use cases.

It's not really, versioning by date isn't settable with the `HTML` method you mentioned, you'd have to rely on unconverted z-time timestamps, which aren't very linear.

**Comment by ImranR98** [comment]
> It's not really, versioning by date isn't settable with the `HTML` method you mentioned

Yes, I meant with the normal GitHub method with the insignificant extra cost. You can still use the HTML method but you would not be able to use release dates. Instead, you could just use the actual version number (which I'm now guessing doesn't change between nightlies and so is not usable).

> ofc it's more work.

Sure technically it is, but I _really_ don't see why you care so much about that extra work. It is _extremely tiny_.

Even if we are going to focus on saving every possible CPU cycle, it would make more sense to focus on the sorting that happens (<=100 items to sort) before we even get to the filtering part (usually < 10 loops) - but even that is a drop in the ocean.

Normally I would welcome PRs for features that I don't personally plan to work on, but really this feature would add completely unnecessary complexity for no reason.

**Comment by ImranR98** [comment]
> so the user would have to make their own regex, and then rely on unconverted z-time timestamps

I'm not sure what you meant by this.

**Comment by ImranR98** [comment]
> would have to make their own regex, and then rely on unconverted z-time timestamps, which aren't as linear.

I'm assuming you mean creating a "whole page" regex that could extract the `"created_at": "2023-08-23T04:56:33Z",`? If so that would be hard to get right, but if it's doable I don't see the issue. Not sure what you mean by "aren't as linear."

**Comment by brian6932** [comment]
> Not sure what you mean by "aren't as linear"

Well if you're doing versioning with dates, unix timestamps are extremely simple cause you'd just do int > int, it's a linear number.

> The new version string just has to be different from the current one, we don't make a numerical comparison to see which is bigger).

Ah weird, ok gotcha.

___

Personally, I still feel like this feature should be built in, it logically follows imo when you have nightly/beta specific tags that get bumped on repos, [I've even done it for this exact package on package managers outside of Android](https://github.com/brian6932/dank-scoop/blob/614119391bf72712b9c199cc652509767ce4657d/bucket/rustdesk-nightly.json#L23-L35), but I understand your position.
