### ISSUE TITLE
Reverse mode for intermediate links

### ISSUE THREAD

**Issue by ceskyDJ** [ImranR98/Obtainium#1253]
**Prerequisites**

Hi, I need to add app Datovka to Obtainium. It has releases published right here via Apache directory listing: https://secure.nic.cz/files/datove_schranky/mobile-datovka/. I tried sorting parameters added to the URL, but it does nothing. So, I can't use the intermediate link properly.

**Describe the feature**

So, I think the one solution available here is to add an option for reverse sorting intermediate links. I could you the last one and it should work.

**Describe alternatives you've considered (if applicable)**

I don't know how to solve it alternatively. I'm open to any solutions.

**Comment by ImranR98** [comment]
Whoops, a recent update (v0.15) seems to have broken the URL parsing such that relative links (like the ones on your page) are not extended to absolute URLs. That's what is causing your problem - nothing to do with sorting (there is already a reverse toggle available but won't make a difference here). Will be fixed in the next release.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.6-beta

It should now work with `mobile` as the intermediate link regex (all other settings can be left as default).

**Comment by ceskyDJ** [comment]
It seems to work, thanks!
