### ISSUE TITLE
Changelog for F-Droid apps.

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#1255]
It will be very useful and convenient just like APKPure because they also provide it in their site. I hope it will be an easy task to do.

As an example:
|     |     |
|-------|--------|
|![Screenshot_20240107-224534](https://github.com/ImranR98/Obtainium/assets/114379310/73b1b57c-062f-4ead-a3e2-a7c5ccfd9cd4)|![Screenshot_20240107-224520](https://github.com/ImranR98/Obtainium/assets/114379310/d28c411d-04df-46d7-a9e8-d5df43ef5fed)|

I want also to mention that not all apps provide a changelog on every update, sometimes there is nothing.

Thank you.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.7-beta

**Comment by JohnBetaro** [comment]
I'm sad to say that it is not working, it is like there is no difference after applying the update, it does not even highlight it like the others that has the changelog supported.

I tried reinstalling the apps, I tested [KDE Connect](https://f-droid.org/en/packages/org.kde.kdeconnect_tp/) and [Unitto](https://f-droid.org/en/packages/com.sadellie.unitto/).

**Comment by ImranR98** [comment]
For F-Droid, we get extra info (like author name and changelogs) from the app's YAML metadata file. We don't use web scraping because it is unreliable.

For some reason, KDE Connect's YAML doesn't have changelog or author info: https://gitlab.com/fdroid/fdroiddata/-/raw/master/metadata/org.kde.kdeconnect_tp.yml
As a comparison, others do: https://gitlab.com/fdroid/fdroiddata/-/raw/master/metadata/com.aurora.store.yml

**Comment by BingoKingo** [comment]
Could you add date as well?
