### ISSUE TITLE
NEW SOURCE Shelter Gitea

### ISSUE THREAD

**Issue by sonalder-darlene** [ImranR98/Obtainium#126]
https://gitea.angry.im/PeterCxy/Shelter

**Comment by ImranR98** [comment]
Doesn't seem like they proivde APKs,

**Comment by noClaps** [comment]
Continuing the discussion on Shelter, it seems that their [custom F-Droid repo](https://fdroid.typeblog.net/) doesn't work in Obtainium.

**Comment by bakedonion** [comment]
I don't mean to necro this issue, but the mentioned custom F-Droid repo is in fact usable.

You can use https://fdroid.typeblog.net/index.xml as a reference to figure out the _App ID or Name_, that is a required field when trying to add an app source from an F-Droid Third-Party Repo. This is to avoid ambiguity, since the repository may contain multiple apps.

In this case you can provide `https://fdroid.typeblog.net/` as the _App Source URL_, change the selection for _Override Source_ to `F-Droid Third-Party Repo` and use `net.typeblog.shelter` as the _App ID_. With this you should be able to add the app to `Obtainium`.

Additionally, if you want, you can also perform a manual installation of the app, prior to managing it with `Obtanium`. At the time of this writing the download link for the most recent version would be https://fdroid.typeblog.net/Shelter-1.8.apk. This info is again taken from the `index.html` from above.
