### ISSUE TITLE
[Suggestion] Asset date version detection

### ISSUE THREAD

**Issue by JunkiEDM** [ImranR98/Obtainium#1284]
Not many, but some apps update builds to the same Release tag for CI builds, so the Asset (apk) date would be newer but the Release date would remain the same. An example of a repo using this setup is flex3r/DankChat, where github actions sends new builds to "release" and "debug" tags without updating the Release date for either tag. This also affects Release ordering (e.g "latest"). 
Either a new version detection option using Asset dates or a toggle preferring them over Release dates would solve this.

Related: #102

**Comment by ImranR98** [comment]
This would be tricky for releases with multiple assets (even after applying filters). Instead, it looks like GitHub does update the `created_at` attribute for releases, even when you're only updating an existing release. At least that's what it looks like based on that date being very close to the asset upload dates for this repo: https://api.github.com/repos/flex3r/DankChat/releases

If we can confirm that `created_at` really does get updated whenever the release assets do, we can add a toggle to use that instead of `published_at` which is what is currently used.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.15.11-beta
