### ISSUE TITLE
Gitlab person access token added, gitlab projects "Forbidden"

### ISSUE THREAD

**Issue by angrykid8** [ImranR98/Obtainium#1297]
Could not find an exisiting issue.
Could not find solution on the wiki

I have created a gitlab account, made a new personal access token, input the token into obtainium, when adding this project: https://gitlab.com/divested-mobile/carrion the error produced is ["Forbidden"]
![Screenshot_20231221-210901]
![Screenshot_20240116-123153](https://github.com/ImranR98/Obtainium/assets/66118543/9692f640-4ac0-4f71-8b7f-66714b0ee5c0)

**Please complete the following information:**
 - Device: Pixel 6
 - OS: GrapheneOS
 - Obtainium Version: 0.15.11-beta

**Comment by DarkCrypt** [comment]
You can't add this app because there's no apk release.

Looks like DivestOS Mobile uses GitLab, GitHub, and Codeberg to host source code for all their apps but releases are only available via F-Droid and/or their own F-Droid repo. Carrion appears to be a brand new app and isn't available via F-Droid yet (the link leads to a 404) but is available via their own F-Droid repo. Check out their [Our Apps](https://divestos.org/pages/our_apps) page on the official website for all links.

If you'd like to add this app from their own F-Droid repo I'll explain how:
1. Open Obtainium -> Add App
2. Copy/paste this link into App Source URL: `https://divestos.org/apks/official/fdroid/repo`
3. You'll now see Override Source. Tap the dropdown menu and select F-Droid Third-Party Repo.
4. Type `Carrion` into the App ID or Name.
5. Hit Add.

Carrion will be in your list of apps and can now be installed. Repeat this process if you want to add more of their apps this way, just make sure you use the correct App ID or Name.

**Comment by angrykid8** [comment]
> You can't add this app because there's no apk release.
> 
> Looks like DivestOS Mobile uses GitLab, GitHub, and Codeberg to host source code for all their apps but releases are only available via F-Droid and/or their own F-Droid repo. Carrion appears to be a brand new app and isn't available via F-Droid yet (the link leads to a 404) but is available via their own F-Droid repo. Check out their [Our Apps](https://divestos.org/pages/our_apps) page on the official website for all links.
> 
> If you'd like to add this app from their own F-Droid repo I'll explain how:
> 1. Open Obtainium -> Add App
> 2. Copy/paste this link into App Source URL: `https://divestos.org/apks/official/fdroid/repo`
> 3. You'll now see Override Source. Tap the dropdown menu and select F-Droid Third-Party Repo.
> 4. Type `Carrion` into the App ID or Name.
> 5. Hit Add.
> 
> Carrion will be in your list of apps and can now be installed. Repeat this process if you want to add more of their apps this way, just make sure you use the correct App ID or Name.

Thank you very much!

**Comment by jayb-g** [comment]
@angrykid8 
the error is same for https://gitlab.com/AuroraOSS/AuroraStore and it does have releases, although apk is added to the release as an upload. Could that be the problem ?

**Comment by DarkCrypt** [comment]
I have AuroraStore pulling from GitLab and I haven't gotten any error.

**Comment by jayb-g** [comment]
@DarkCrypt can you please share the URL you are using and which permissions you have allowed for the gitlab access token?

**Comment by DarkCrypt** [comment]
@jayb-g 
I'm using the same URL as your above comment and I don't use an access token. AuroraStore is the only app I'm pulling from GitLab at this time so it's not really necessary.

To attempt to recreate your issue, I created an access token specifically for Obtainium. I also removed AuroraStore from the app, cleared cache, closed/reopened app, added the new access token, and then added AuroraStore. I received no errors, even after refreshing multiple times. (I didn't go as far as completely uninstalling/reinstalling AuroraStore).

Now, I assume you're correct about a problem with your access token permissions. When I created mine I only checked the 1st box:

api = which basically grants all acces

You may not be comfortable with full access permission. I haven't tried anything else yet.
