### ISSUE TITLE
Signature (?) Changed

### ISSUE THREAD

**Issue by nightznero** [ImranR98/Obtainium#1308]
Obtanium 16.0 cannot be installed over last 15.1version

**Comment by marek22k** [comment]
It also shows "F-Droid" releases for me. Which is the different to the normal ones? Does the normal ones include non-FLOSS components?

**Comment by ImranR98** [comment]
@marek22k The only difference between them is the App ID and the fact that the F-Droid variant will not include a default "Obtainium" entry in the app list on new installs. See #30 for details.

@nightznero you must have picked the F-Droid APK instead of the regular one. These are not interchangeable so you need to pick the right one - you can't update from one variant to the other. I suggest using the APK filter settings to automate this (use `fdroid` as the filter, the turn on the invert option).
