### ISSUE TITLE
Unable to match versions correctly

### ISSUE THREAD

**Issue by rancidfrog** [ImranR98/Obtainium#132]
Mechanism to detect version is limited, as only apps installed through obtainium will be able to be updated as app does not detect version otherwise.

However, when using [apkupdater](https://github.com/rumboalla/apkupdater) unmaintained app now.
The app used to be able to detect correctly when an update is available without this limitation.

Not sure how they did it but they were able to detect version number currently installed and compare them to vultiple online sources to see if an update is available.

Currently, app is unusable unless you want to make it the Only updater:
![](https://i.imgur.com/Zui0TBp.png)

**Comment by ImranR98** [comment]
As far as I can see, most sources don't provide the exact `versionName` and `versionCode` strings that Android uses, so the only way to grab the real version of an app is by downloading it's APK, which is unreasonable for update checking. Not sure how to work around this, but I'll take a look at the app you linked.

**Comment by rancidfrog** [comment]
Many apps check automatically via github using this mechanism:
- https://github.com/M66B/FairEmail/commit/055f16368755031280e4a626059eef2e70570ef9
- https://github.com/libre-tube/LibreTube/pull/391

But, I guess that relies on devs using tag names
```
info.tag_name = jroot.getString("tag_name");
                                    Log.i(Helper.TAG, "Lastest version=" + info.tag_name);
                                    if (BuildConfig.VERSION_NAME.equals(info.tag_name))
```
 

This file is where it gets all the installed apps details I believe:
https://github.com/rumboalla/apkupdater/blob/2.x/app/src/main/java/com/apkupdater/repository/AppsRepository.kt

Using - getPackageInfos

Check for updates:

https://github.com/rumboalla/apkupdater/blob/2.x/app/src/main/java/com/apkupdater/repository/apkmirror/ApkMirrorUpdater.kt

https://github.com/rumboalla/apkupdater/blob/2.x/app/src/main/java/com/apkupdater/repository/fdroid/FdroidRepository.kt

https://github.com/rumboalla/apkupdater/blob/2.x/app/src/main/java/com/apkupdater/repository/googleplay/GooglePlayRepository.kt


Installing, not sure if it does silent install, though:
https://github.com/rumboalla/apkupdater/blob/2.x/app/src/main/java/com/apkupdater/util/app/InstallUtil.kt

**Comment by ImranR98** [comment]
Obtainium also uses GitHub tags to determine the version string. The problem is that these tags can only be compared to previous tags (as we do for update checking); they cannot safely be compared to the Apps real `versionName` in the OS because tags are not always the same as versions. Obtainium itself is an example - the latest version tag is `v0.8.1-beta` but if you look at the version in your phone's settings, it is just `0.8.1`. Another example is this where they don't have a version at all in the tag: https://github.com/recloudstream/cloudstream/releases/tag/pre-release

The comparison code above looks like it tries to extract the numbers from the tag, and assumes that will always match the internal real version. This would probably work most of the time, but I'm not sure if its reliable enough.

I'll give it a try at some point with as many different Apps as I can and see how many end up with unreliable behaviour due to bad tag names (like with the CloudStream example). If there are only a few such cases we could switch to that approach and use some other workaround for those cases.

**Comment by ImranR98** [comment]
I've tried making version detection better for Apps where a "standard" version string can be extracted. I'll test it for a while before release, to make sure nothing else has broken. Feel free to test it out too, APKs attached.

[app-release.zip](https://github.com/ImranR98/Obtainium/files/10149221/app-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10149222/app-arm64-v8a-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10149223/app-armeabi-v7a-release.zip)
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10149224/app-x86_64-release.zip)

**Comment by ImranR98** [comment]
I've tried making version detection better for Apps where a "standard" version string can be extracted. I'll test it for a while before release, to make sure nothing else has broken. Feel free to test it out too, APKs attached.

[app-release.zip](https://github.com/ImranR98/Obtainium/files/10149295/app-release.zip)
[app-arm64-v8a-release.zip](https://github.com/ImranR98/Obtainium/files/10149296/app-arm64-v8a-release.zip)
[app-armeabi-v7a-release.zip](https://github.com/ImranR98/Obtainium/files/10149297/app-armeabi-v7a-release.zip)
[app-x86_64-release.zip](https://github.com/ImranR98/Obtainium/files/10149298/app-x86_64-release.zip)

**Comment by ImranR98** [comment]
Released: https://github.com/ImranR98/Obtainium/releases/tag/v0.8.2-beta
