### ISSUE TITLE
Display source link in app page

### ISSUE THREAD

**Issue by NatoBoram** [ImranR98/Obtainium#1336]
**Prerequisites**

**Describe the feature**

In an app's page, I'd expect to be able to see the link of an app's source.

For an example, an app just changed source link but I cannot verify if I added the new source.

![Screenshot_20240124-205528.png](https://github.com/ImranR98/Obtainium/assets/10495562/621db5a9-c991-4f6f-a311-8a2d210ada8b)

**Describe alternatives you've considered (if applicable)**

**Additional context**

I remember this being there previously, but right now I cannot read or edit an app's source.

![Screenshot_20240124-210032.png](https://github.com/ImranR98/Obtainium/assets/10495562/b39fd1bf-d6df-4f7a-a6b7-0d18d87f2d45)

**Comment by ImranR98** [comment]
You can click the author's name or long press to copy the link. Changed it for a cleaner look.

**Comment by DarkCrypt** [comment]
This change does give a cleaner look but I have to agree with NatoBoram.

It was nice being able to see the source link for better usability. It made it stupid easy for users to instantly know where they're pulling updates from because they'll never remember, especially as their app list continues to grow.

Now users are basically forced to click the link to view the source within the in-app webview or an external browser in order to know. This is extremely inconvenient and adds stress to the user.

Otherwise, the only other options to avoid this headache is to include the source name by categorizing within the app list or by copy/pasting the source link into the "About" section within the edit settings of every app. Users can also see the source link by clicking on the app version within the app list to see the changelog but this only works for certain sources.

**Comment by DJCrashdummy** [comment]
this is somewhat related to #1290 which would be en even easier/quicker way to spot the "source" (aka. distributor) for more than one app at a time.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.1
