### ISSUE TITLE
Setting to choose when an .apk should be deleted

### ISSUE THREAD

**Issue by RAPXT** [ImranR98/Obtainium#1360]
**Prerequisites**
Please ensure your request is not part of an existing issue. --> ✅
Please ensure you have checked the Obtainium Wiki. --> ✅

**Describe the feature**
My phone has only 32GB of internal storage. Often almost all storage is occupied.
Therefore I would like to have a setting to configure when an downloaded .apk should be deleted. E. G.
just after install - 1 to 23 hours - days

**Describe alternatives you've considered (if applicable)**
➖

**Additional context**
I've seen #551, but 7 days before cleanup starts, might be to long for some people with low storage devices.

**Comment by ImranR98** [comment]
#551 is outdated. APKs are now deleted immediately after being installed so you should usually have no APKs sitting around in cache. Sometimes an APK might not be deleted because of a failed/cancelled install, or a partial/corrupt download. In those cases, you can either try to install the app again, or just clear Obtainium's cache in the OS settings.
