### ISSUE TITLE
App version doesn't reflect through to work profile

### ISSUE THREAD

**Issue by jayb-g** [ImranR98/Obtainium#1366]
**Describe the bug**
If using obtanium on both owner and work profiles, app updated on one of them doesn't reflect the new version in another profile in obtanium.

**To Reproduce**
First you need to have work profile enabled through shelter/insular or otherwise. And have obtanium installed on both.
1. Choose an app that gets frequent updates. Install it on **both** owner and work profile using obtanium.
2. Wait for a few days for the app to get an update. 
3. Update the app on owner profile. 
4. Check obtanium in the work profile and it should still show that the app has an update; even if you check the app version directly from app info it should show updated version. 

**Please complete the following information:**
 - Device: [Pixel 7] 
 - OS: [GrapheneOS]
 - Obtainium Version: [v1.0.1]

**Additional context**
I'm having this issue with firefox installed through github in obtanium. Also with most/all other apps.

**Comment by ImranR98** [comment]
This is normal for apps whose versions from the OS cannot be reconciled with the version string taken from the source (you'll see that the relevant toggle in the app's settings is always off). See this section of the Wiki: https://github.com/ImranR98/Obtainium/wiki#version-detection (slightly out of date - it's no longer called "version detection").

Not much can be done to solve this - either try using the "version extraction" field to manually trim the string if possible (so that it matches a "standard" format) or just manually tap "mark as updated" in the work profile.

Or just avoid adding an app to Obtainium in both profiles - if it's already in one, there might not be any point in having it in the other.
