### ISSUE TITLE
Deley after pressing edit

### ISSUE THREAD

**Issue by Zumux** [ImranR98/Obtainium#1374]
**Describe the bug**

The edit button in the bottom left corner of the app page is greyed out. If you press it and wait about a second delay it then in grey's out and then you can press it again to bring up the edit page.

**To Reproduce**
1. Go to an app page
2. Tap on the greyed out edit button
3. Wait a second or so
4. Press now no longer greyed out button to see edit page

**Screenshots and Logs**

https://github.com/ImranR98/Obtainium/assets/59784734/4432bdc5-738b-4e74-83de-9e5a05f680c6

**Please complete the following information:**
 - Device: Pixel 6a
 - OS: GrapheneOS
 - Obtainium Version: v1.0.2

**Additional context**

**Comment by ImranR98** [comment]
This is normal. When Obtainium is getting app info from a source, it's important that the app's additional settings don't change since that could cause those changes to be overwritten. So the edit and delete buttons get greyed out anytime updated app info is being fetched. This happens when you:
1. Open the app detail page (if the relevant setting is enabled)
2. Pull down to refresh
3. After editing any app settings
