### ISSUE TITLE
Can't locate Aurora Store APK

### ISSUE THREAD

**Issue by kslcsdalsadg** [ImranR98/Obtainium#1384]
**Describe the bug**
Can't download AuroraStore updates.
I have installed AuroraStore 4.3.5 from GitLab repo
Noticed that versions 4.4.0 and 4.4.1 are out at GitLab repo but Obtanium isn't capable to find it.
Isn't a temporary problem (I have checked for a day before post the issue)

**To Reproduce**
1. Add AuroraStore (from Gitlab repo)
2. Tap on Aurora Store then try to find updates

**Screenshots and Logs**
![image](https://github.com/ImranR98/Obtainium/assets/31618496/5c23c3ee-a9f7-48da-aa74-cd6808086b62)

![image](https://github.com/ImranR98/Obtainium/assets/31618496/abd9447b-cde1-471c-834c-900ade915e62)

**Please complete the following information:**
 - Device: Google Pixel 7 Pro
 - OS: GrapheneOS
 - Obtainium Version: 1.0.2

**Comment by DwainZwerg** [comment]
Duplicate of various issues. You can't add https://auroraoss.com/ (in GitLab wird auf diese Seite verlinkt) to Obtainium since Cloudflare fucks up. If you only want use the alphaversions you could update via https://f-droid.org/en/packages/com.aurora.store/. At the moment, however, F-Dorid does not seem to have uploaded the new versions yet. Please close this issue.

**Comment by kslcsdalsadg** [comment]
Thanks for the answer

**Comment by DwainZwerg** [comment]
Hello @kslcsdalsadg ,
According to https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859, the Aurora Store devs have fixed the problem. The download of AuroraStore should work normally again.
