### ISSUE TITLE
Kodi on f-droid.  Failure.

### ISSUE THREAD

**Issue by DiagonalArg** [ImranR98/Obtainium#1386]
Obtainium 1.0.2
Pixel 7 running GrapheneOS

Kodi: https://f-droid.org/en/packages/org.xbmc.kodi/

Right now, that link shows version 19.4 (arm64-v8a), version 20.2 (-v7a and -v8a), version 20.3 (-v7a)

The proper version for my Pixel 7 is 20.2 (-v8a).  That's what's installed now.  

My Obtainium profile for Kodi has no switches on.  That gives me notification for an update to "20.3 Latest", but of course when I try I'm told it's the wrong version.  I note that the -v7a versions are `org.xbmc.kodi_xxxx000.apk`, while the -v8a versions are `org.xbmc.kodi_xxxx001.apk`.  So, I add the regular expression `1\.apk` to the "Filter APKs by Regular Expression" field.  The response is, "No APK found."  When I change that to `\.apk`, I don't get that response, but then of course it identified 20.3 rather than 20.2.

**Comment by ImranR98** [comment]
This is the info returned by F-Droid: https://f-droid.org/api/v1/packages/org.xbmc.kodi

I don't currently see a way to filter out APKs not ending with '001' because of the order of steps:
1. The first thing we do is select a version (for example 20.3)
2. We then return APKs for that version

The APK filter only runs after step 2 so if we select 20.3 in step 1, the APK you want has already been filtered out.

I'll improve the filter in the next release so that it runs before step 1 as well.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.3

**Comment by DiagonalArg** [comment]
Fantastic!  :pray: 

It only dawns on me now, that another day to do this would have been to filter on architecture first, then on version; but this solves the problem.
