### ISSUE TITLE
Detect

### ISSUE THREAD

**Issue by Baker0o7** [ImranR98/Obtainium#14]
Make It can detect if I already updated it from github

**Comment by ImranR98** [comment]
To do this, the APK would need to be downloaded first, before the App can be added. Nothing wrong with that approach, but it's not how Obtainium does things currently. It's a good idea, but would require a lot of major changes and so probably won't be done anytime soon. Leaving the issue open as I'll hopefully get around to it at some point.

For now, the latest version has an "Already Updated" button on the App page that you can use as a workaround.

**Comment by ImranR98** [comment]
Leaving some notes for my future reference.

Plugins to use:
- [package_archive_info](https://pub.dev/packages/package_archive_info) - to extract ID and version info from APKs.
- [installed_apps](https://pub.dev/packages/installed_apps) - to get IDs and Icons for all Apps installed on device.

Service changes:
- After downloading an APK, we can extract it's "real" ID (`org.example.app` as opposed to our generated `name_author_source` IDs) and "real" version (the one on the settings page as opposed to the one extracted from GitHub or other source) and save this info along with the remaining App info.
- When installing an APK, we skip the install if there is already an App installed with that real ID and real version.
- If the real version being installed is lower than the one already installed, throw an error as that installation will (silently) fail anyways.

Page changes:
- When displaying Apps (both App list and individual App page), we can use an App's real ID (if it was saved, which would be true for any installed App) to get its icon (if it is still installed) and display it (for #57).
- Also on both pages, we can display a warning for to any Apps that are displayed as "Installed" but that were not detected on the device (maybe add a filter for these) so the user can easily remove them from Obtainium. It's better to do this than to automatically remove them as this may not be desired by the user.

Other Notes:
- We still need to keep generated IDs and extracted versions, because these can be obtained without downloading the APK.
	- Using real versions to do update checking, for example, would require downloading the whole APK just to check if it is a newer version. So it is not feasible to do this for update checking, which is done frequently and for all Apps every time. Using "fake" versions is still reliable (enough) and only needs a simple HTTP request.
	- Similarly, an App that was added, but not installed (meaning we don't know it's real ID), still needs an ID so we keep the generated ones.

**Comment by ImranR98** [comment]
I've made some major changes to resolve this issue and #57. Detailed notes in https://github.com/ImranR98/Obtainium/pull/59. Everything seems to work but I don't want to release it yet as I haven't tested it very much, will do so over the coming days. If anyone else wants to give it a try, the build is here:

[app-release.zip](https://github.com/ImranR98/Obtainium/files/9793686/app-release.zip)

Note that upgrading to this version will cause all your existing Apps to be marked as "Not Installed" and you'll have to install them all again (multi-select option should work) as they now use real App IDs instead of the generated ones.

**Comment by S7venLights** [comment]
Will test 👍

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.6.0-beta
