### ISSUE TITLE
Obtainium can't be installed on my device

### ISSUE THREAD

**Issue by LJNeon** [ImranR98/Obtainium#1417]
**Describe the bug**
My phone is on Android 10 and has a Qualcomm Snapdragon 632 CPU, which is ARM and 64-bit. So I downloaded the arm64 release, gave the unknown app permission, and then tapped install. It then said the app couldn't be installed on my device.

**Screenshots and Logs**
![Screenshot_20240221-142023](https://github.com/ImranR98/Obtainium/assets/23249107/0312aaba-f7bf-4677-946a-73148fcffeb3)
![Screenshot_20240221-142115](https://github.com/ImranR98/Obtainium/assets/23249107/e7630ae6-c4c6-4e8e-9235-4a3c843fa2cc)
![Screenshot_20240221-142135](https://github.com/ImranR98/Obtainium/assets/23249107/e4068b66-1b3c-4533-aabf-25a2ad9b90ca)

**Comment by DwainZwerg** [comment]
Does your phone have Android One or an unclean Android (e.g. CustomRoms or MIUI)?

**Comment by DwainZwerg** [comment]
Which model?
I ask because there are two different types of Motorola series. There is the Motorola One series, which uses Android One (Android that is as clean as it comes from Google) and other series that are fitted with Motorola customizations (unclean Android, such as Samsung One UI or MIUI).

**Comment by LJNeon** [comment]
it's the moto e (2020), serial number is XT2052-1.

**Comment by DwainZwerg** [comment]
Ah, I see just now that you're trying to update Obtainium within the Obtainiumapp, right? Did you originally get the app from F-Droid? If so, you can't update it with the GitHub version (same thing in the reverse). That would be the desired behaviour because both apps contain different PackageIDs.

PS: It is definitely a Motorola patched Android and not a clean Android One. I did not need the serial number to determine whether it is clean Android or not and you should also remove this information because it can also be used to do nonsense. Thank you for your answers, although I think a closer look at the screenshots provided would probably have helped you more quickly.

**Comment by LJNeon** [comment]
I have never installed Obtainium before, I have never installed f droid either actually.

**Comment by DwainZwerg** [comment]
What kind of app are you trying to install Obtainium with? Can you try another app or download the latest version of Obtainium again? Other than the fact that the download is corrupt or the install app has a bug, I can only imagine that this is due to some bugs caused by the unclean Motorola Android. @ImranR98 do you have any more ideas?

**Comment by ImranR98** [comment]
You could also try installing this app: https://github.com/deckerst/aves/releases/tag/v1.10.5

It also uses flutter so if it works that would confirm the issue is specific to obtainium (if not, it's something wrong with your OS).

**Comment by LJNeon** [comment]
I tried downloading it from chrome and from brave, neither worked. I then tried installing it from my files app afterwards (screenshots came from that) which gave the same error. I'll try the other version later when I have more free time and get back to you.

**Comment by LJNeon** [comment]
Yea I get the same exact error on that other linked app. So is this something that can't be solved or should I move to flutter because they could do something about it?

**Comment by ImranR98** [comment]
I think you should narrow down what the cause is by trying other apps - it could be specific to Flutter apps, or it might be a more general issue. In any case it's not an Obtainium bug.

**Comment by LJNeon** [comment]
Do you know an app with a github release that doesn't use flutter that I could try?

**Comment by ImranR98** [comment]
You could try any of the apps on https://apps.obtainium.imranr.dev/ - most of them do not use Flutter. But there are other variables that could be involved (the main one being Android SDK an app targets).

**Comment by LJNeon** [comment]
I tried two apps that don't use flutter and both worked immediately. I guess I'll open an issue there next. thank you for the help!
