### ISSUE TITLE
Suggestion : displaying the actually installed apk filename

### ISSUE THREAD

**Issue by Ugau943** [ImranR98/Obtainium#1426]
### Discussed in https://github.com/ImranR98/Obtainium/discussions/1414

<div type='discussions-op-text'>

<sup>Originally posted by **Ugau943** February 20, 2024</sup>
Hi,

Maybe I've missed something somewhere, but I can't find if there's a way to see which APK has been installed by Obtainium, i.e. which APK has been selected in the source.

In this case I'm filtering an APK by regex (on GitHub, where there's an F-droid version and another), but not being absolutely sure of the reliability of my filter, I wanted to make sure of the name of the APK that has actually been downloaded and installed.

So is this information somewhere in Obtainium ?</div>  

---  

From this discussion, it seems that the information is not in the app. So here's a feature request to implement this functionality mentioned in the topic.

I know it's not a core or essential feature, and it's not pressing, but I thought it'd be handy, if not difficult to implement.

**Comment by DwainZwerg** [comment]
@Ugau943 However, you should bear in mind that the real version name (which is sent to the system and is also displayed by Obtanium on the details page) is often different from the filename. The filename of the downloaded file could of course be cached in Obtanium, but if you also install using other installers, the information can very easily become obsolete (because the filename that was downloaded is only cached somewhere).

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v1.0.4
