### ISSUE TITLE
Exclude XAPK

### ISSUE THREAD

**Issue by DrIT2016** [ImranR98/Obtainium#1427]
I would like an option on regular app sources as f.e. apkpure to exclude xapk files/releases from version check.
This way the latest release can be different than latest (as sometimes only an xapk is released or apk later).
That would enable me to turn off the Track-Only option and install via Obtainium which i now don't because of sometimes corrupt app when xapk is pushed first on source.

I have looked at current 2 regex options and configured on apkpure source, but than no version is found if i exclude "xapk" when latest version is only xapk.

**Comment by ImranR98** [comment]
The APK/XAPK list is only extracted after Obtainium picks a release, so implementing this would not be easy. Instead it would make more sense to have a "fallback to older releases" option (like GitHub has) and use that in combination with the APK filter. Unfortunately this isn't possible because I can't figure out how to extract APK URLs for older versions of an app from APKPure.

So your best option is to wait for better XAPK support (#682).

**Comment by DrIT2016** [comment]
Ok will have to wait then, thanks for checking it out.
