### ISSUE TITLE
Incorrectly detect an App as installed and display incoherent status

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1436]
![IMG_20240229_140445](https://github.com/ImranR98/Obtainium/assets/18471069/cf3d9e05-059d-4d39-aa5a-aecea323e7e0)
![IMG_20240229_140412](https://github.com/ImranR98/Obtainium/assets/18471069/3c1c00b2-81a3-41e8-9b09-0411f61fa33a)

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 4
 - OS: Google Android 7.0
 - Obtainium Version: 1.0.3

**Additional context**
Click on the aTalk App give me different status sometime (other than the "null" value that can also appear), as showed above, but in any case this App is in Track-only mode because it's NOT installed.

**Comment by ImranR98** [comment]
When an app uses a "pseudo-version", Obtainium will not attempt to detect whether or not it is installed. Instead, it will try to track the install status internally, and this can sometimes go out of sync (which you then have to manually correct). See the Wiki for details.

Track-Only mode is an extension of this, where Obtainium never even attempts to install the app, assuming you will do so yourself. You can then "Mark as Installed" accordingly.

So I'm not sure what your issue is. If you don't plan on ever installing this app, you have 3 options:
1. Tap on the "reset install status" icon. This will tell Obtainium that the app is not installed. So you won't ever get update notifications.
2. Tap on the "Mark Updated" button. This will tell Obtainium that the app is installed and up to date. So you will only be notified when the next release is out.
3. Do nothing. Obtainium will think the app is out of date and continue to notify you of an available update.

Whether or not the app is actually installed doesn't matter - Obtainium has to track some internal "install status" in order to be useful (provide new update notifications).

**Comment by DwainZwerg** [comment]
Or deactivate the track-only mode, which is very pointless with GitHub ...

**Comment by Sami32** [comment]
@ImranR98 I wasn't aware of the method 1 because i didn't saw anything about this symbol meaning in the wiki, not event a reset option wording.
Then after your comment i finally tried this unkown clock/time symbol to me and eureka...it did the trick.
Method 2 has been used before but as you said it has to be renewed at each new update so not my taste (if you've only 5 App why not...)

My enhancement suggestion is to do it automatically when an App link end with `/tags` in Track-Only mode, used when no releases are done on their GitHub, GitLab, Codeberg... page.
