### ISSUE TITLE
support sources that contains multiple apks

### ISSUE THREAD

**Issue by jaylotw** [ImranR98/Obtainium#1440]
**Prerequisites**

**Describe the feature**
Sometimes the app recognizes the Github URL with multiple apks within a release and asks which one I would like to get, but sometimes it doesn't work.

For new Sources, please ensure:
1. It is not already possible to use the HTML Source for your purposes.
2. It must be possible to extract the following details from the Source in a reliable way:
- The App version (or any release-specific identifier - a "pseudo-version") for the latest release
- One or more APK URL(s) for the latest release
- Above details for previous releases (optional)

If you're not sure about 1 or 2, open a discussion item instead.
Note that the Web scraper cannot deal with JavaScript-enabled content. -->

**Describe alternatives you've considered (if applicable)**

**Additional context**
[Example] 
For source: https://github.com/revanced-apks/build-apps
I am able to pick which apks I want to get.
![Screenshot_20240302_114219](https://github.com/ImranR98/Obtainium/assets/56015530/faf1621a-98b9-46c4-b567-331a496f48f4)

But for source: https://github.com/j-hc/revanced-magisk-module
I am not able to picking apks(it only shows this one) even though there are multiple apks in the latest release.
![Screenshot_20240302_114258](https://github.com/ImranR98/Obtainium/assets/56015530/6d1f5565-8f3e-4c60-a355-3260b182e808)

**Comment by ImranR98** [comment]
What do you mean by it doesn't work? Please provide enough detail and follow the issue template.

**Comment by jaylotw** [comment]
Thank you for the quick reply. I just added two examples and some screenshots. I hope I have conveyed the problem clearly.
Anyway, thank you for the amazing project!

**Comment by ImranR98** [comment]
Again, you haven't told me what the error message is or what exactly isn't working.

Since the developer of that repo has decided to package several different apps under the same release, you have to use the APK filter in Obtainium to filter out all the APKs except the one you need. If you pick one APK when adding the repo but then pick a different APK after clicking install, Obtanium will give you an error because the app that you added is different from the one that you're trying to install.

Please read the wiki and open a discussion post if you have any questions after that because from what I can tell this repo works as expected.

**Comment by ImranR98** [comment]
Okay, I see the problem here. Only one of these APKs has a CPU architecture in the file name, while the others don't. Obtainium filters out all the other APKs because the CPU filter option is enabled by default.

So you need to disable the toggle which says "Attempt to filter APKs by CPU architecture if possible."

**Comment by jaylotw** [comment]
It worked! Thank you so much, again :D
