### ISSUE TITLE
Every Door allows update when it is already latest version

### ISSUE THREAD

**Issue by Coehill** [ImranR98/Obtainium#1451]
**Describe the bug**
When updating Every Door which was originally installed from FDroid, it displays an error message even though they are the same version. 
Obtanium Version: v4.1 Latest
FDroid Version: 4.1.0
![e1fbfa8c-52e6-49fd-b23b-b96180ed92f3](https://github.com/ImranR98/Obtainium/assets/13023025/903bfce5-1f0f-4758-bb30-fca4649d5b2e)
![35165e49-f3c9-4ca0-9ad8-f620a0d1f141](https://github.com/ImranR98/Obtainium/assets/13023025/52831ed2-9310-4744-a572-a792c6a0072b)

**To Reproduce**
1. Install EveryDoor from FDroid
2. Add the source to Obtanium: https://github.com/Zverik/every_door
3. Tap update
4. See error:  Some Errors Occurred: Cannot install an older version of an App [Every Door] 

**Screenshots and Logs**

**Please complete the following information:**
 - Device: Samsung Galaxy S23
 - OS: Android 14
 - Obtainium Version: 1.0.3

**Additional context**
I would expect it to grey out the Update button and be aware that it is up to date.

**Comment by DwainZwerg** [comment]
> I would expect it to grey out the Update button and be aware that it is up to date.

1. I assume that Every Door does not support [reproducible builds](https://f-droid.org/docs/Reproducible_Builds/). This means that you can't install the GitHub version over the F-Droid version either way, because both versions have different signing keys. So either you uninstall the F-Droid version and then install the GitHub version, or you add the F-Droid source in Obtainium (instead of the GitHub source).
2. Moreover, the two versions seem to use different version schemes, which is why Obtanium believes that Every Door is not up-to-date. Alternatively, it may be that the app actually supports reproducible builds, but that the version sheme of the version names in GitHub is different from what the app tells the system (and thereby Obtanium). If this is the case, Obtanium will also keep trying to update where there is nothing to update, which can also lead to problems.

**Comment by ImranR98** [comment]
If it is a version string issue, you can turn off the "reconcile version string..." toggle.

**Comment by Coehill** [comment]
@DwainZwerg Thanks, I learned something new about the reproducible builds!  I added the Version String Extraction RegEx `^[^\d]*(.+)` with Match Group 1 which resulted in:
```
4.1.0 Installed
4.1 Latest
```

I then triggered the same error.  Therefore, the issue must be reproducible builds, right? (Assuming it is smart enough to realize 4.1.0 = 4.1.  Either way, this does have a misleading error message since it suggests it's an older build even if it's not reproducible or if it's a version number problem.

I decided to open an issue for Every Door requesting reproducible builds.

UPDATE: I selected "Reconcile version string with version detected from OS" and it then displayed `4.1 Installed/Latest` and realized that the app was up to date.

@ImranR98 That toggle did not work for me, likely because of the reasons @DwainZwerg mentioned.

**Comment by DwainZwerg** [comment]
> Thanks, I learned something new about the reproducible builds! I added the Version String Extraction RegEx `^[^\d]*(.+)` with Match Group 1 which resulted in […]
> I then triggered the same error. Therefore, the issue must be reproducible builds, right? (Assuming it is smart enough to realize 4.1.0 = 4.1. Either way, this does have a misleading error message since it suggests it's an older build even if it's not reproducible or if it's a version number problem.

No, it only has something to do with reproducible builds in a secondary way and is neither the problem nor necessarily a suitable solution (I had already mentioned the suitable (ad-hoc) solution for you: Uninstall the F-Droid version (unless the app supports reproducible builds (which it probably can't), in which case it wouldn't do any good because it would be a different problem) and reinstall the GitHub version via Obtainium).
I wanted to make it clear that there are (legitimately) problems with Android if you try to install a version with different signing keys on an app. Apps always have different signing keys if they are different. In most cases, the only difference is that one installation file is packed by the developer (GitHub developer) and the other by the store provider (F-Droid). In this case, reproducible builds can help. They are built in such a way that everyone can always and only sign them in exactly the same way. The F-Droid version and GitHub version then have the same signing keys. However, this is of course not useful and not possible if the source code of the two versions differs (I'm not sure if it does).

**Comment by ImranR98** [comment]
Yep, the reproducible builds issue is something to be aware of, but not related to what you're seeing with the version string mismatch.

> I disabled, then enabled "Reconcile version string with version detected from OS" and it then displayed 4.1 Installed/Latest and realized that the app was up to date. Whenever I check the settings again though, it is disabled. Not sure if this is expected functionality.

Yes, Obtainium is supposed to automatically disable that toggle when it notices that the two version strings are incompatible. It should never have been enabled in the first place (should have been disabled as soon as you added the app) - that might be a bug.

Sounds like this is resolved.
