### ISSUE TITLE
Package ID does not match existing App ID (updating OrganicMaps)

### ISSUE THREAD

**Issue by lovfi** [ImranR98/Obtainium#1455]
**Prerequisites**

I believe this issue meets the prereqs. 

**Describe the bug**
When attempting to install the new Organic Maps update, I receive the error: "Downloaded package ID does not match existing App ID - app.organicmaps.web [Organic Maps]."

**To Reproduce**

1. Install Organic Maps via Obtanium (installed version from 2024-02-06)
2. Attempt to install new update from 2024-03-05

**Screenshots and Logs**

I hope I attached the screenshot correctly. I am viewing github in desktop mode on a mobile device, so I may have to readd later. 

**Please complete the following information:**
 - Device:  Samsung S23
 - OS:  OneUI
 - Obtainium Version:  1.0.4

**Comment by lovfi** [comment]
Nope, didn't add correctly. Here they are:
![Screenshot_20240306_235910_1](https://github.com/ImranR98/Obtainium/assets/115566702/2add9d02-3677-413a-88da-2ad53513c1d7)
![Screenshot_20240306_235906_1](https://github.com/ImranR98/Obtainium/assets/115566702/06518200-0b52-4ac7-80b6-6760df64e5d4)

**Comment by Grishnackh** [comment]
Unfortunately it is how @DwainZwerg pointed out. Don't forget to export your saved places if you have some and remember your settings, as they're not inclueded in any exports.

**Comment by ImranR98** [comment]
It looks like they are using different package IDs for beta and non-beta versions. When you added this app, Obtainium picked up a non-beta version, but now it's picking up the latest beta version. You need to turn off the "include pre-releases" toggle. Or you could remove the app from Obtainium and add it again with a filter to only include beta releases. But you can't mix non-beta and beta versions.

@cerels

**Comment by ImranR98** [comment]
My previous comment assumes that they are correctly marking beta versions of their app as pre-releases on GitHub. If not, then the toggle won't work. You'll need to use one of the other filter options.

**Comment by cerels** [comment]
@ImranR98  I actually turned on pre release version because I want to use the beta, not stable, I have never installed the stable version neither on phone or tv, and as far as I noticed, the betas are pre released, already tried other filter options but idk what I'm doing to be honest, I just noticed that obtanium is picking the latest version but just refuses to install it

**Comment by ImranR98** [comment]
Obtainium expects the app ID to be whatever it was when the app was first added. So when you added the app, it must have not picked up a beta version. You need to remove the app, add it back, but this time add a filter so that it only picks up beta versions and never a regular release. There is no toggle for this (no one has needed it so far). You can probably use the release title to filter for betas, but I haven't actually looked at their repo to confirm.

**Comment by cerels** [comment]
`Obtainium expects the app ID to be whatever it was when the app was first added`

Ok this fixed it, what I was doing was adding the app to obtanium and then editing the "pre release" option, so I deleted it, added again but applied that option from the start and it installed, thanks

**Comment by ImranR98** [comment]
If it ever happens that the latest release is not a beta, Obtainium will prompt you to install that non-beta release and you'll see the same error again. So you might still want to filter out non-beta somehow.

**Comment by cerels** [comment]
How would I do this? As I understand obtanium have some form of regex,
smarttube naming convention is simply SmartTube_stable...apk and
SmartTube_beta...apk

How would it works to filter to only install those that have "beta" in the
name?

**Comment by ImranR98** [comment]
Assuming you're talking about this repo: https://github.com/yuliskov/SmartTube/releases

It looks like they have the word beta in the title of all beta releases. So you could just put "Beta" in the release title filter field.

**Comment by ImranR98** [comment]
Ideally, there would just be an "exclude non-prereleases" toggle or something, but we don't have that right now.

**Comment by samuelion** [comment]
Just a small comment as I struggled with somewhat similar issue as cerels, and I'm not sure it is coherent and expected behavior.

To first install organic maps, I went to the following page : https://apps.obtainium.imranr.dev and select organic maps, and add the conf in obtainium.
When I then tried to install, I noticed that there are 2 apk (google and web), so I edit the conf to add a filter to select the "web" version and then retry to first install.
I got the same error saying that ID are inconsistant between downloaded package and existing package (which was not installed ...).

First : the error is misleading, the app was not installed so I struggled and was forced to get on this issue to understand what's happening.
Second : I cannot use https://apps.obtainium.imranr.dev anymore to install organic map anymore as it "preselects" the google version (first in alphabetical order I guess) and then, I cannot change version anymore (cause different ID).

An easy workaround would be to have 2 flavours for organic map, the google and web version in https://apps.obtainium.imranr.dev
But my thought is that ID should not stored and imposed before real first install, or at least, having a meaningful error message, cause "mismatch between download and existing app ID" seems to me not exact.

This is a just to help (app or users facins same issues as me).
Meanwhile, I just love this app and can't live without this app =).

**Comment by EntropicNinja** [comment]
@ImranR98, I would like to echo @samuelion,  

I had [Tutanota](https://github.com/tutao/tutanota/releases) installed via Obtainium but recently it has been failing to update, displaying the same error as stated in this bug.

I have noticed that they now have a calendar app so added a filter for that. Still no joy. I removed and readded the entry from Obtainium, no luck.

I uninstalled the app and now can not reinstall it due to the same error code. Leads me to wonder if Obtainium is storing these `app ids` somewhere? I have restarted the phone and run SD Maid SE which tells me there were no left over data from removed apps.

I have checked other issues and noted that you mentioned `infer app id`, but I no longer see this option. I'm assuming for the security concerns you have expressed about this (please correct me if I'm wrong) it has been removed.

I can install from the Aurora store, but I much prefer Obtainium's update mechanism.

It once worked but now does not. I get a feeling that your gunna ask me to take this up with Tutao. Any ideas would be helpful though. 

TIA.

**Comment by ImranR98** [comment]
@EntropicNinja are ypu trying to install the calendar app?

**Comment by ImranR98** [comment]
@EntropicNinja you probably are still selecting the calendar instead of email due to a bad filter. Try this (in the release title filter): `^[0-9].*Android`

**Comment by EntropicNinja** [comment]
I'm not now, through trial and error I found that, due to them labeling both the calendar and the mail app with the word Android, Ibgainium picks the top release with that filter.  
In this case the calendar app.

The way I folder is with the regex \bCalendar\b in the APK fikter and toggle invert.

I tried your suggestikn and still got the calendar.
![Screenshot_20241022-001105](https://github.com/user-attachments/assets/1663537a-7e0c-42bf-8053-f04d37e1b1c8)
![Screenshot_20241022-001210](https://github.com/user-attachments/assets/ccff1129-f6f2-4f6e-86ad-18ffaf44d209)

**Comment by ImranR98** [comment]
You're missing the `^` from mine, but this works too.

**Comment by EntropicNinja** [comment]
Lucky I updated the post at 😉. Good spot. A quick Andoid copy paste didn't help. 

Your correct, ofc, that yields the same results. Alas it still errors.

**Comment by ImranR98** [comment]
> Alas it still errors.

Yeah you will have to re-add it. Obtainium grabs the app ID when you first add the app.

**Comment by EntropicNinja** [comment]
But this is a readd, I've even uninstalled the app!

**Comment by ImranR98** [comment]
That's weird. And your release filter is already there at the time you add it?

**Comment by EntropicNinja** [comment]
Yep.

**Comment by ImranR98** [comment]
Open a new issue and describe the exact steps you're doing.
