### ISSUE TITLE
Wrong error message when a GitLab repo has no releases

### ISSUE THREAD

**Issue by bwmanske** [ImranR98/Obtainium#1489]
**Prerequisites**

Trying to add suyu emulator project from gitlab.com no prerequisites. 

**Describe the bug**

URL to add:
https://gitlab.com/suyu-emu/suyu-releases/
Adding this temporarily displays "forbidden" 

May be related to a search on only gitlab for suyu-emu results in no results. 

**To Reproduce**

In the first case, enter the full URL above and press "add". 
In the second case, enter suyu-emu press search then select only gitlab. 

**Screenshots and Logs**

**Please complete the following information:**
 - Device: Samsung Tab S9
 - OS: Android 
 - Obtainium Version: v1.0.6

**Additional context**

Conjecture : the releases folder contains folders for versions not all formatted the same. The version folder contains not only the apk but also versions for windows, Mac & Linux.

**Comment by DwainZwerg** [comment]
'forbidden' = Cloudflare
Do you use a GitLab token? If not, then use it.

**Comment by ImranR98** [comment]
This repo just doesn't have any releases to scrape: https://gitlab.com/suyu-emu/suyu-releases/-/releases
For comparison: https://gitlab.com/AuroraOSS/AuroraStore/-/releases

The only bug here is that you're seeing the wrong error message ('Forbidden' instead of 'Not Found').

**Comment by ImranR98** [comment]
The wrong error is also GitLab's fault - Obtainium only reports the message it receives from them. See these examples for comparison:
- https://gitlab.com/api/v4/projects/AuroraOSS%2FAuroraStore/releases (works)
- https://gitlab.com/api/v4/projects/suyu-emu%2Fsuyu-releases/releases (fails with an incorrect error - [should be 404](https://gitlab.com/suyu-emu/suyu-releases/-/releases))

The inconsistency should be fixed on their end, it won't be fixed in Obtainium as this would cause incorrect messages for other cases (not all `403` errors can be assumed to be incorrectly attributed `404`s).
