### ISSUE TITLE
Obtainium prompts for update but doesn't install the apk after downloading

### ISSUE THREAD

**Issue by Aayu1254** [ImranR98/Obtainium#149]
**Apk installation skip because of unusual version number**
Obtainium shows update available when there's a new update and also downloads the update when i press update, but after downloading it just skip the installation and marks the app as updated. The app releases new updates as "latest" and not a version number in github.

**To Reproduce**
1. Add the app Xtra by crackdeded (Source: https://github.com/crackededed/Xtra)
2. Update the app through Obtainium

**Smartphone:**
 - Device: Realme X3 (RMX2081)
 - OS: Android 10
 - Obtainium Version: 0.8.9

**Comment by ImranR98** [comment]
It looks like the developer doesn't increment the App's `versionCode` between releases. So as far as Obtainium is concerned, the downloaded APK doesn't need to be installed as it's identical to the old one. You're supposed to increment the `versionCode` for each version, so this is something the dev would need to fix on their end.

Also I wouldn't depend on reliable update notifications for this App since Obtainium checks the version by looking at the release tag and comparing it to the previous one. Would't work here as the dev uses "latest" as a tag. Again, tags are meant to identify a specific commit so reusing the same one doesn't make sense to me, and isn't something Obtainium can do much about.
