### ISSUE TITLE
Directory error on all attempts to add a source

### ISSUE THREAD

**Issue by kavemang** [ImranR98/Obtainium#1546]
After some recent update the apps i had saved in unobtanium disapeared and when i try to add any back i get the following error

![SmartSelect_20240417_104452](https://github.com/ImranR98/Obtainium/assets/66108693/3d1db478-350f-417e-afe7-0a4c65ae95e7)

 - Device: Galaxy S22 Ultra
 - OS: Android 14
 - Obtainium Version: 1.12 & 1.14

**Comment by ImranR98** [comment]
Does your file manager app show anything in the `data/dev.imranr.obtainium` folder?

**Comment by kavemang** [comment]
It looks like both my file manager and unobtanium cant see into data folders anymore. Is this android 14?

**Comment by DwainZwerg** [comment]
> It looks like both my file manager and unobtanium cant see into data folders anymore. Is this android 14?

Yeah, it's due to Android 14 that you can no longer access the folders starting from /storage/emulated/0/Android. Try using a decent file manager such as [TotalCommander](https://play.google.com/store/apps/details?id=com.ghisler.android.TotalCommander), [FileManager+](https://play.google.com/store/apps/details?id=com.alphainventor.filemanager) and [MiXplorer](https://xdaforums.com/t/app-2-2-mixplorer-v6-x-released-fully-featured-file-manager.1523691/#post-23109280), which usually still work. If all else fails, you can also try "[Files](https://play.google.com/store/apps/details?id=com.marc.files)"; this should work.

**Comment by kavemang** [comment]
I used files as the quick light option thanks a lot

**Comment by DwainZwerg** [comment]
> Does your file manager app show anything in the `data/dev.imranr.obtainium` folder?

This question would be important to answer in order to help you with the bug.

**Comment by kavemang** [comment]
> > Does your file manager app show anything in the `data/dev.imranr.obtainium` folder?
> 
> This question would be important to answer in order to help you with the bug.

The moment i installed that files app the issue w android 14 resolved and im both able to see into that folder and obtanium works normally again. I checked around and other people having similar issues w data access also had this experience

This is resolved and hopefully lots of ppl on newer devices find this as they get their os upgrade rollout

**Comment by ImranR98** [comment]
Seems like an OS bug, I don't see why installing one app should affect another.

**Comment by kavemang** [comment]
> Seems like an OS bug, I don't see why installing one app should affect another.

I dont think your wrong at all but from what i can see its affecting anyone using apps that access data directory and dont come from playstore and that files all for some reason is correcting the issue for people when they get upgraded

**Comment by ImranR98** [comment]
Not sure what to do about that aside from maybe pinning the issue if it affects a lot of people. The data dir is the right place for apps to store files (storing things elsewhere requires dealing with SAF, permissions, etc.).
