### ISSUE TITLE
Autodetect installed apps

### ISSUE THREAD

**Issue by GEkuL** [ImranR98/Obtainium#1579]
Hi there, 

I installed the Obtanium, but it seems that I have to manually add all the APS and their sources, which poses a bit of a challenge.

I saw a similar OSS project -  https://github.com/rumboalla/apkupdater which seems to have this auto-detection feature, but lacks on a clear design (_e.g. I want to see the exact source the binary is going to be downloaded from_ ).

Could you please add the auto-detection so it was easier for new users to join and start using the app?

**Comment by DwainZwerg** [comment]
Check previous issues (#223).

**Comment by ImranR98** [comment]
Yes, this has been covered in previous issues. Auto detection would only work if there was a way to reliably get app IDs from sources without downloading the APKs first.

This is possible for some sources, but not for GitHub and GitLab which are the top most commonly used ones.

From what I can tell, AppVerifier is able to do auto detection because it treats all sources as equal and grabs APKs from wherever they are available. In practice this means it usually suggests APKs from sites like ApkPure, Aptoide, etc. (which do provide app IDs) instead of places like GitHub which are usually more "direct from the developer" (in my testing, GitHub was suggested for just 1 app out of 30+ GitHub apps I have installed). This is a fine approach for those who prefer it, but not what Obtainium has gone for.

**Comment by DwainZwerg** [comment]
@ImranR98 Have you actually read [this comment](https://github.com/ImranR98/Obtainium/issues/163#issuecomment-1407767540)? It suggests to check if the app is signed by F-Droid or IzzyOnDroid and if this is not the case, to assume that the app comes from the source URL given on F-Droid (GitHub, GitLab, SourceForge, Codeberg) and has been signed. Wouldn't that be a method that is at least unreliable, but worth considering?

**Comment by ImranR98** [comment]
@DwainZwerg missed that. Replied there.
