### ISSUE TITLE
Track only is forcefully checking for a "suitable release" and blocking addition of new apps.

### ISSUE THREAD

**Issue by xcfmc** [ImranR98/Obtainium#1628]
For a while, I have been unable to add non-android projects that I wanted to track. The app now forces a "suitable release" to be available. Also, several android apps have suitable releases, but they are being reported as not having a release. This project has a release, but gives that error:

https://gitlab.com/engy4life/scrcpy-android

Is it possible to bypass release checking for Track Only apps? It is possible to turn off release checking for an app that Obtanium is failing to detect? I'd like to at least manually install the app and have Obtanium alert me of new versions. 

On a side note, thanks for your hard work on this project. This is one of the first apps I install on new android devices, and one of the most important apps to have.

**Comment by ImranR98** [comment]
The repo you linked has neither [tags](https://gitlab.com/engy4life/scrcpy-android/-/tags) nor [releases](https://gitlab.com/engy4life/scrcpy-android/-/releases). You need at least tags in order to add as track-only (otherwise what would it be tracking?). They do have an APK available but it's part of the actual repo source. You could probably use the "Direct APK Link" (Source Override menu) to add it since it looks like the URL never changes.

Do you have examples of repos with tags/releases that you can't add?

**Comment by xcfmc** [comment]
Here's an example of one I'd like to track that has releases, but isn't for android:

https://github.com/merbanan/rtl_433/

It's not an android project, but it would be cool if obtanium could still alert me to new versions. I have several non-android projects working in obtanium currently, but they were added prior to the addition of release checking. I'll see if those can be added under the current version, on another android device, and share those links/results as well.

**Comment by ImranR98** [comment]
Not sure what you mean by "prior to the addition of release checking" - there have been no recent changes to the way apps are added/tracked. The link you provided works fine in track-only mode.
