### ISSUE TITLE
PathAccessException

### ISSUE THREAD

**Issue by Sami32** [ImranR98/Obtainium#1668]
When trying to "Download release asset" for the already manually installed Silence App i get a PathAccessException error.

**To Reproduce**
1. Add the Silent App to Otainium: https://f-droid.org/packages/org.smssecure.smssecure
2. Tap on it
3. Then click on "Download release asset"
4. See error --> PathAccessException

**Screenshots and Logs**
![IMG_20240612_133551](https://github.com/ImranR98/Obtainium/assets/18471069/6ee0a1b1-2601-4aa0-a052-42fa1597f3a5)

![IMG_20240612_132721](https://github.com/ImranR98/Obtainium/assets/18471069/b38fc05b-d697-4b81-9b71-e198aabd7138)

**Please complete the following information:**
 - Device: Xiaomi Redmi Note 4
 - OS: Google Android 7.0
 - Obtainium Version: 1.1.10

**Comment by ImranR98** [comment]
This may be an issue with Xiaomi's Android skin because it works fine on my Android 7.0 emulator (there have been other issues with MIUI, for example APK installation).

Could you check that Obtainium has storage access permissions? Also does this happen with all apps or only this one? Also if there is already a `.part` file in `/Download` you can try deleting it.

**Comment by Sami32** [comment]
Oups...you was correct, i didn't have the Storage permission for Obtainium.
I never tried to download asset before and forgot to set it for this use case 8~
