### ISSUE TITLE
Github releases with long list not showing all available apks

### ISSUE THREAD

**Issue by TaivasJumala** [ImranR98/Obtainium#1687]
An example is:
https://github.com/revanced-apks/build-apps/
 
where revanced-youtube is shown in extended release list, but won‘t  be presented in obtainium.

**Comment by gabrielparca** [comment]
try adding "/releases" to the url

**Comment by TaivasJumala** [comment]
![Screenshot_20240625-174742_Obtainium.png](https://github.com/ImranR98/Obtainium/assets/72904966/e49754b8-0ef3-4e50-aa6a-8c1841124383)

You can see that, it only shows a maximum of five available apps.

**Comment by gabrielparca** [comment]
Right. Thought the problem the program had fetching would be the "see more" of long lists, which if you go to the releases it shows all not depending on any further action, ie displays all formats without hiding any.

**Comment by ImranR98** [comment]
This is because Obtainium tries to filter out all APKs that don't appear to match your CPU architecture. In this case, there are some APKs containing the string "`arm64-v8a`" which is an exact match for one of your available architectures. So Obtainium decided to filter out anything that did not contain an exact match for one of your archs (the other 2 were not matching because the developer used the string "`arm-v7a`" instead of "`armeabi-v7a`".

You can disable the "filter by CPU architectures" option and try again.
