### ISSUE TITLE
F-Droid 3rd party repo URLs contain nonfunctioning App-ID

### ISSUE THREAD

**Issue by firefoxlover** [ImranR98/Obtainium#1708]
Many apps are only available through F-Droid 3rd party repos.

For example Cromite:

1. URL: https://www.cromite.org/fdroid/repo
2. Then you need to manually change the type of the repo to "f-droid 3rd party repo"
3. Then enter the AppID (I use F-Droid basic and share the app to get it)
4. Then the app is saved as `https://www.cromite.org/fdroid/repo?appId=org.cromite.cromite`

So now the AppID is saved in the URL. 

I would assume directly adding such an URL would work, but it doesnt work.

I add that link, set the type manually to "F-Droid 3rd party repo" and still need to enter an app id.

----

1. Is this a bug? Would downloads work with just the AppID in the URL? This would make URL backups easier
2. Should Obtainium allow a repo without the app ID?

The workaround is to add the appID in the URL another time in the dedicated field.

GrapheneOS latest, Obtainium latest

**Comment by firefoxlover** [comment]
Yeah ignore that example. There are others though.

I wouldnt use Cromite at all anymore, as they build in shady code like the adblocker, made by the company that makes "uBlock" (not "origin")

**Comment by ImranR98** [comment]
Not a bug. F-Droid URLs don't usually have an `appId` parameter so I never expect a user to paste such a URL in manually. Obtainium just adds it so that multiple apps from the same repo can have unique URLs (this was important at some point, could probably be done differently now). It's also useful for the third-party repo search feature that was added recently.

> I would assume directly adding such an URL would work, but it doesnt work.

It would work if you could tap the "Add" button but it won't let you since the "App Id" field further below is empty. Making that field non-required depending on user input is not practical.
