### ISSUE TITLE
Several apps version codes and updates are completely wrong

### ISSUE THREAD

**Issue by RBWare** [ImranR98/Obtainium#1717]
The following applications that I use show completely the wrong updates and don't seem to have an easy way to address. At the same time, it seems like the application should be seeing them just fine. I get notifications pretty regularly that some of these apps, "May have been updated".

Amethyst - https://github.com/vitorpamplona/amethyst
![Screenshot_20240712-104258](https://github.com/user-attachments/assets/42b47fa1-fc95-4a7c-8000-6fb3dd093edd)

Proton Mail - https://github.com/ProtonMail/proton-mail-android
![Screenshot_20240712-104303](https://github.com/user-attachments/assets/0a961667-3ddc-4fc1-ab1c-f76fc531f0fd)

Wikipedia - https://f-droid.org/packages/org.wikipedia
![Screenshot_20240712-104308](https://github.com/user-attachments/assets/fd7da7d5-fa5f-478c-bca0-755ca4c02422)

Proton Drive, and Proton Calendar were also exhibiting this behavior but I was able to press "Mark Selected Apps as Updated".

**Comment by ImranR98** [comment]
For Amethyst, you need to turn on the "Include Prereleases" toggle because the version you've got is marked as pre-release.

For ProtonMail, you're using an archived repo. The current one is https://github.com/ProtonMail/android-mail.

Not sure what's going on with Wikipedia. What happens when you click update?

**Comment by RBWare** [comment]
ProtonMail was the archived version, I didn't realize they'd changed. It seems to be working fine now.

For Wikipedia, I get semi-regular notifications that it "may have been updated". But it doesn't. If I open Obtanium and press the download button, it fails to update (which it should, because the 2020 version is definitely older).

**Comment by ImranR98** [comment]
Sometimes F-Droid returns releases in the wrong order. See if the "Suggested VersionCode" or "Highest VersionCode" toggles help.

**Comment by unoukujou** [comment]
> Sometimes F-Droid returns releases in the wrong order. See if the "Suggested VersionCode" or "Highest VersionCode" toggles help.

Is there a way to see the list of releases from the F-Droid repo? This way I can see the list and filter them by regex how I want.

**Comment by DwainZwerg** [comment]
> "Suggested VersionCode"

I had already tried it when I saw this issue. But for some reason, it doesn't work. That's why I left the issue open.

**Comment by LightWayUp** [comment]
F-Droid source is correct. [All versions of Wikipedia app past June 2020 have been disabled and are not available anymore](https://gitlab.com/fdroid/fdroiddata/-/commit/db1c7fe7639851b00c6a25b1390d322dfe5e054c) due to the use of [Play Install Referrer Library](https://gitlab.com/fdroid/fdroid-suss/-/commit/d8b230fb3acac43830dc03aa15465ea8b7a1ce13).

**Comment by gabrielparca** [comment]
try this toggle setup
●●○ ○○●○ ○○○

![Screenshot_20240722_105429](https://github.com/user-attachments/assets/6aaf2f3c-8db8-4333-bc15-f172fa49c176)

**Comment by LightWayUp** [comment]
> F-Droid source is correct. [All versions of Wikipedia app past June 2020 have been disabled and are not available anymore](https://gitlab.com/fdroid/fdroiddata/-/commit/db1c7fe7639851b00c6a25b1390d322dfe5e054c) due to the use of [Play Install Referrer Library](https://gitlab.com/fdroid/fdroid-suss/-/commit/d8b230fb3acac43830dc03aa15465ea8b7a1ce13).

[Latest versions of Wikipedia are back on F-Droid again](https://f-droid.org/packages/org.wikipedia/), starting from release 2024-07-23, available since August 9th. The app should update normally via Obtainium now.

---

- [F-Droid news regarding repository cleanup, and Suspicious or Unwanted Software Signatures scanner update](https://f-droid.org/2024/07/04/twif.html#community-news)
- [Related issue in F-Droid/Data](https://gitlab.com/fdroid/fdroiddata/-/issues/3328)
- [Exclude InstallReferrer library from F-Droid build. - Wikimedia Phabricator](https://phabricator.wikimedia.org/T369814)
- [Pull request to exclude InstallReferrer library from F-Droid build](https://github.com/wikimedia/apps-android-wikipedia/pull/4800), was merged on July 12th, and another related fix was merged on July 18th

**Comment by DwainZwerg** [comment]
@RBWare @ImranR98 Aren't all the problems fixed now so that this issue can be closed?
