### ISSUE TITLE
Problem with versions

### ISSUE THREAD

**Issue by acress1** [ImranR98/Obtainium#1736]
Hi, 

**Describe the bug**
I have some issues on Obtainium. The app announces me that there are some apps not up to date. When I click, the last version is an old version, even if a more recent one is on the platform (f-droid). 

In the meantime, I should have an update offered for AntennaPod (v3. 4.1 available and I have 3.4.0) and I don't have ! 

**Screenshots and Logs**
![Screenshot_20240718-172205_Obtainium](https://github.com/user-attachments/assets/f308d661-8e76-4bfa-9ea0-3d54cec87177)
![Screenshot_20240718-172158_F-Droid](https://github.com/user-attachments/assets/a3068aeb-2371-4c16-9932-1374a3acb18c)

**Please complete the following information:**
 - Device: ONEPLUS 5T
 - OS: LineageOS
 - Obtainium Version: Last one
 -

Thanks !

**Comment by ImranR98** [comment]
Not an Obtainium issue. For some reason the F-Droid API is not kept up to date (more specifically, updates are delayed).

The API still says 24.2.4.2 is the latest version: https://f-droid.org/api/v1/packages/org.documentfoundation.libreoffice

Obtainium uses the F-Droid API instead of scraping the webpage since that's more reliable. It's on F-Droid to make sure their API actually works.
