### ISSUE TITLE
Help: issues auto updating smarttube beta in background

### ISSUE THREAD

**Issue by jeyjai** [ImranR98/Obtainium#1738]
I'm having some problems getting smarttube beta to auto update in the background on my android tv.
At first i thought it was because i had the app running when it tried updating so i lowered the background check to 30min, i assumed the background update was tied to the background check, but it still never updated.

Tried uninstalling smarttube and installing it through obtainium because i had problems with another app till i manually pressed the update button for it in obtainium, but that didn't help either.

Ive set it up to include prereleases, filter titles for "Beta", and even added filter apks by "arm64-v8a" (even tho its already filtering by cpu architecture), just to be sure. So it's definitely finding the correct apk and if i press the update button on either the apps tab or smarttubes own page, it updates just fine, no issues or extra prompts, so I don't get why its not updating by itself in the background.

I of course closed smarttube during this time, ive even force closed it and it still wont update by itself in the background.
Am i missing something, is there anything else i can do to fix this?

.

Im also wondering about the timing for the background updates, is it directly tied to the background update check, is there a delay, or does it have its own timer that we can't change?
It would help to know when i have issues like this and testing things.

**Comment by ImranR98** [comment]
Yes, background updates happen right after the background update check. The app must satisfy these conditions: https://github.com/ImranR98/Obtainium/wiki#background-updates
The fact that it updates silently in the foreground (with no extra prompts) means it should update in the background too (unless there's some other requirement I forgot about) so I'm not sure what's going on there. Do other updates work?

**Comment by Adhjie** [comment]
There's an in-app auto-updater, actually. Even though the first installation could be varied, the easiest one is the aftv. Also be careful with beta releases, read the changelog. If you update to a bug ridden beta release, you will get error specified to that release bug e.g., 304 etc.
I use stable to avoid this.
You could also side load with send to TV app.
You sure the auto updater doesn't work after first installation?
Scroll down to settings and almost to the bottom of the list, there's an update button.
Set your setting to always start at setting tab instead of home page.

**Comment by Adhjie** [comment]
There's an in-app auto-updater, actually. Even though the first installation could be varied, the easiest one is the aftv. Also be careful with beta releases, read the changelog. If you update to a bug ridden beta release, you will get error specified to that release bug e.g., 304 etc.
I use stable to avoid this.
You could also side load with send to TV app.
You sure the auto updater doesn't work after first installation?
Scroll down to settings and almost to the bottom of the list, there's an update button.
Set your setting to always start at setting tab instead of home page.

**Comment by jeyjai** [comment]
@ImranR98 looked at the smarttube apk and it says "target: 8.0 (SDK 26 Oreo)"
I wouldn't really consider that recent so that's likely the problem here.



@Adhjie ive been using the beta for years and never had any issues other than the 304 lately, and even that has been fixed, but me using beta or stable is completely irrelevant to my question.
And who said the auto updater doesn't work? I use obtainium with shizuku to get rid of the update prompts and manually updating the apps when i open them, which happens a lot more often on beta versions, so with obtainium everything is updated in the background.

**Comment by Adhjie** [comment]
@jeyjai I don't use shizuku or something similar because, I'm worried if it got detected by banking apps. Even tho, I want it for sd maid SE, banking app most of the time is so better than other detection app like Gplay protect.
I take most apps as mission critical apps, and use only stable now. Very worried if I got locked out because of bugs, etc. and I can't back up/export the settings and data.

Background update for SmartTube in Obtainium is indeed slow, or SmartTube actually put so much frequent release, not sure between the two.

**Comment by jeyjai** [comment]
@Adhjie oh ok, i totally get what you're saying but shizuku is completely safe in that regard. Shizuku is basically just using ADB commands in the background and bypass certain prompts or slightly elevates a few permissions, so nothing that breaks any of their security parameters, or is able to on it's own. 

The first major step when rooting devices and voiding your warranty is unlocking the bootloader, which is also what breaks safetynet and knox if you're on a samsung galaxy, but 95% of apps that stop working are using safetynet to verify if the phone is secure and shizuku can't effect safetynet (the other 5% is knox and other BS which shizuku can't effect either)

Side note: even when rooted there's ways to get safetynet working again, or even to hide root for those apps completely

**Comment by jeyjai** [comment]
@ImranR98 looked at the smarttube apk and it says "target: 8.0 (SDK 26 Oreo)"
I wouldn't really consider that recent so that's likely the problem here.

**Comment by jeyjai** [comment]
@ImranR98 is there really no way around it since its still able to do the same process without any popup whatsoever with obtainium in the foreground but not background?

I'm not a dev so i dont have a clear understanding how older api level effects background updates other than on those older apps that get the extra popup forcing you to click "install anyway".  
But this is android tv and i don't think that's a thing on android tv, not sure tho.
