### ISSUE TITLE
Some toggle functions in Github sources are abnormal 

### ISSUE THREAD

**Issue by jbwfu** [ImranR98/Obtainium#1744]
**Describe the bug**
Switching to versionCode as the app version cannot be restored to using the actual version number.

**To Reproduce**
1. Add a GitHub update source for the installed app (the actual version number of the app is used in this case)
2. Turn on "Reconcile version string with version detected from OS" and "Use app versionCode as OS-detected version" at the same time (versionCode is used at this time)
3. Close the two toggles opened in step 2 and refresh them (the versionCode is still used at this time, but the configuration at this time is the same as that added in step 1) 

**Screenshots and Logs**
* Step 1
<img src="https://github.com/user-attachments/assets/22810bb1-1d21-4167-b843-a0756dae3198"  width="400" />

* Step 2,3
<img  src="https://github.com/user-attachments/assets/b6a747b2-4fce-46ce-8988-3ac5cc696d71" width="400" />

**Please complete the following information:**
 - Device: Xiaomi POCO F3
 - OS: crDroid
 - Obtainium Version: 1.1.14

**Comment by jbwfu** [comment]
It is currently found that the purpose of recovery can be achieved by marking it as updated and then revoking the mark instead of deleting and recreating it.

**Comment by ImranR98** [comment]
Obtainium keeps its own internal record of what version an app is on - this is based on user actions like installing, updating, etc. and the "version" here can be any string unique to that app (like a version code, release date, etc. - it doesn't have to be the actual version like `1.5.2`).

On the other hand, Android has its own "version" which is the actual version string provided by the app - like `1.5.2`. This can be affected by actions taken outside of Obtainium (updating the app through the Play store or other means).

When the external version changes, Obtainium can't know the nature of that change or whether it means the app needs to be updated. Sometimes it can reconcile the internal and external versions if they conform to a standard format. When this is not the case (as in your case above), it just assumes an update is available. If you know that's not true, you can "mark as updated". If the version detection went wrong, you can reset it.

It's hard for me to understand exactly what your issue is or why you're mixing up two separate things (version code and OS version detection). But I suggest reading the Wiki to understand how these work (or just leave everything at default settings).
