### ISSUE TITLE
aptoide: FGO apk cannot be installed (Incompatible)

### ISSUE THREAD

**Issue by soredake** [ImranR98/Obtainium#1795]
**Prerequisites**

**Describe the bug**
`Incompatible` error when installing FGO english apk from aptoide

**To Reproduce**
1. Add https://fategrand-order-english.en.aptoide.com/app to applications list
2. Try to install it
3. `Incompatible` error

**Screenshots and Logs**
![изображение](https://github.com/user-attachments/assets/5d8715d1-d204-4646-9add-5c04541a0847)

<details>
<summary>Logs</summary>
2024-08-17 07:27:33.428: info: Cleared 93 logs (before = null, after = null)

2024-08-17 07:28:10.852: error: Incompatible
</details>

**Please complete the following information:**
 - Device: Motorola Edge 40
 - OS: Android 14
 - Obtainium Version: [v1.1.19](https://github.com/ImranR98/Obtainium/releases/tag/v1.1.19)

**Additional context**

**Comment by ImranR98** [comment]
The Aptoide API only provides a single APK URL: https://ws2.aptoide.com/api/7/getApp/app_id/68289544 (under `node.meta.data.file.path`)

So if the APK they provide isn't compatible with your device, there's nothing Obtainium can do.

That said, there might be something wrong with this app specifically from the developer's side messing up the APK, given #1794. You could try installing through the official Aptoide client app and see if that works (if it works, they may be using an APK that their API doesn't link to and if it doesn't work, that confirms the issue is from the dev).
