### ISSUE TITLE
Added adguard but it shows at once that an update is available

### ISSUE THREAD

**Issue by topcaser** [ImranR98/Obtainium#1797]
Hi, I added adguard via your market place but it shows at once after installation, that an update is available. But this update isn't installable. The version I installed is 4.6.61, but the latest on github is 4.6.1.

**Comment by ImranR98** [comment]
Yes, this is normal. Obtainium sees that the version you have installed is different from the latest GitHub release, so it thinks an update is available. Of course, in this case it would be a downgrade, but Obtainium doesn't try to decide which version string is higher since that isn't reliable (some apps have very strange versioning schemes). Also some users do downgrade (#107).

I suggest sticking to whatever app store or download method you got `4.6.61` from since it seems to have newer versions than GitHub. Or just uninstall `4.6.61` and install `4.6.1` from GitHub. Or ignore the update notification and wait for GitHub releases to catch up.

**Comment by topcaser** [comment]
> I suggest sticking to whatever app store or download method you got `4.6.61` from since it seems to have newer versions than GitHub.

Hi, I installed it directly via obtainium. I used first of all the obtainium search to find adguard. Then the beast was installed via obtainium to show directly after installation an update. Then I deinstalled it and removed it from obtainium again to get it not via Obtainium search but via your market place which delivers pre configured app configurations. But still the same result.

The question is, why sees obtainium a new version and install it rather to sich to the latest label? Or I can formulate the question in another way: why uses Obtainium another mechanism to find the latest version during initial installation rather than during update check?
