### ISSUE TITLE
Consider publishing Obtanium on Accrescent

### ISSUE THREAD

**Issue by ghost** [ImranR98/Obtainium#1817]
**Describe the feature**

Accrescent is a private and secure Android app store built with modern features in mind. It aims to provide a developer-friendly platform and pleasant user experience while enforcing modern security and privacy practices and offering robust validity guarantees for installed apps.

Documentation: https://accrescent.app/docs/guide/getting-started/index.html

**Describe alternatives you've considered (if applicable)**
Downloading from the available sources.

**Additional context**
Accrescent is still in early alpha.

**Comment by ImranR98** [comment]
Looking through their requirements, I'm not sure Obtainium would satisfy this one: https://accrescent.app/docs/guide/appendix/requirements.html#self-updaters

**Comment by PrivacyAndSecurity** [comment]
I agree, that we would love to see Obtainium on Accrescent! Maybe you ask why we want this or what Benefits it would have for us as Users.

The Benefits for me would be a few, like these:

- I could get Obtainium from Accrescent, which I already installed and use to download Apps. It would save me time and would make it a lot easier for me. I prefer Accrescent over Github, because on Accrescent the App get's checked before it comes to the Store and the Apps are always checked, like for example the SDK of Apps, if there is Malware and more.

- Apps on Github are not checked, but on Accrescent they are going trough Filters always. And I think that would make it more secure. And since Accrescent is on a good way in terms of Security and Privacy, I think that it will be really good in the Future. And I think that Apps which value Security and Privacy should make it available there. Because Accrescent have the same values in Security and Privacy.

- I really hope that you Guys could make that possible, because it would have great Benefits for us as Users. And think like that: If we support them by adding Apps, we help them to grow from Alpha to Stable.

**Comment by DwainZwerg** [comment]
If I'm right, the option for Obtainium to update itself is disabled in the reproducible F-Droid version, isn't it?

**Comment by randomwithnoname** [comment]
This would be really helpful, especially for GrapheneOS users where Accrescent is mirrored in their App Store. I do also wonder whether it would be allowed on Accrescent though. Alternatively, Obtainium could be mirrored in the GrapheneOS App Store.

**Comment by randomwithnoname** [comment]
I asked in the Accrescent Matrix room if Obtainium would be allowed and explained that there's already the F-Droid variant which isn't preset to update itself. The response from the lead developer was "Third-party app sources aren't currently allowed within Accrescent"

This issue can be closed and reopened if anything changes.

**Comment by PrivacyAndSecurity** [comment]
I hope that it will come one day to Accrescent, when it can update itself.

**Comment by randomwithnoname** [comment]
> I hope that it will come one day to Accrescent, when it can update itself.

That doesn't seem to be the issue. Obtainium already has a variant that doesn't update itself for release on F-Droid. I'll ping @lberrymage so he can give a better response.

**Comment by PrivacyAndSecurity** [comment]
> > I hope that it will come one day to Accrescent, when it can update itself.
> 
> That doesn't seem to be the issue. Obtainium already has a variant that doesn't update itself for release on F-Droid. I'll ping @lberrymage so he can give a better response.

Oh okay. I will wait then to the response.

**Comment by lberrymage** [comment]
Accrescent doesn't currently plan on hosting other app sources, so Obtainium wouldn't be allowed even if its self-update functionality was disabled.

**Comment by Geblaat** [comment]
> Accrescent doesn't currently plan on hosting other app sources, so Obtainium wouldn't be allowed even if its self-update functionality was disabled.

Thanks for the reply!
