### ISSUE TITLE
[Question] Which permissions need to be given for Github Personal Access Token?

### ISSUE THREAD

**Issue by yqs112358** [ImranR98/Obtainium#1830]
I have generated a Fine-grained Github Personal Access Token with `Public Repositories (read-only)` repo access. However, when I was searching and adding a batch of apps from Github, I still faced with API request rate limit (need to retry 30 minutes later).

So... which permissions exactly need to be given for Github Personal Access Token to improve API request rate limit?🤔

**Comment by grm34** [comment]
_the token should only need the minimal read access permission_

See https://github.com/ImranR98/Obtainium/wiki#github

**Comment by yqs112358** [comment]
![image](https://github.com/user-attachments/assets/da812144-263f-4714-bb2a-e5f49239f8c1)
This seems to be correct I think... 
So it's strange to see the limitations again 🤔 I remember that with personal access token the request rate limitation will be up to 100,000 times in an hour.

**Comment by grm34** [comment]
No it's not. You must use classic token with `read:packages` perm which allows to _Download packages from GitHub Package Registry_

**Comment by soredake** [comment]
@ImranR98 can information provided by @grm34 be documented on https://github.com/ImranR98/Obtainium/wiki#github page?

**Comment by Dev123456689** [comment]
I generate a personal token (classic) with access to both read public repo and read packages but I am still facing the API request rate limit issue. What should I do?

![IMG_20240925_130034](https://github.com/user-attachments/assets/34c791ad-dc47-4f29-a046-421f5367170a)

**Comment by ImranR98** [comment]
Not sure what's going on here. I'm currently using a fine-grained token with no extra access:
![image](https://github.com/user-attachments/assets/b45ff809-295a-46d8-8797-d5bb72bb6c08)

**Comment by js12h** [comment]
I ran into this a few weeks ago. Try running this script and see what is returned. If your token is correct and accepted, it will show 5000.

Mine wasn't and I ended up creating a new Github account, using a real email address (instead of an alias like I normally do). Verified the email address w/ Github. Ran this command and it showed 5000. Don't know if my original email alias, even though authenticated, was causing the limit to stay low or if it was just an old account. Either way, I have been fine since I created a new account and verified the email address. The classic token works fine. I haven't tried the fine-grained token yet but will.

Note; w/ this script, you can use Bearer or Token:

curl -L \
  -H "Accept: application/vnd.github+json" \
  -H "Authorization: Bearer <YOUR-TOKEN>" \
  -H "X-GitHub-Api-Version: 2022-11-28" \
  https://api.github.com/rate_limit

**Comment by js12h** [comment]
Just tested the fine-grained token and verified it works as well. Though for now I will stick w/ the classic token.

Hope this helps.

**Comment by ImranR98** [comment]
Thanks @js12h 
Added a line to the Wiki: https://github.com/ImranR98/Obtainium/wiki#github

@yqs112358 please try those steps. We can re-open the issue if https://api.github.com/rate_limit shows you a high limit but Obtainium still gets rate limited.

**Comment by yqs112358** [comment]
Okay, I have tested the request and returned a correct result:
```
"rate": {
    "limit": 5000,
    "used": 2,
    "remaining": 4998,
    ...
```
BTW I haven't encountered rate limit again recently. It seems to be OK all the time. 😊 
I will try to query this API in case I encounter it again in the future. Thanks so much!

**Comment by js12h** [comment]
Excellent. Glad to see everything is working well for you now.
