### ISSUE TITLE
Conflict error when updating Obsidian

### ISSUE THREAD

**Issue by noto10** [ImranR98/Obtainium#1909]
When updating Obsidian, the installation ends with the following error: 

![Screenshot_20241017-093450](https://github.com/user-attachments/assets/42ee71f0-9044-414a-ba76-7b4a42081ece)

Here is the video clip of installation process: 

https://github.com/user-attachments/assets/d27b9468-e4e4-4abc-9c9a-70acbc25ed3c

Samsung Note 10

**Comment by ImranR98** [comment]
Did you originally install it through Obtainium?

**Comment by noto10** [comment]
> Did you originally install it through Obtainium?

No, but it was from the same source - Github release.

**Comment by ImranR98** [comment]
Hmm, not sure what's going on (I received that same update earlier with no issue). Could you try manually downloading and installing the new release? Conflict errors ar usually from Android so I expect it to fail.

**Comment by noto10** [comment]
> Hmm, not sure what's going on (I received that same update earlier with no issue). Could you try manually downloading and installing the new release? Conflict errors are usually from Android so I expect it to fail.

I tried that. Still failed. I think you're right. Probably will need to uninstall and re-install. No worries. Thank you for checking.

**Comment by mdecourcy** [comment]
I run into this issue very frequently. Most recently with bitwarden beta. Just downloaded and installed via my browser and without installing fine. Let me know if there's any other info that could help.

**Comment by Bakr-Ali** [comment]
I have run into this issue with another app (URLCheck), where I was 100% sure I downloaded the app from obtainium (see screenshot), and the app 100% didn't change its signature. But it turned out to be user error: I changed the app source inside Obtainium from f-droid to github _after I already downloaded it_. I confirmed it using App Manager where the signature clearly indicated being signed by f-droid (see 2nd screenshot). 

<details>

<summary>screenshots</summary>

![Image](https://github.com/user-attachments/assets/d1b2d82b-a97a-4d1c-a13d-4bb9b8114a41)

![Image](https://github.com/user-attachments/assets/3d85e4e5-5027-4d38-aac2-a259b7371b19)

</details>

**Comment by ztx-lyghters** [comment]
~It would be great to have an option to "force update" the app despite any conflicts, because the alternative is to lose settings and cache, due to the need to uninstall it. In my case it's a music server client with over 2000 songs cached, gets pretty annoying to deal with that.~

Nevermind, I cannot update outside of Obtainium either, so that's not an Obtainium issue.
