### ISSUE TITLE
Package ID does not match existing App ID (Installing Tutoanota)

### ISSUE THREAD

**Issue by EntropicNinja** [ImranR98/Obtainium#1925]
I had [Tutanota](https://github.com/tutao/tutanota/releases) installed via Obtainium but recently it has been failing to update, displaying the Package ID error in the title.

I have noticed that they now have a calendar app so added a filter for that. Still no joy. I removed and readded the entry from Obtainium, no luck.

I uninstalled the app and now can not reinstall it due to the same error code. Leads me to wonder if Obtainium is storing these `app ids` somewhere? I have restarted the phone and run SD Maid SE which tells me there were no left over data from removed apps.

I have checked other issues and noted that you mentioned `infer app id`, but I no longer see this option. I'm assuming for the security concerns you have expressed about this (please correct me if I'm wrong) it has been removed.

I have filtered for the correct APK with both `^[0-9].*Android` under title & using `\bCalendar\b` whilst toggling "Invert Regular Expression".

**Comment by DarkCrypt** [comment]
I've discussed this a few times.

Tutanota Config:
- [Tutanota - GitHub](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22de.tutao.tutanota%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Ftutao%2Ftutanota%22%2C%22author%22%3A%22tutao%22%2C%22name%22%3A%22Tuta%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22releaseTitleAsVersion%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5B0-9%5D%2B%5C%5C%5C%5C.%5B0-9%5D%2B%5C%5C%5C%5C.%5B0-9%5D%2B%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22tutanota-app%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22An%20email%20service%20with%20a%20strong%20focus%20on%20security%20and%20privacy%20that%20lets%20you%20encrypt%20emails%2C%20contacts%20and%20calendar%20entries%20on%20all%20your%20devices.%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D)

**Comment by DarkCrypt** [comment]
Clearing Obtainium's cache manually doesn't help?

**Comment by EntropicNinja** [comment]
Forward: your link to the Tutanota config worked beautifully. Thanks.

SD Maid seems to do it manually. It requires you to leave the screen on and then taps the required areas on the screen automatically. Same as if you was to tap it.

I must say my regex game is weak, but when I filtered as stated it did only select what seem to be correct.

![Screenshot_20241022-002211](https://github.com/user-attachments/assets/6aaf7cbf-61d1-4147-af49-85494086b4cd)

**Comment by DarkCrypt** [comment]
No, not from Obtainium Config site, I use my own configs. If you look around I'm quite active this way.

This is my above config breakdown.
 
My Config:
- URL: `https://github.com/tutao/tutanota`
- Override Source: `GitHub`
- Trim Version String: `[0-9]+\.[0-9]+\.[0-9]+` (to only get version # instead of long ugly string)
- Filter APKs by Regular Expression: `tutanota-app`
- About description

I did try to use your config which worked for me like this.

Your Config:
- URL: `https://github.com/tutao/tutanota`
- Override Source: `GitHub`
- Filter Release Titles by Regular Expression: `^[0-9].*Android`
- Could add trim version string
- Could add about description if desired

I'm not sure why or what `\bCalendar\b` is for. It appears to be unnecessary.

**Comment by DwainZwerg** [comment]
I've added the config to my pull request for the website: https://github.com/ImranR98/apps.obtainium.imranr.dev/pull/270

**Comment by DarkCrypt** [comment]
@EntropicNinja 
Your welcome friend, I try to help if I can. I was posting config breakdowns in other posts but then stopped. I wasn't sure if anyone was paying attention to detail, maybe I'll continue again.

I think I understand your configs more clearly now. ImranR98's ReGex works well as stated in the above config breakdown but the other config doesn't work for me. If I'm correct, this is what the config looks like.

Config:
- URL: `https://github.com/tutao/tutanota`
- Override Source: `GitHub`
- Filter APKs by Regular Expression: `\bCalendar\b`
- Invert Regular Expression (Filter APKs by Regular Expression): `Toggle on`

This config doesn't filter out the calendar releases. I added the app this way and it imported the calendar release instead of the app release. If I add ImranR98's ReGex to this config it works correctly which means this config itself doesn't work.

Or am I misunderstanding?

**Comment by EntropicNinja** [comment]
I think you should continue. Especially as in this thread someone has pulled your configs into the site. Must be worth something 😎

Well then I'm not sure. Your break down is correct but it did filter it out for me 🤷🏼 even without ImranR98's RegEx, but I got the error stated in this thread when trying to install.  
If I removed `\bcalendar\b` (I write in my previous posts with a capital C for clarity, but not in my config - dunno if that difference matters?) and replaced with Imran's RegEx I got the same result and it still didn't install with the exact same error?? 🤦  
Yours on the otherhand was flawless!

Do you have a repo of public configs?

**Comment by DarkCrypt** [comment]
I agree to continue. Posting config breakdowns is helpful for others to learn and also helpful to DwainZwerg and Hamster45105 for maintaining the Obtainium Config site. They would be able to quickly see if an app is worth adding or not. They've also added multiple configs I've posted which is very exciting to me!

I retried your 2nd config using `\bcalendar\b` and it worked without issue. `\bCalender\b` doesn't work because the characters don't match. The uppercase C doesn't match the lowercase c (as we can see in the above screenshot). So now this means both of your configs worked for me.

This is what I think happened.

1. Obtainium was updating Tutanota app without issue as normal. (No filter was necessary)
2. Tutanota introduced their Calendar app within GitHub releases.
3. Obtainium sees this as a new app update because of no filter.
4. Without knowing, you hit the button to update the app and Obtainium downloads the Calendar release causing the Package ID mismatch.
5. You then see this error and check GitHub releases to find out what's going on.
6. Now you know you need to add a filter to eliminate the Calendar apps and do so accordingly. But it's already to late and now your config won't work.

The only way I know how to fix this is to remove the app from Obtainium, close out of Obtainium, and then clear Obtainium's cache. After doing this the app should be able to be readded with the proper filters and updates should work correctly again. It sounds like you did this with SD Maid SE but you were still having issues?

To answer your question, no I don't have a repo of configs.

**Comment by EntropicNinja** [comment]
This is why I love open-(insert here, source/hardware/community).  
Blur said it best, "it gives me an enormous sense of wellbeing!"

Yeah, you have it down pat, thats exactly the steps I took! Strange that clearing the cache didn't work. Took a different config to make it work again

**Comment by ImranR98** [comment]
Hmm, still not sure what happened here. After adding the filter in step 6 (from DarkCrypt's comment) it should have started working again (without needing to remove/re-add). Anyways glad to hear it's working now.

**Comment by EntropicNinja** [comment]
Can't be to sure myself. 2 thoughts.  
1. SD Maid did not clear the cache as well as I believed it to.  
2. A day after this happened my phone updated (GrapheneOS 15 stable). I had some network connectivity issues and the whole UI was slow to respond (swiping, notification shade, multitask app switching). A second reboot fixed it.  
Maybe it had a precursor and was not the update but the 🤷.
