### ISSUE TITLE
Brave Browser on Obtainium For Android Phones GOS

### ISSUE THREAD

**Issue by stantonlarson** [ImranR98/Obtainium#1952]
When Brave Browser is downloaded to Obtainium it downloads but it will not install. I contacted GOS and they suggested that this was an issue with your app. 

This is the message I get when I try to install Brave on Obtainium.

It says ( Unexpected Error ) Range Error ( start ) invalid value: Not in inclusive range 0.1:-1

This was the feedback I received from Graphene OS:  Looks like a configuration error in Obtanium? Its trying to access index -1 in a range of 0.1. I'd look for a channel for Obtanium to get support and/or manually review the Brave entry configuration

Can you please review this report and see if your app can be fixed to install Brave.  Thanks

**Comment by stantonlarson** [comment]
![Brave Browser](https://github.com/user-attachments/assets/0bef17a5-6dc9-4432-96fc-6005d4928a2b)
![Message when I click install](https://github.com/user-attachments/assets/469fd4ae-8b65-4bb5-8b52-f3abe5c848cd)

**Comment by DwainZwerg** [comment]
Clearly looks like an incorrect configuration. What do your settings look like?

Otherwise, try these settings:
includePrereleases = true
fallbackToOlderReleases = true
verifyLatestTag = false
versionExtractionRegEx = Relea
versionDetection = true

**Comment by stantonlarson** [comment]
Good Afternoon

These are my settings and still not working. All other apps I had install are working as intended including the updates

Thanks 


Nov 5, 2024, 05:40 by ***@***.***:

**Comment by stantonlarson** [comment]
![Screenshot_20241105-124845](https://github.com/user-attachments/assets/6c392a1f-3216-4c15-80c5-517849e1f43b)
![Screenshot_20241105-124955](https://github.com/user-attachments/assets/df09cb61-66e5-4094-9aed-6cda2ec147a4)
![Screenshot_20241105-125026](https://github.com/user-attachments/assets/addf3b13-631c-4ca0-8e28-70c126d71aca)

**Comment by DwainZwerg** [comment]
Verify Latest Tag must be false!

**Comment by stantonlarson** [comment]
![Verify the latest tag](https://github.com/user-attachments/assets/949f3620-72f4-4c18-80a1-be5ee21153c5)

I am still getting the same error

**Comment by DarkCrypt** [comment]
@DwainZwerg 
stantonlarson is using the config from Obtainium's Config website which is producing the issue.

@stantonlarson 
This config is for stable version Bravearm64Universal.

Brave Config:
Install Link: [Brave (Stable)](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.brave.browser%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fbrave%2Fbrave-browser%22%2C%22author%22%3A%22brave%22%2C%22name%22%3A%22Brave%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Atrue%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22Release%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22releaseTitleAsVersion%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22Universal%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22Brave%20browser%20for%20Android.%20An%20open-source%2C%20lightning%20fast%2C%20safe%20and%20private%20web%20browser%20with%20AI%2C%20Adblock%2C%20and%20VPN.%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D)
- URL: `https://github.com/brave/brave-browser`
- Override Source: `GitHub`
- Include prereleases: `Toggle ON`
- Fallback to older releases: `Toggle ON`
- Filter Release Titles by Regular Expression: `Release`
- Filter APKs by Regular Expression: `Universal`
- About: `Brave browser for Android. An open-source, lightning fast, safe and private web browser with AI, Adblock, and VPN.`

**Comment by stantonlarson** [comment]
This conf file you provided me worked. What was causing the issue ? thanks

**Comment by DarkCrypt** [comment]
You're welcome friend. This table is a comparison of the differences between the configs.
|                 Obtainium Website Config                	|                                                                                             Revised Config                                                                                             	|
|:-------------------------------------------------------:	|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:	|
|              Include prereleases: <br> OFF              	|                                                           Include prereleases: <br> **ON** <br> (Some stable releases are tagged pre-release.)                                                          	|
| Filter Release Titles by Regular Expression: <br>  NONE 	| Filter Release Titles by Regular Expression: <br>  **Release** <br>  (Brave offers 3 different versions within GitHub releases. Stable, Beta, and Nightly. Using this filter targets stable releases.) 	|
|            Verify the `latest` tag: <br>  ON            	|        Verify the `latest` tag: <br>  **OFF** <br>  (Some stable releases are tagged latest and some are tagged pre-release. This needs to be off in order to retrieve updates from both tags.)        	|
|       Trim Version String With ReGex: <br>  Relea       	|                                                                  Trim Version String With ReGex: <br>  **NONE** <br> (Filter not used.)                                                                 	|
|      Filter APKs by Regular Expression: <br>  NONE      	|                        Filter APKs by Regular Expression: <br>  **Universal** <br>  (Brave offers multiple apks. Using this filter targets the Bravearm64Universal apk.)                       	|

**Comment by DwainZwerg** [comment]
should be corrected
