### ISSUE TITLE
AppVerifier on Obtainium Apps

### ISSUE THREAD

**Issue by stantonlarson** [ImranR98/Obtainium#1958]
There are may Obtainium apps that can't be verified with AppVerifier. These are a few samples:

Thunderbird

Organic Maps

OsmAnd

Tor Browser

Obtainium

Privacy Cell
![Obtainium](https://github.com/user-attachments/assets/241ba174-7de8-469d-86b7-d127b3ddcd77)
 
Will you be so kind as to check why this happens please.. I moved over from Fdroid as it was recommend by Graphenene but this unknown verification statuses do not inspire confidence in this app vs fdroid. Thanks

**Comment by ImranR98** [comment]
In order to verify an app, you have to know what the app's signature hash is. You can then compare it with what AppVerifier shows you. Most of the time it's your responsibility to find that information from a trusted source. This could be the developer's website or somewhere else.

For a small number of apps, AppVerifier itself includes signature information in its internal database, which means for those specific apps, App Verifier itself can act as the trusted source. Which is why you see a tick next to those few apps. For the rest, it's on you to hunt down the relevant information and verify it using AppVerifier.

I suggest you read more about what AppVerifier does and why it's useful. Their repos's homepage may be a good place to start.

Either way, this is not an issue with Obtainium nor AppVerifier.
