### ISSUE TITLE
k9mail version isn't correctly detected

### ISSUE THREAD

**Issue by kslcsdalsadg** [ImranR98/Obtainium#1966]
**Describe the bug**
The installed version and the github version from k9mail isn't correctly checked.
I'm at K9 8.1 but Obtainium says there is an update.

K9mail repo: https://github.com/thunderbird/thunderbird-android

Why for some apps it exists a check at the down to mark app is updated but not for some others?

Thanks

![image](https://github.com/user-attachments/assets/1f36b462-b424-4b4b-903e-2834e0ca4218)

**Please complete the following information:**
 - Device: Google Pixel 7 Pro
 - OS: GrapheneOS 15 (also occurs in GrapheneOS 14(
 - Obtainium Version: 1.1.30 (also in previous)

**Comment by DwainZwerg** [comment]
Hello @kslcsdalsadg,
please check other issues and discussions before opening a new one (see https://github.com/ImranR98/Obtainium/discussions/1869).
The problem is that your configuration is not correct. Either you manually add a ‘K’ to filterReleaseTitlesByRegEx or you take the [configuration from the website](https://apps.obtainium.imranr.dev/).
> Why for some apps it exists a check at the down to mark app is updated but not for some others?

Because these apps are either a) set to track-only or b) Obtainium uses pseudo versions (usually because correct versioning is not possible). Please check the [Wiki](https://github.com/ImranR98/Obtainium/wiki) for such general questions.

**Comment by kslcsdalsadg** [comment]
I apologize. 
The solution at #1869 doesn't work for me. I comment at that thread and close this one.
Thanks again
