### ISSUE TITLE
Bitwarden app version is not correctly parsed

### ISSUE THREAD

**Issue by kslcsdalsadg** [ImranR98/Obtainium#1967]
**Describe the bug**
The installed version and the github version from Bitwarden isn't correctly checked.
I'm at Bitwarden  2024.11.3 but Obtainium says there is an update.

Bitwarden repo: https://github.com/bitwarden/android

Why for some apps it exists a check at the down to mark app is updated but not for some others?

Thanks

![image](https://github.com/user-attachments/assets/9861a444-0d68-427f-9745-79a48c196608)

**Please complete the following information:**
 - Device: Google Pixel 7 Pro
 - OS: GrapheneOS 15 (also occurs in GrapheneOS 14(
 - Obtainium Version: 1.1.30 (also in previous)
 -

**Comment by DarkCrypt** [comment]
Not an Obtainium issue.

The above Bitwarden repo link `https://github.com/bitwarden/android` (current repo) is correct but the link within your screenshot is `https://github.com/bitwarden/mobile` (old repo). You'll need to readd the app in order to change the link to be correct. I also see you have no apk filter in place since it says 2 APKs, the current repo will have 5 APKs.

This config will fix the issue and include a proper filter: Import App -> [Bitwarden](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22com.x8bit.bitwarden%22%2C%22url%22%3A%22https%3A%2F%2Fgithub.com%2Fbitwarden%2Fandroid%22%2C%22author%22%3A%22bitwarden%22%2C%22name%22%3A%22Bitwarden%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22includePrereleases%5C%22%3Afalse%2C%5C%22fallbackToOlderReleases%5C%22%3Atrue%2C%5C%22filterReleaseTitlesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22filterReleaseNotesByRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22verifyLatestTag%5C%22%3Afalse%2C%5C%22dontSortReleasesList%5C%22%3Afalse%2C%5C%22useLatestAssetDateAsReleaseDate%5C%22%3Afalse%2C%5C%22releaseTitleAsVersion%5C%22%3Afalse%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Atrue%2C%5C%22releaseDateAsVersion%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22bitwarden.apk%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22A%20password%20manager%20app%20that%20securely%20stores%20and%20manages%20passwords%20and%20other%20sensitive%20information%20across%20devices.%5C%22%7D%22%2C%22overrideSource%22%3A%22GitHub%22%7D)

@DwainZwerg 
Obtainium's Config website needs to change to the current Bitwarden url, right now it's the old one. All other settings and filters are still correct.

**Comment by kslcsdalsadg** [comment]
Thanks, is working now
