### ISSUE TITLE
Forward me to the app page when duplicating

### ISSUE THREAD

**Issue by xxx508** [ImranR98/Obtainium#2016]
Currently, Obtanium works like this:
You search for app on given sources, or paste the app source url (like github), Obtanium proceeds to download apk, which can be heavy, then proceeds to check for the duplicate and if it finds one, it just says about it:

![Screenshot_20241209-213227_Obtainium.png](https://github.com/user-attachments/assets/5fb967c9-f50d-4c41-a0a8-9cea66c27f90)

Why not forward me to the application screen with such source or name (check for source before download apk or for app package name as it seems right now)?

**Comment by ImranR98** [comment]
In order to check whether you already have the app installed, Obtainium needs to know the app's package ID and it can't know that without first downloading the app. There are a few exceptions to this - in some cases, Obtainium can know the package ID in advance and in those cases you won't see it attempt a download. So if you see it downloading before showing you the message, then that's unavoidable.
