### ISSUE TITLE
Telegram's latest version is changing after every refresh

### ISSUE THREAD

**Issue by Marocco2** [ImranR98/Obtainium#2025]
**Prerequisites**

Add Telegram via Obtainium preset on the website

**Describe the bug**

Obtainium doesn't pick up a stable latest version of Telegram and it will message about a new version release

**To Reproduce**

1. Go to Telegram page
2. Refresh

**Screenshots and Logs**

https://github.com/user-attachments/assets/fda16638-01e4-4038-97c8-3bd2e2d29877

**Please complete the following information:**
 - Device: Pixel 8 Pro
 - OS: GrapheneOS
 - Obtainium Version: V1.1.34 

**Additional context**

**Comment by ImranR98** [comment]
This is likely due to https://github.com/ImranR98/Obtainium/issues/2027 (the setting gets reset for some reason). For now, you can manually change the "Pseudo-Versioning Method" back to "Partial APK Hash" and then mark as updated.

**Comment by Marocco2** [comment]
> For now, you can manually change the "Pseudo-Versioning Method" back to "Partial APK Hash" and then mark as updated. 

I can't. It's imported as DirectApkLink, not HTML (which I don't know how to set up)

**Comment by DarkCrypt** [comment]
I understand the reason to remove Telegram as a dedicated source but I fail to understand why the config website is using "Direct APK Link". I have a config for "HTML" source if you want me to post it?

**Comment by Revival8697** [comment]
The version of Telegram can be checked with https://github.com/DrKLO/Telegram/blob/9dcd88b8c12b2ef8eaa05ffe5f89e096a738d735/gradle.properties#L17.

**Comment by leo-liar** [comment]
I just checked (after the Obtainium update switching Telegram to a regular HTML setup) and I also don't see the regular HTML config page (only a subset of options and no way to change pseudo-versioning)!

**Comment by DarkCrypt** [comment]
Wasn't able to extract the version so we're stuck with the ugly APK hash string of numbers unfortunately. Because of this it'll also say "Pseudo-Version". I'll also include a config breakdown.

Telegram config for "HTML" source.
Import App -> [Telegram](https://apps.obtainium.imranr.dev/redirect?r=obtainium://app/%7B%22id%22%3A%22org.telegram.messenger.web%22%2C%22url%22%3A%22https%3A%2F%2Ftelegram.org%2Fandroid%22%2C%22author%22%3A%22telegram.org%22%2C%22name%22%3A%22Telegram%22%2C%22preferredApkIndex%22%3A0%2C%22additionalSettings%22%3A%22%7B%5C%22intermediateLink%5C%22%3A%5B%5D%2C%5C%22customLinkFilterRegex%5C%22%3A%5C%22apk%5C%22%2C%5C%22filterByLinkText%5C%22%3Afalse%2C%5C%22skipSort%5C%22%3Afalse%2C%5C%22reverseSort%5C%22%3Afalse%2C%5C%22sortByLastLinkSegment%5C%22%3Afalse%2C%5C%22versionExtractWholePage%5C%22%3Afalse%2C%5C%22requestHeader%5C%22%3A%5B%7B%5C%22requestHeader%5C%22%3A%5C%22User-Agent%3A%20Mozilla%2F5.0%20(Linux%3B%20Android%2010%3B%20K)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F114.0.0.0%20Mobile%20Safari%2F537.36%5C%22%7D%5D%2C%5C%22defaultPseudoVersioningMethod%5C%22%3A%5C%22APKLinkHash%5C%22%2C%5C%22trackOnly%5C%22%3Afalse%2C%5C%22versionExtractionRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22matchGroupToUse%5C%22%3A%5C%22%5C%22%2C%5C%22versionDetection%5C%22%3Afalse%2C%5C%22useVersionCodeAsOSVersion%5C%22%3Afalse%2C%5C%22apkFilterRegEx%5C%22%3A%5C%22%5C%22%2C%5C%22invertAPKFilter%5C%22%3Afalse%2C%5C%22autoApkFilterByArch%5C%22%3Atrue%2C%5C%22appName%5C%22%3A%5C%22%5C%22%2C%5C%22shizukuPretendToBeGooglePlay%5C%22%3Afalse%2C%5C%22allowInsecure%5C%22%3Afalse%2C%5C%22exemptFromBackgroundUpdates%5C%22%3Afalse%2C%5C%22skipUpdateNotifications%5C%22%3Afalse%2C%5C%22about%5C%22%3A%5C%22A%20cloud-based%20mobile%20and%20desktop%20messaging%20app%20with%20a%20focus%20on%20security%20and%20speed.%5C%22%2C%5C%22refreshBeforeDownload%5C%22%3Afalse%2C%5C%22supportFixedAPKURL%5C%22%3Afalse%7D%22%2C%22overrideSource%22%3A%22HTML%22%7D)
- App Source URL: `https://telegram.org/android`
- Override Source: `HTML`
- Custom APK Link Filter by Regular Expression: `apk`
- Default Pseudo-Versioning Method: `APK Link Hash`
- About: `A cloud-based mobile and desktop messaging app with a focus on security and speed.`

*If you already have v11.5.3 installed, after importing the above config Obtainium will suggest an update. The APK hash string of numbers 126950255 is the same version. You can hit update and go that route or you can hit the checkmark and "Mark as Updated".

*I haven't tried this config until I seen this post, so far it has eliminated the constant update issue.

**Comment by ImranR98** [comment]
> Default Pseudo-Versioning Method: APK Link Hash

This will not work because the APK link is `https://telegram.org/dl/android/apk` - it doesn't change when updates are released so the hash won't change and Obtainium won't know there has been an update.

**Comment by ImranR98** [comment]
And you're right, Telegram was converted to a "Direct APK Link" source, not HTML. I confused this for the WhatsApp issue #2022. @Marocco2 you'll need to keep using the pseudo-version - just tap the "mark as updated" button.

**Comment by DarkCrypt** [comment]
My above config retrieves the apk from the same link as the "Direct APK Link". I understand your reason for why my config won't work. So the "Direct APK Link" works because it doesn't check for the hash?

**Comment by ImranR98** [comment]
Your config doesn't work because it uses the APK link hash - if you switch to "partial APK hash", it will work (this means hashing the first few KB of the APK itself to see if it hash changed). That's what the "direct APK link" source does, but it skips the unnecessary step of loading the HTML page first (telegram.org/android).

**Comment by ImranR98** [comment]
Should be in the app config settings (pencil icon on the bottom left)

**Comment by ImranR98** [comment]
Are you on the latest version?

**Comment by ImranR98** [comment]
Not sure why you don't have the dropdown:
![Screenshot_20241213-030550](https://github.com/user-attachments/assets/59f53631-091c-4ea1-945b-3dbb8c9d6dcc)

**Comment by ImranR98** [comment]
That's weird - please open a new issue. For Telegram specifically ypu should be using the direct link config anyways, available on apps.obtainium.imranr.dev.

**Comment by ImranR98** [comment]
Oh, I see. The "Partial APK hash" option is only relevant to the HTML source which is what was being discussed above. So you should be good. Are you seeing the constant version changes still? This issue was about the version constantly changing on every refresh. If you only saw the version change once (from "x.y.z" to a series of random numbers) then that is normal and expected - read above and the wiki for details.

**Comment by Marocco2** [comment]
> > Oh, I see. The "Partial APK hash" option is only relevant to the HTML source which is what was being discussed above. So you should be good. Are you seeing the constant version changes still? This issue was about the version constantly changing on every refresh. If you only saw the version change once (from "x.y.z" to a series of random numbers) then that is normal and expected - read above and the wiki for details.
> 
> I get that it's expected, but Telegram updates constantly even after being marked as updated, despite having no new releases. These updates don't do anything but refresh this pseudo-version number string.

Which is exactly what this issue was for

**Comment by leo-liar** [comment]
I do observe the same as user plusmeup:

Near constant update notifications for Telegram despite there being no new version and only the pseudo version string getting updated.
My config also looks like shown above with no settings entry for switching to partial APK hash.

I had Telegram set up before and got switched to the current setting by the recent Obtainium update. I'm also on the latest version 1.1.36 ...

**Comment by DarkCrypt** [comment]
> Your config doesn't work because it uses the APK link hash - if you switch to "partial APK hash", it will work (this means hashing the first few KB of the APK itself to see if it has changed). That's what the "direct APK link" source does, but it skips the unnecessary step of loading the HTML page first (telegram.org/android).

@ImranR98
Thank you for the explanation. I changed to "Partial APK Hash" and my config was able to update to the new release (v.11.5.4) like you said. I guess I prefer the "HTML" source because it provides more options even though it's not necessary.

**Comment by leo-liar** [comment]
I tried to directly modify the JSON data for Telegram to add the setting for partial APK hashing but this gets immediately removed after the first "update" Obtainium detects for Telegram.

@ImranR98: Do "Direct APK link" apps even support this setting?

**Comment by ImranR98** [comment]
Since APK hashing is unreliable for some people (and I don't see a way to grab the version through the existing HTML source), I've restored the original Telegram App source: https://github.com/ImranR98/Obtainium/releases/tag/v1.1.37
