### ISSUE TITLE
"Pseudo-Versioning Method" Reverts to Default 

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/Obtainium#2027]
When "Partial APK Hash" is selected as the pseudo-versioning method, it sometimes reverts to the default ("APK Link Hash"). This has been observed when changing anything in the app config and saving the changes (I specifically toggled "exempt from background updates").

**Comment by ngrigoriev** [comment]
Not sure if it is related, but after updating to the latest version of Obtanium, I have got problems with multiple apps. It looks like the version detection logic has changed and because of that it started to fall back on the pseudo version. For multiple different apps Obtanium started to show that version "x.y.z" is installed, but version 12332423 is the latest. I have fixed some of the apps by adding the specific version regex to the configuration.

**Comment by ImranR98** [comment]
This has been fixed. @ngrigoriev you''d need to provide more details about your problem in a separate issue.
