### ISSUE TITLE
How to get the version from the APK name?

### ISSUE THREAD

**Issue by ibrahimbayyinah** [ImranR98/Obtainium#2049]
I want to install [Librera Reader](https://github.com/foobnix/LibreraReader/). However, they offer 2 versions at the same time: a Pro version and an F-droid version. The problem is: the version number of the Pro version is always 1 more than the release number, for some reason. A picture might be clearer:
![librera_pro_version](https://github.com/user-attachments/assets/17e7cf52-4dac-4d3b-ab88-2882683288d3)

As you can see, the version number of the Pro version is `8.9.183` while the release has version `8.9.182` in the title.

This causes Obtainium to always think that this app needs to be updated:
![librera_update](https://github.com/user-attachments/assets/ef0f7132-73c7-4832-a0c3-bedd4c5e345b)

Is there a way to tell Obtainium to take the version number from the filename of the APK? If so, what should I change in the configuration for this app?

Thanks in advance!

**Comment by ImranR98** [comment]
No way to do that atm (I believe there is already an open issue for it).

If you don't plan on updating the app from outside of Obtainium, you can turn off the "Reconcile OS version..." toggle in the app-specific settings, the tap the "mark as updated" button - then it should work as intended (it will say the version is 182 instead of 183, but notifications will work properly.
