### ISSUE TITLE
Allow Category Selection for Apps en Masse from the Apps Page

### ISSUE THREAD

**Issue by ImranR98** [ImranR98/Obtainium#205]
Would include a warning if the Apps selected already have different category settings as these would be overriden.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.11-beta

**Comment by S7venLights** [comment]
Noticed a bug with this. 

If you select multiple apps to add to a category,  and one or more are already part of a category. 
The warning shows up that your apps will be removed from existing categories.
I click continue and then the apps are removed but they are also all deselected and not added to the new category selection. 

Expected behaviour: they would be added to the new category even if removed from the old. 

Ideal behaviour: The apps are added to new category while persisting their other category, conforming with the multiple category per app feature.

**Comment by ImranR98** [comment]
Not sure I get what you mean - it doesn't deselect anything for me. Could you send a recording?

**Comment by S7venLights** [comment]
Seems the latest version of Obtainium has fixed the deselect issue. So no worries. 

As for what I said in "Ideal Behaviour":
When selecting apps en mass, you can't assign multiple categories to those apps. Only one which overrides the others.
If it needs to be that way, no stress but ideally you could add multiple.

**Comment by ImranR98** [comment]
You can select more than one category using the multi select. You should be able to confirm this by looking at which categories are ticked in the selection menu (or using the filters). It's just that the colour on each side of the app in the apps list will only show one category (not sure yet how to display all of them).
