### ISSUE TITLE
Version "latest" is problematic

### ISSUE THREAD

**Issue by dominikheinz** [ImranR98/Obtainium#210]
Some apps on GitHub use (unfortunately) not proper version labeling.
For example: https://github.com/crackededed/Xtra

It specifies installed version as latest and remote version also as latest. But I know for a fact that the installed version is older. What is the best way to handle this? Maybe checking the date or something...?

**Comment by ImranR98** [comment]
Nothing can be done about this as the developer themselves have not provided a version number on GitHub. Using release dates instead of release titles would not work as Obtainium needs to be able to compare the actual App version to the external one.

**Comment by dominikheinz** [comment]
That's fair. So the best option is to suggest to the developer to switch to proper versioning numbers?

**Comment by ImranR98** [comment]
Yes that would be the solution for now

**Comment by Sertonix** [comment]
Currently the detection for versions of Etar also doesn't work.
I created an issue there to make the naming consistend.
https://github.com/Etar-Group/Etar-Calendar/issues/1338

**Comment by ImranR98** [comment]
Leaving some notes for later:
1. Add `bool supportsDate` to Source schema.
2. Add `Date? releaseDate` to App schema.
3. For Sources where `supportsDate == true`, a release date should be extracted and saved along with the latest version (modify Sources to support this).
4. Add an toggle to `additionalAppSpecificSourceAgnosticSettingFormItems` to enable using the App release date as the App version (with a prompt explaining it and its limitations).
   - This will need some changes to that array (and the other one, `additionalSourceAppSpecificSettingFormItems`). Instead of containing `List<GeneratedFormItem>`s directly, these arrays should instead contain `List<Map<GeneratedFormItem, List<String>>>`, where the `Map` value is a list of Source properties/attributes that must not be `null` or `false` if the associated `GeneratedFormItem` is to be used.
   - Then modify `combinedAppSpecificSettingFormItems` to support this and return a filtered list of `GeneratedFormItem`s.
   - We can use this on our new `releaseDateAsVersion` toggle; it should only appear if the Source has `supportsDate = true`.
5. When `releaseDateAsVersion == true`, `noVersionDetection` should automatically be enabled too (since version detection won't work when using dates as versions). Figure out the best place this logic should be added.
6. Modify the code to respect this new toggle by replacing the version string with an integer representing the release date (discard original version strings). Again, do this in an appropriate place.
7. In the UI (both Apps List and App Detail), add the Release Date for Apps that support it (along with a sort option) - this is for #298.

**Comment by ImranR98** [comment]
Using release dates instead of versions is now supported (for some Sources): https://github.com/ImranR98/Obtainium/releases/tag/v0.11.0-beta
