### ISSUE TITLE
Obtainium don't install updates

### ISSUE THREAD

**Issue by summoner001** [ImranR98/Obtainium#219]
Hi!

Android version: Android 9
Obtainium version: 0.9.14-beta
New app installation permission: enabled
Storage permission: enabled

Clearing cache and storage don't solve the problem.

When Obtainiun notify me new updates are available for update. I tap to the down button. I don't leave the app when I'm waiting for download. When the download has complete obtainium don't install the update but the version tag changed to the new version number. But the app isn't updated.

Until now, the only time an update would not install for an application was when I left the application

The app: Mindustry Latest Bleeding Edge https://github.com/Anuken/MindustryBuilds/releases

**Comment by ImranR98** [comment]
Most likely the App's `versionCode` has not changed between releases so Obtainium thinks you're trying to install the existing version. Please check if this is the case (if so, the developer would need to change it on their end). Will reopen if this is not the problem.

**Comment by summoner001** [comment]
I checked the app version number in the phone options >> apps >> mindustry menu. The version number has older then the new version. And in the game menu has the older version number. Only the obtainium shows that the app it is updated to the new version.

When after obtainium download the apps the installer don't run. Only obtainium show the new version number.

Or how can I view the correct version number?

**Comment by ImranR98** [comment]
Unfortunately Android only shows the version number, not version code. GrapheneOS does show it so I'll check and let you know. Though it is probably the case.

**Comment by ImranR98** [comment]
Just checked - not a build number issue after all.

**Comment by ImranR98** [comment]
Was looking at the wrong line. It is a version code issue. All versions of Mindustry show up as having a `versionCode` of `1`:
![Screenshot_20230107-163200-01](https://user-images.githubusercontent.com/30463115/211171096-1067a015-2a3d-4683-abf6-8b5852357721.jpeg)

This is something the app developer needs to fix, since the [versionCode](https://developer.android.com/studio/publish/versioning#versioningsettings) is supposed to be different for every version of an app.

That said, a few other apps have had this problem too so it may be a good idea to add a workaround for it in Obtainium.

**Comment by ImranR98** [comment]
Fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.9.15-beta

Thanks for reporting this, found 1 other bug while fixing it too.

**Comment by summoner001** [comment]
Yeah it is working for now. But the installer screen a bit laggy and freezing. After restart my phone the mindustry has updated. I will try to clearing obtainium cache and storage and I'll see if the installer freezing bug is still there.

Thank you for the fast coding!
