### ISSUE TITLE
Unable to add Tutanota repo

### ISSUE THREAD

**Issue by Universal-Igloo** [ImranR98/Obtainium#22]
On trying to add the tutanota repo (https://github.com/tutao/tutanota), the app says "No APK found". 

While Tutanota's model is to do separate releases with the same version number for different device types, so "3.1.1000 (Android)" may be the 3rd release for example, which has an apk file, while "3.1.1000 (Desktop)" may be the top release without an apk.

**Comment by ImranR98** [comment]
That's a weird way to use GitHub releases, usually all platform binaries are under the same release for a given version. I'm not sure how to handle it since from the API point of view the Android version looks older than the newest one (iOS).

One way to do it would be, if there is no APK in the latest release, we could look for other releases which have the same `created_at` date and assume they are also the same version - since it looks like Tutanota's Android and iOS releases always share the same commit (not shown in the API) and the same `created_at` date. 

I'm not sure this approach will always work since there could be a release in the future with different `created_at` dates for Android VS iOS, but for now it's better than nothing. Will add in the next release.

**Comment by Universal-Igloo** [comment]
It's a good idea, but unfortunately your concern is spot on. More often than not in fact, Tutanota releases are on different dates for different devices.

What if you just search recursively all the prev releases until you hit the latest one with an APK? Because that is of course always the latest android release. Is that possible with the API?

**Comment by Universal-Igloo** [comment]
In my perspective, even beyond Tutanota, you will be hard pressed to find perfect congruency in how everyone chooses to use github releases. Thus, covering more scenarios as fallbacks should be useful in the longer run, right?

**Comment by S7venLights** [comment]
I think similar to my issue downloading brave this would require more fine tuned APK selection. Perhaps a toggle for manual APK selection which the user can turn on and off for each repo. 
I imagine it works by notifying us when there is a change to releases and then you browse the releases page via webview and click on the APK you want.

**Comment by ImranR98** [comment]
Added a fallback option in the latest release https://github.com/ImranR98/Obtainium/releases/tag/v0.3.0-beta
Tested with Tutanota.
