### ISSUE TITLE
feature enhancement when doing updates

### ISSUE THREAD

**Issue by droidus** [ImranR98/Obtainium#242]
I have an idea for when doing multiple updates, and Obtanium is one of them.  I will sometimes update several apps at a time (let's say there are 5 selected, for example).  Obtanium may be the 3rd one to get updated.  After updating, I open the app again, and it shows 2 more updates.  Is there a way to make Obtanium to be the last one to update?  Or some kind of flag to say, hey, keep on doing updates, upon app reboot, when there were others that were pending?

**Comment by ImranR98** [comment]
Thought this was fixed already (see #84) as Obtainium is always the first item on the install list (so it should be the lowest update prompt, with other Apps stacking on top). But I guess the timing still breaks this sometimes (since the update prompts themselves are handled by Android). I'll add a tiny delay to try and fix this, but it might still happen depending on the device and Apps being installed.

**Comment by ImranR98** [comment]
Added a delay, hopefully this fixes it: https://github.com/ImranR98/Obtainium/releases/tag/v0.10.6-beta

**Comment by S7venLights** [comment]
Yeah it happens sometimes, when it does, I skip (cancel) updating obtainium and redo it after the other apps
