### ISSUE TITLE
Examples of HTML not working

### ISSUE THREAD

**Issue by zachvlat** [ImranR98/Obtainium#262]
I have 3 examples of html (I know it's kinda hit or miss) that they don't add, and also force close the app because its left out of memory.

`https://d1ahtucjixef4r.cloudfront.net/Exponent-2.26.6.apk` (for the app Expo Go)

`https://pokemmo.com/download_file/9/` or `https://dl.pokemmo.com/download/PokeMMO-Client.apk?r=22215` (two links that both fail)

`https://mega.nz/file/oAEDiCCa#FSzt8VTpewaZu-6Sr-nni2NS5tYKt-wbWvJZuoxUp5g` or `http://58816445.swh.strato-hosting.eu/Download/PokeOneDroid.apk` (also two links that both fail)

What confuses me is that "simple" (i dont know how simple it is) .apk links fail and an other link that I have doesn't (a non apk that I use with no issue, but I can't reveal it here because it contains my ip address).

**Comment by ImranR98** [comment]
The link you use needs to return an HTML page (which is why the source is called 'HTML'). That page is then scanned for links to actual APK files.

The links you posted don't point to HTML pages, they point to the APKs directly. So the app tries to scan an entire APK as an HTML file, which causes the crash.

I don't see why you would add a fixed APK link to Obtainum instead of just downloading through a browser. The point of using this app is to track APKs from sources as they are updated over time, then provide notifications and a convenient UI to install those updates. The HTML source also assumes that the APK links on a page will change over time, and that's when it sends an update notification.

If you provide a fixed link to an APK directly, there is no way to tell that the APK has changed without downloading it first - and that's not practical for update checking.

Also for the HTML source, links must end in `.apk` - indirect links won't be picked up (though that could be added).

**Comment by zachvlat** [comment]
Thank you for the heads up! I got blindsided and forgot basic HTML stuff. I managed to grab the Expo go app from their site (by pasting the web page as you said). For these two games, I "hacked" my way through the JSON file (I exported it) and insert the apk URL and now it works. I have the standard "can't find a suitable release", but it's fine my me! Below is the edits I made to make it work. (this is not a feature request just my way of thinking)
{
        "id": "eu.pokemmo.client",
        "url": "https://pokemmo.com",
        "author": "PokeMMO",
        "name": "PokeMMO",
        "installedVersion": "PokeMMO",
        "latestVersion": "PokeMMO",
        "apkUrls": "[\"https://dl.pokemmo.com/download/PokeMMO-Client.apk\"]",
        "preferredApkIndex": 0,
        "additionalSettings": "{\"trackOnly\":false,\"noVersionDetection\":true,\"apkFilterRegEx\":\"\"}",
        "lastUpdateCheck": 1675765161926381,
        "pinned": false,
        "categories": [
            "Games"
        ]
    },
    {
        "id": "com.PSXTeam.P1",
        "url": "https://pokeonecommunity.com",
        "author": "PokeOne",
        "name": "PokeOne",
        "installedVersion": "PokeOne",
        "latestVersion": "PokeOne",
        "apkUrls": "[\"http://58816445.swh.strato-hosting.eu/Download/PokeOneDroid.apk\"]",
        "preferredApkIndex": 0,
        "additionalSettings": "{\"trackOnly\":false,\"noVersionDetection\":true,\"apkFilterRegEx\":\"\"}",
        "lastUpdateCheck": 1675765162430066,
        "pinned": false,
        "categories": [
            "Games"
        ]
    }
