### ISSUE TITLE
A dark theme icon [Feature Request]

### ISSUE THREAD

**Issue by Toiletmason** [ImranR98/Obtainium#267]
Would be pretty great to have the icon switch based on the theme that you're using.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.7-beta

**Comment by ImranR98** [comment]
Actually there seems to be a problem with that one.

**Comment by ImranR98** [comment]
So when I try to implement this, it seems to work but is unstable. The App icon does not reliably update in the launcher when the theme changes. According to this bug report, it is intentional behaviour and will not be fixed: https://issuetracker.google.com/issues/147521650?pli=1

> Status: Won't Fix (Intended Behavior)
> Response from engineering team:
> Some resource qualifiers like locale/density/version code do not change in day-to-day use and changing icons on those are supported. But we do not recommend changing app icons and labels based on frequently changing parameters and it is not supported at most places in system UI.
> Users create a memory map between apps and their corresponding icons/labels. Changing these frequently is disruptive to the use

Unless I've missed something, this is not doable. Will reopen if anyone has other info.
