### ISSUE TITLE
Feature Request: UI/UX changes to update in fewer clicks

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#27]
I'm sure you have thought about this and perhaps have planned to do this. But I thought I'd share ideas. 

I know the 'Install All' button exists as a 1 click solution but sometimes one wants to see what they are updating first and there are scenarios where you may not want to update all apps at once. 

### Current method v0.3.2 beta: 
When an app has an update, it is marked by the 'update available' tag. 
If you want to update it you click to enter its webview and then click update. (two clicks)

### Idea methods:

1. Have the 'update available' tag be a clickable button that reads 'Update'. This would save a click but still require scrolling through apps. 

2. To expand on that idea, perhaps the notification for updates available could have an update/update all button that begins downloading new updates when clicked and then notifies you when to install.

3. And/or a search/filter to show only apps with updates or better yet (like droidify) a tab that shows only updateable apps which would reduce finding updates to 1 click. You could also the install/update all button on every interface.

PS I know you're looking into unattended updates too. And sorry if it seems like I'm hounding you with requests, I appreciate this app and I only want to help improve it for everyone. Take your time to build it and enjoy (ツ)

**Comment by ImranR98** [comment]
With the [latest release](https://github.com/ImranR98/Obtainium/releases/tag/v0.4.0-beta), your points 1 and 3 have been addressed via the multi-select actions (#23) and more filter options.
For point 2, it would need a way to make the background update checking process do something that would make installs initiate as soon as you re-open the app later. I don't think it's worth the trouble just to save a couple of taps, especially since there are other problems with foreground/background detection and processes anyways (#24, #25).

**Comment by S7venLights** [comment]
Clever implementation with the filters, well done. So for finding only updates and choosing them: 
Click filter
choose 'Non-installed apps'
then select apps you want to update
Click the download button
then confirm selection.
5 clicks.
Could still be reduced to 2 clicks per app, with the Droidify type setup of having an update tab and an update button next to each app. 

But the new layout does loses a 1 click to install all button.
Now it requires hitting select all and then install all.
And I also wonder if that will cause rate limits faster. Since Obtanium will make requests for every repo whether its up to date or not.

**Comment by ImranR98** [comment]
[Latest version](https://github.com/ImranR98/Obtainium/releases/tag/v0.4.1-beta) brings back the install all button, but still with a confirmation click (2 clicks).
Also adds a new button to toggle an "updates only" filter without having to open the filter menu. So updating all apps is now 3 taps instead of 5.

Regarding rate limiting, updating/installing apps does not use any API as the app does not check for new updates at that time, it only applies updates which are already known. The actual checking for new updates happens periodically in the background or when the user pulls down on the list to refresh manually.

**Comment by S7venLights** [comment]
Lovely, have a good week 👍
