### ISSUE TITLE
Wrong Shizuku version shown

### ISSUE THREAD

**Issue by Sertonix** [ImranR98/Obtainium#280]
The latest [Shizuku](https://github.com/RikkaApps/Shizuku) version has the name `13.2.1.r958.5f9516b` (downloaded from f-droid).
That is the version number with some additional inflrmation (don't ask me why).
Obtainium shows that an update is available to `13.2.1`. Which is different but not a new version.
If I am correct the build found on github has the version name `13.2.1.r958.5f9516b`. Maybe the version detection is confused by the letter?

Edit: With [Geometric Weather](https://github.com/WangDaYeeeeee/GeometricWeather) it seems to be the same. Shows `3.103` but should be `3.103_fdroid`

**Comment by ImranR98** [comment]
There was a lot of messing around with version detection before settling on the current approach (see #136).

Because there's no guarantee of consostency between the real and source-based version, detection can sometimes break (as in the case of Shizuku). For those, you can disable version detection in the App-specific options and instead manually mark as updated when/if needed.

For Geometric Weather though, I'm not sure why it doesn't work for you as it should. Is it just that the version being displayed in Obtainium is missing the '_pub'? If so that is expected. Or is the actual version number wrong?

**Comment by Sertonix** [comment]
> For Geometric Weather though, I'm not sure why it doesn't work for you as it should. Is it just that the version being displayed in Obtainium is missing the '_pub'? If so that is expected. Or is the actual version number wrong?

It is just missing the ending so it works as expected. Might be better to strip the ending on both the current version and the update version.

That it doesn't work for all apps is fine for me. Maybe close the issue then.
