### ISSUE TITLE
[Feature request]: Detect apk from zip-file for example threma work

### ISSUE THREAD

**Issue by new-on-github** [ImranR98/Obtainium#295]
Some apps are distributed via a zip-file as bundle of different version (x86 & arm) like threma work:
https://threema.ch/en/work/download

Now obtainium cannot handle the link to the zip-file. It would be nice if this would be possible.

By the way a big thanks for obtainium.

**Comment by ImranR98** [comment]
Figuring out what links lead to APK files must be doable without actually visiting the links or downloading the files. This is because requesting all the links on the page would be impractical, slow, and waste a lot of data - especially since it would need to be done on every update check. This is why the 'HTML' Source only grabs links that end with '.apk' - those are the only ones that obviously lead to APK files.

I don't see a way this would work for zip files in a general way where the zip might contain anything. Instead, you could make an issue for adding Threema as its own source.
