### ISSUE TITLE
MJ PDF repo not working 

### ISSUE THREAD

**Issue by berserkwarwolf** [ImranR98/Obtainium#3]
https://gitlab.com/mudlej_android/mj_pdf_reader

It has a direct link to the APK in the releases section, packages. What is happening?

**Comment by ImranR98** [comment]
The GitLab [releases page](https://gitlab.com/mudlej_android/mj_pdf_reader/-/releases) cannot be scraped using the existing solution used in Obtainium, because the release info is dynamically loaded in with JavaScript. So the only way to currently get this info is through the [tags RSS feed](https://gitlab.com/mudlej_android/mj_pdf_reader/-/tags?format=atom). Unfortunately it looks like this feed doesn't always contain a link to the release APK like I thought it did - it depends on how the app developer does things. Here's the [Aurora Store RSS feed](https://gitlab.com/AuroraOSS/AuroraStore/-/tags?format=atom) for comparison.

For now, nothing can be done until someone finds a way to scrape the releases page itself. I'll add a more informative error message about this later.

**Comment by ImranR98** [comment]
Closing as there does not seem to be any way to enable this.

**Comment by ImranR98** [comment]
Not sure whether they actually scrape the APK file, but looking through their code reminded me that Obtainium now has an option to add a GitLab Access Token to enable search. The same token could be used to get release data via the API instead of the RSS feed (which is what it uses now).

The next update will use the GitLab API for better APK discovery, with the RSS feed as a fallback.

Thanks for bringing up this old issue.

**Comment by ImranR98** [comment]
Users with GitLab API keys can now add this repo: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.16-beta

**Comment by foolishgrunt** [comment]
Apologies for resurrecting this - feel free to tell me if I should start a new discussion. But apparently the developer of MJ PDF no longer hosts apk's directly on GitLab: he links to a download page on archive.org, where the only direct download is a .zip file. So my question is twofold:

1. Can Obtainium unpackage .zip files?
2. If yes, is there any way to point it to navigate through the intermediate archive.org page to the download?
    A. I'm aware that I could add the archive.org page directly as an HTML source, but it looks like that URL changes with every new release.

My intermediate workaround is to download from the Izzyondroid repo, but that's not an ideal solution.

**Comment by BabyOilJohnson** [comment]
Does anyone have issue with adding gitlab repo of mj pdf?
@ImranR98 I'm getting "unauthorized" msg while adding.
