### ISSUE TITLE
Redirect to the app detail page as soon as a new app is successfully added 

### ISSUE THREAD

**Issue by BeautyyuYanli** [ImranR98/Obtainium#313]
When I am adding a new app from GitHub, the button turns into loading and the notification shows that the new app is downloading. After the download finished, the loading animation stopped and it will be redirected to the app detail page.

This is ambiguous because users can't tell apart "detecting the new app from source" and "downloading the new app". My suggestion is to redirect to the app detail page as soon as the app is added, then start the downloading.

**Comment by ImranR98** [comment]
The App isn't actually added until after the download completes because adding an App requires its package ID. So there wouldn't be an App detail page until after the download.

This only applies to sources (like GitHub) where downloading the APK is the only way to get the App's package ID. For others, like F-Droid, we don't have that initial download at all.

**Comment by BeautyyuYanli** [comment]
a downloading progress bar inside the page may be helpful?
