### ISSUE TITLE
Skydroid written in Flutter possible source

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#342]
https://github.com/redsolver/skydroid

Posting this for a few reasons after I looked into it. 

The app is written in flutter and in their Readme they say: Planned Features: are to add auto background updates. Maybe you can glean something from them.

Also I'm trying to understand the advantages of their decentralised app source, from the sounds of it anyone can add apps (which sounds bad for security) but apps can be verified via hashes by other users…

It may be a source Obtanium can pull from if you think it's secure?

**Comment by ImranR98** [comment]
Thanks for making me aware of this, looks very interesting. That said, it looks like SkyDroid itself is not a Source (since it's decentralized), so "supporting SkyDroid as a Source" really just means supporting the system/protocol they use to grab their Apps. I don't think it makes sense because it would be a lot of effort for functionality that the SkyDroid App itself already does (and does better than I could).

Definitely going to keep an eye on how they end up doing background updates though.

**Comment by S7venLights** [comment]
Glad to help 🙌

**Comment by S7venLights** [comment]
Just found this:
https://github.com/Solido/awesome-flutter

**Comment by S7venLights** [comment]
https://pub.flutter-io.cn/packages/app_installer

**Comment by ImranR98** [comment]
> https://pub.flutter-io.cn/packages/app_installer

Pretty sure I've tried this one already.
