### ISSUE TITLE
Allow Github OAUTH to increase rate limit/s

### ISSUE THREAD

**Issue by Joshndroid** [ImranR98/Obtainium#35]
As mentioned in the other issues, GitHub has a rate limit.

It would be cool for those of us with a GitHub account to OAUTH login (as i assume you dont want to handle/parse our GitHub login details) to increase our rate limit.

This obviously isnt going to help the other accounts such as gitlab, etc however from my experience the vast majority of my apps are served through GitHub.

**Comment by ImranR98** [comment]
Added in the latest release ([Personal Access Tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token), not OAuth): https://github.com/ImranR98/Obtainium/releases/tag/v0.5.0-beta

**Comment by Joshndroid** [comment]
Hey @ImranR98 can we get a run down of what permissions check boxes we can use to to get a PAT that is sufficient but not so permissive so as to leave us vulnerable?

**Comment by ImranR98** [comment]
None of them. All the data accessed is public already, the token only increases your rate limit.

**Comment by Joshndroid** [comment]
perfect. thanks

**Comment by S7venLights** [comment]
I've set this up now too, it's great, gave me an idea too,  since a token can allow Obtanium to 'read user' and 'notifications' you could maybe use these permissions to get app lists easier and get notifications of repo releases. When you follow an app on Github, you can set it to only notify you of releases by using the follow buttons drop down menu and  custom settings.
Just a thought for future if you need it. For now it seems to work.

**Comment by S7venLights** [comment]
Yeah it's just an idea for an alternative option if needed. It could for example ensure notifications of updates if there are rate limit or other issues in future.
