### ISSUE TITLE
Error Message Prompt After Trying To Install An APK From GitHub

### ISSUE THREAD

**Issue by MarkCyberSecDev93** [ImranR98/Obtainium#358]
![Screenshot_20230315-212713.png](https://user-images.githubusercontent.com/58934423/225323086-fb4c717f-e1d0-4ddd-9629-e93944e5dca7.png)

**Comment by ImranR98** [comment]
As the error says, there is a package ID conflict. Florisboard has an ID of `dev.patrickgold.florisboard` but Florisboard beta has an ID of `dev.patrickgold.florisboard.beta`. The developer posts both of these to the same releases feed, so Obtainium sees them as one app. But Android treats apps with separate IDs as separate apps, so Obtainium blocks the install when it notices (especially since app IDs don't change and this happening could indicate a security problem).

If you only want Obtainium to grab the non-beta versions, turn off "Include Prereleases" (pencil icon on the bottom right).

If you want to only grab beta/alpha versions, use the regular expression filter option with an appropriate filter like `(alpha|beta)`.
