### ISSUE TITLE
Apps showing as "Not Installed"

### ISSUE THREAD

**Issue by jimbudarz** [ImranR98/Obtainium#362]
Apps installed from F-Droid are showing up as "Not Installed", yet when I try to install them I get an error that it doesn't match the Installed version. 

![Screenshot_20230316-211258](https://user-images.githubusercontent.com/692898/225787527-1022b7ad-cfc2-43a9-a068-18cec3382773.jpg)
![Screenshot_20230316-211252](https://user-images.githubusercontent.com/692898/225787551-99724af5-0e4c-46b7-9c88-2d5b164f5ae9.jpg)

**Comment by ImranR98** [comment]
Most f-droid apps use different app IDs from normal (non f-droid) releases. So Android (and Obtainium) treats them as separate apps. So it is generally not a good idea to mix the two. It's best to pick a source (f-droid or not) and stick to it.

With that said, i'm not sure what's going on with wifianalyzer since it looks like they release the f-droid built apk on github (judging by the release titles). Could you let me know what the app ID is for the installed version?

Might also help to re-add the app (the ID in the screenshot makes me think it was added on a much older version).

**Comment by ImranR98** [comment]
Reopen if issue turns out to not be related to mixing App IDs.
