### ISSUE TITLE
Unexpected error when adding apps

### ISSUE THREAD

**Issue by SirBobLoblaw** [ImranR98/Obtainium#375]
Hello, i've been getting this error while adding apps on a device running Android 7.
![e_1.png](https://user-images.githubusercontent.com/120464754/226539914-961e17b9-5af6-4c39-b0fa-e0a335b38e89.png)

 This has mostly made the app unable to add any app whether it is via URL or by using the built in search.
I found a workaround which is using the import option, unfortunately it only works for a handful of apps only from github. FDroid or third party repos throw this error too.
I'm guessing this has something to do with the operating system because i have not found any issues on another device with Android 10.

I found this while looking for a solution, i don't know if they might be helpful:

https://github.com/flutter/flutter/issues/50699
https://stackoverflow.com/questions/72700742/unhandled-exception-handshakeexception-handshake-error-in-client-os-error-ce
https://flutter-developer.medium.com/flutter-android-7-certificate-verify-failed-with-letsencrypt-ssl-cert-after-sept-30-2021-9cb5f672c090

**Comment by SirBobLoblaw** [comment]
Yes, i am able to download APKs from the browser, i tried with many sources including the ones that don't work with Obtainium. I don't think it's possible to download apps from fdroid third party repos from the browser but i tried with the client and it also worked fine.
Regarding the date and time, i have the phone set up to use automatic time zone, and i can confirm that it is correct (time.is says it's 0.6 seconds behind if that's of any relevance).

**Comment by ImranR98** [comment]
Weird. I'll try an Android 7 emulator when I get the chance. Could you see if switching to another network does anything?

**Comment by ImranR98** [comment]
Not having this issue on Android 7 either on my end.

**Comment by SirBobLoblaw** [comment]
That is weird indeed.
I just tried with 2 different wifi networks and my carrier data with no luck.
Should i close this since it seems to be device specific?

**Comment by NaeemBolchhi** [comment]
Just dropping a link that seemed relevant.

https://stackoverflow.com/questions/69511057/flutter-on-android-7-certificate-verify-failed-with-letsencrypt-ssl-cert-after-s

**Comment by ImranR98** [comment]
I've tried adding a bugfix in the latest release: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.15-beta

No clue if it works as I don't know how to replicate the problem. Please let me know if it helps.

@flufficat this issue seems to be identical to yours and it is older, so you can also reply here (closing the newer issue as duplicate).

**Comment by SirBobLoblaw** [comment]
Everything works perfectly for me.
I tested thoroughly with apps from almost all the sources available and i didn't encounter the issue this time. Thank you!

**Comment by ImranR98** [comment]
@NaeemBolchhi thanks for the link you provided!

**Comment by RWCoding58** [comment]
Hi, I'm getting a similar error with my apps using apkpure.net as a source (Reddit, Sync for Reddit, and Meme Generator) whenever Obtanium tries to fetch updates for them. The strange thing is that it worked fine until today (it was able to fetch updates perfectly before). Please let me know if I should create a new issue instead of commenting here. 
![Screenshot_20240303_102658](https://github.com/ImranR98/Obtainium/assets/87898490/0f2d9fc0-fa5a-4dc1-8edc-c979f62ca680)
