### ISSUE TITLE
Add option to search apps using Github api

### ISSUE THREAD

**Issue by ph00lt0** [ImranR98/Obtainium#40]
As a way to move more to apps discovery I think a great start would be to utilize the option to use API keys of GitHub to search repositories. Ideally these would be filtered based on the results having releases with an APK file. 

This all would remove the requirement to find the url of the app and copy it over etc.

**Comment by ImranR98** [comment]
This is a good idea, but i'm not sure about filtering results to get rid of non-APK releases, because there could be 100s of results and checking each needs one API request so even a user with a token could run out quickly (and it would take a long time). But yeah, allowing the user to search then pick a result can be looked into.

**Comment by S7venLights** [comment]
Is there no official way that Github devs designate what platform their repos target? Like a Tag for android? 
If there is, you could use that as a filter

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.7.0-beta

No way to filter only for android Apps as far as I can see.
For now the results only show App name/author since that was easiest to implement, but I'll add App descriptions and URL links later to make it easier to pick results. Leaving the issue open till then.

**Comment by ImranR98** [comment]
Done: https://github.com/ImranR98/Obtainium/releases/tag/v0.7.1-beta
