### ISSUE TITLE
[Feature request] Remember app architecture selection

### ISSUE THREAD

**Issue by KaKi87** [ImranR98/Obtainium#436]
Hello,

It would be nice of Obtainium to remember the architecture selection of each app after choosing once.

Or even better, detect the currently installed architecture, so that already manually installed apps don't even require an initial choice.

Thanks

**Comment by ImranR98** [comment]
Obtainium already pre-selects the APK you picked previously (as long as the order of APKs remains consistent between releases). You can use the APK name filter to avoid the selection menu entirely.

**Comment by KaKi87** [comment]
It's still not as user-friendly as it could be with my feature.

**Comment by ImranR98** [comment]
As mentioned, there is no guarantee that an app will name it's APKs consistently between releases or that the way archs are specified will be exactly what you expect (for example, `aarch64` is one I've seen even though the OS usually reports `arm64-v8a` or similar. This has been discussed before and is why the APK selection menu tells the user what archs their device supports.

There's a similar problem with versiom detection, where Obtainium sometimes fails to match an app's real version to the version string given by the source, which is why "no version detection" is an option. I'd rather not add a similarly complicated "architecture detection" that would similarly require an off switch for edge cases.

If you know how to match the device arch to a specific APK in a reliable and not error-prone way, it could definitely be added.

**Comment by KaKi87** [comment]
> there is no guarantee that an app will name it's APKs consistently between releases

Just like a manual filter may no longer be a match in the same situation, in which case the app just has to ask the user to reconfigure.

**Comment by ImranR98** [comment]
Yes, a user-defined regex can be manually reconfigured, but automatic detection would have to handle that variability without user config (that would kind of miss the point of automatic detection).

**Comment by KaKi87** [comment]
> automatic detection would have to handle that variability without user config

Or it could just show the modal again.

What I'm suggesting is simple :
1. As long as the option previously selected using the currently implemented modal is available, then continue using that choice.
2. Whenever said option becomes unavailable, show the modal again, getting back to situation n°1.

**Comment by ImranR98** [comment]
> 1. As long as the option previously selected using the currently implemented modal is available, then continue using that choice.

Okay, so your'e suggesting the modal should just be skipped if an option exists which is identical to the previously selected one? That's definitely simpler than the automatic arch detection I thought you meant, but we would also need a way for the user to manually bring the modal up if they change their minds about their selection. Meaning a new setting/button that needs to be put somewhere. Would also need a way to inform the user about how this works / make the feature is discoverable (maybe a "remember this choice" checkbox?); one benefit of a manual regex is that the user explicitly sets it so they know what they're doing.

In general I think that idea would be good and would save the user a click, just wouldn't be a high priority.

**Comment by KaKi87** [comment]
> we would also need a way for the user to manually bring the modal up if they change their minds about their selection. Meaning a new setting/button that needs to be put somewhere

Could be in the same form as the filter setting.

> benefit of a manual regex is that the user explicitly sets it so they know what they're doing

But it requires more effort, thus provides worse UX.
After all, the whole point of this app is to automate updates.

**Comment by ImranR98** [comment]
> Could be in the same form as the filter setting.

Actually we could reuse the existing filter instead of adding a new option. When the selection dialogue comes up there could be a checkbox asking if the user wants to "filter for this apk next time" and if they check it then the existing filter is set to that apk name. This means we can use all the existing logic and avoid adding a new per-app option.

> But it requires more effort, thus provides worse UX.

I'm not sure if the ux would be much better with your suggestion because it would only work for apps where the apk name does not include the version number. For example something like `app-release-armv8a.apk` would probably be fine but `app-release-1.0.0-armv8a.apk` would change per release. I'm concerned that users would pick the "remember this option" checkbox without knowing its limitations.

The more I consider this the more it feels like a simple file name equality check like this would only work for some apps and end up confusing some users as described, while more advanced users would go for the regex filter anyways.

**Comment by KaKi87** [comment]
> For example something like `app-release-armv8a.apk` would probably be fine but `app-release-1.0.0-armv8a.apk` would change per release.

The dialog works fine with Iceraven that I mentioned in #431 while file names do contain version numbers.

**Comment by ImranR98** [comment]
> The dialog works fine with Iceraven that I mentioned in #431 while file names do contain version numbers.

Yes, because the dialog is based on the order of items, not the item content. If you pick the third item on the list, it will automatically pick the third item again next time (even if the APK name has changed). This is good enough as a simple convenient suggestion as it will be right often enough to save the user an additional click most of the time.

But if we want to skip the dialog entirely, that's not good enough because we aren't just making a suggestion - we are actually going ahead and downloading/installing the APK without user input. We would have to actually look at the contents of the APK name and only skip the dialog if we find something that matches what the user had picked previously. In this case "match" would be "identical to" since there's no smarter match method that would always work.

So:
1. This would only work for apps which do not change their APK file names between releases, which is a subset of apps.
2. The user would need to be informed about this limitation when presented with the checkbox. It's not a "smart" feature that detects the file naming pattern, CPU architecture, etc. to make a decision - it's just a dumb equality check.
3. Since this feature would be based on the existing file name filter (not worth adding a whole new field w/ dedicated logic), the user would have to know where to go in order to disable it since they wouldn't be able to "untick the checkbox" they had ticked previously.

I don't think this is worth doing given all the above. The existing APK filter is fine and works very well for those who know to use it. Maybe it could be made more user-friendly by adding a "help" button next to the form input. When clicked, it could pop up an explanation with the following:
1. A link to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions explaining what a regex is
2. A note about APKs sometimes being split by CPU architecture and how this is a common use case for the APK filter
3. A suggested regex that would probably work for the user based on their device's CPU architecture
4. A caveat saying that it may not work and may need to be modified to fit the specific target app

**Comment by ImranR98** [comment]
> Just like a manual filter may no longer be a match in the same situation, in which case the app just has to ask the user to reconfigure.

Reading through the thread again, I might have misunderstood this. There would be nothing for the user to "reconfigure" if automatic detection fails, but it could always just fallback to the manual selection. So maybe smart/auto detection is worth a try.

**Comment by ImranR98** [comment]
Okay, I've added a toggle for a very simple additional filter that looks for an architecture string in the APK name and matches it. The wording indicates that it is not guaranteed to work, and if it fails, the user just gets an APK selection dialog as you suggested. This should work for some apps while being completely inconsequential for cases where it doesn't, without giving the user the wrong expectations: https://github.com/ImranR98/Obtainium/releases/tag/v0.11.26-beta

**Comment by KaKi87** [comment]
> the dialog is based on the order of items, not the item content

The dialog displays a list of architecture, so it must have parsed file names, and successfully doing so, including when receiving updates.

So as long as it does work, it can preserve my previous choice.

I hope I can make you understand that what I'm asking is really simple : in terms of parsing, there's nothing to change in the app.

The only thing I want to change is this :
```
architectures = parseArchitectures()
selectedArchitecture = showDialog(architectures)
download(selectedArchitecture)
```
To this :
```
architectures = parseArchitectures()
selectedArchitecture = showDialog(architectures)
download(selectedArchitecture)
```
Obviously there's no need for that much variables, it's just for pseudo-code clarity.

Thanks

**Comment by ImranR98** [comment]
> The dialog displays a list of architectures, so it must have parsed file names, and successfully doing so, including when receiving updates.

The list of architectures in the dialog is not being extracted from the APK names - those are the archs that the user's CPU supports and the list is reported by the OS. We show the list to the user to help them make the right choice and avoid downloading an APK their OS can't run. I'm also not sure what the point of saving the user's last choice would be since we already know what architectures their CPU supports (if they want to choose an unsupported one, they can deal with regex).

The core of the issue is this: The OS always reports a consistent list of supported architectures that never changes and can be relied on. The App on the other hand is not guaranteed to name it's APKs in a consistent way, use the same arch names as the OS (`arm64-v8a` vs `aarch64` for example), or even provide arch-specific APKs at all. So the issue is finding a way to extract architecture info from the APK names (your `parseArchitectures()`) and match that up with one of the items in the OS-provided list.

With the latest version, this is effectively what Obtainium is doing. If the new toggle is enabled, we take the OS-provided list (the one you see in the dialog message) and we see whether any of the APKs has a matching arch string in the file name. This obviously will fail often (non-standard arch string, non-supported arch, no arch info in filename, etc.) and in such cases, we just fall back to the normal choice dialog. The fact that such failures might be common (since matching only works when the arch strings are identical) is why the checkbox label says "Attempt to ... if possible". 

So I think this accomplishes exactly what you want without even having to remember the user's last choice and it's a reasonable solution for users who don't want to mess with regular expressions and are willing to deal with the limitations.

In the future the matching could be made "smarter" so it doesn't just work with identical strings (for example `app-aarch64.apk` would be able to match the OS-reported `arm64-v8a`) but it has to be conservative as the worst outcome would be to pick the wrong APK. This works for now (including with Iceraven).

**Comment by KaKi87** [comment]
So, if I understand correctly, the dialog is about choosing which architecture to try downloading.

Then, I'd like to suggest removing the dialog altogether, and just attempt one supported architecture after the other. :shrug:

**Comment by ImranR98** [comment]
Bruh. The apk selection dialog is about apk selection. Think about the possibilities: an app developer can include _any number_ of apks for _any number_ of reasons and _name them anything_ - it just so happens that splitting apks by architecture is one common reason to have multiple apks, but it could also be literally anything else - for example I recently saw an app that provided an `app-release.apk` and a `debug.apk`. Sometimes the developer might even have separate apks for fdroid versus google play where one apk contains some extra libraries that the other doesn't.

So given that the apk selection dialog could contain literally anything, I don't see how you could make the choice automatically without asking the user to pick (aside from the very specific case where the recently created architecture matching works). And you can't just attempt one supported architecture after the other because you don't actually know that the apks are definitely split by architecture, and even if you did, you can't tell what architecture and apk is without downloading it and it's not practical to download every apk just to try it.

This issue is closed and I think I've explained why but if you are interested in implementing a better system, feel free to make a PR.

**Comment by KaKi87** [comment]
> I don't see how you could make the choice automatically without asking the user to pick

That's not what I'm asking.

What I'm asking is ask once and rember next time as long as an APK with the same name exists.

If the options are `app-release.apk` and `debug.apk`, and I choose `app-release.apk` for the first time, then it would try downloading `app-release.apk` at the next release if there is one, if not, then it will open the dialog again, if the new choices are `app-release.some-arch.apk`, `app-release.some-other-arch.apk`, `debug.some-arch.apk` and `debug.some-other-arch.apk`, and choose `app-release.some-other-arch.apk` for that time, then it would try to download `app-release.some-other-arch.apk` the following times as well, etc.

Thanks

**Comment by KaKi87** [comment]
Hello ?
