### ISSUE TITLE
Release updates on a schedule

### ISSUE THREAD

**Issue by Kreuger** [ImranR98/Obtainium#445]
I appreciate all of the work going into the app but I dont think you need to put out a new release for every little change you make. I think there have been times where youve put out 2 or 3 updates in a 24 hr period. Maybe once a week or every 2 weeks would be sufficient, aside from a glaring bug. Maybe we could have a stable build and a dev build and do it that way? Just a thought.

**Comment by ImranR98** [comment]
I prefer to have all the latest changes (especially bugfixes) available. I try to hold off making feature releases too often but new features are usually followed by a bunch of bug discoveries (since I don't really test them as much as I should). Things should calm down in the future when prerelease versions will be released often while stable versions won't - but for now it is what it is.
