### ISSUE TITLE
Apps Being Added With No Version Detection

### ISSUE THREAD

**Issue by FWC-9696** [ImranR98/Obtainium#447]
Adding some Apps to Obtainium will add the app without version detection and will also not correctly recognize the currently installed application version if it is updated. Latest Beta 0.11.29.

Edit: I have also noticed that apps originally added with Standard Version Detection have been switched to No Version Detection. In some cases, it is not possible to switch back to another type of version detection (see below)

![Screenshot_20230408-130922_Obtainium.png](https://user-images.githubusercontent.com/76880537/230734370-962bcdf4-2f3b-4b4e-bac8-847735648dd1.png)

**Comment by Sertonix** [comment]
I have the same issue.
I don't know if it is related but I had the prerelease option active for that app.

**Comment by FWC-9696** [comment]
> I have the same issue.
> I don't know if it is related but I had the prerelease option active for that app. 

I don't think so since I first noticed this with F-Droid apps, which I don't think have a prerelease option

**Comment by ImranR98** [comment]
This happens automatically for apps with non-standard versioning formats, where standard version detection wouldn't work anyways (in the past it would just break and you'd have to switch to "no version detection" manually).

**Comment by Sertonix** [comment]
Could you test with this app: https://github.com/d4rken-org/sdmaid-se
It behaves a bit wierd with the version detection.
It changed to no version detection automatically even though it doesn't makes sense.
If I change it to "release date as version", press contine the next time I try to change the version detection I can set it to "standart version detection".
Should I make a new issue gor that?

**Comment by ImranR98** [comment]
It does make sense. The version reported by the OS is `0.6.10-rc0` which can't be matched up with the GitHub-reported `v0.6.10-beta0`.

When you switch to release-date based versioning, the original versions are not stored in Obtainium, they're just replaced with date strings. So the option to go back to standard version detection is enabled because at that point, we no longer know if it should be disabled or not because we no longer have the original versions to compare. But once you do re-enable standard version detection, it will grab the version from GitHub again and just get disabled when it rediscovers that the version strings are not compatible.

**Comment by Sertonix** [comment]
Some kind of notification so that you know version detection got disabled would be nice
