### ISSUE TITLE
Let HTML Source Find Text Links

### ISSUE THREAD

**Issue by muznyo** [ImranR98/Obtainium#454]
Pixelfed is a fediverse [instagram alternative](https://pixelfed.org/_dl/pixelfed-android-v1.0.0.19.apk).

**Comment by ImranR98** [comment]
There doesn't seem to be a simple way to extract the version and APK url from this site as it doesn't work without JavaScript (see also #2, #3).

**Comment by stephen304** [comment]
It's it possible to support the rss feed?

https://pixelfed.org/mobile-apps/pixelfed-for-android/builds.rss

I haven't been able to get obtanium to find any suitable releases using that url, it's hard to debug whether the default or my custom regex is working since obtanium doesn't give any debug feedback.

**Comment by ImranR98** [comment]
The HTML source doesn't work with xml because it looks for an html link element. Rather than adding a separate xml source we could have a toggle that tells the HTML source to search for plain text urls instead of links specifically. This would make it work with xmls as well as any other page with plaintext links (but might be more prone to errors so would be off by default).

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.32-beta
