### ISSUE TITLE
HTML source for Öffi no longer working

### ISSUE THREAD

**Issue by loaidheach** [ImranR98/Obtainium#455]
I added https://oeffi.schildbach.de/download.html as a HTML source when they were first implemented and it worked like a charm. A few days ago (with the release of Öffi 12.1.10) it stopped working complaining that the app could not be found. 
I looked an older version on archive.org and it looks like the only differnce is the changed version numbers in link text and target.

**Comment by ImranR98** [comment]
This is happening because the APK URLs are relative without a leading `/` (`href="downloads/oeffi-12.1.10-aosp.apk"`) so Obtainium uses the current path as the base of the URL (see #287, #286). This results in an APK URL of `https://oeffi.schildbach.de/download.html/downloads/oeffi-12.1.10-aosp.apk`, which is wrong because of the extra `download.html`.

Turns out that in such cases, the last segment of the current URL should actually be ignored: https://www.rfc-editor.org/rfc/rfc3986#section-5.2.3

This will be fixed in the next release.

**Comment by loaidheach** [comment]
Ah, I didn't notice that. Thank you for the quick reply and the quick solution.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.30-beta
