### ISSUE TITLE
Bug: Various install fails

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#46]
On V0.5.4 Using the download all updates button results in many apps downloading simulataneously. They all reach 100%, but none of them actually launch the android install/update dialogue. But the apps are then marked as updated in Obtanium but they haven't actually been updated (checked version numbers). Then there is no easy way to know which apps didn't update to reset them (By marking as not installed again) and try update again. 
This sometimes happens with individual app updates too. And it happens even without leaving Obtanium. 

Perhaps apps should download 1 at a time and only start the next download once the first has installed properly.

**Comment by ImranR98** [comment]
Thanks for discovering this. It has nothing to do with batched downloads followed by successive installs (doing it this way makes it easier to send a notification asking the user to return to foreground, and maximizes available bandwidth).

The problem is that this new APK installer plugin (see #25) apparently can't handle installing more than one thing at a time (which I didn't test before adding it). It also (like the previous plugin) does not let you wait for the install to finish, nor does it tell you if the install passed/failed. This is an issue for both prompted and silent installs - the plugin just crashes. The solution would be to wait for one install to finish before starting the next one, but that doesn't work. Unfortunately it looks like this plugin is just not usable (the dev also seems unresponsive), so I will switch back to the old one which at least allows for batch installs.

This does mean that #25 is not as close to being resolved as I hoped - no possibility of background/silent installs right now as far as I can see.

**Comment by ImranR98** [comment]
Thanks for discovering this. It has nothing to do with batched downloads followed by successive installs (doing it this way makes it easier to send a notification asking the user to return to foreground, and maximizes available bandwidth).

The problem is that this new APK installer plugin (see #25) apparently can't handle installing more than one thing at a time (which I didn't test before adding it). It also (like the previous plugin) does not let you wait for the install to finish, nor does it tell you if the install passed/failed. This is an issue for both prompted and silent installs - the plugin just crashes (adding a small delay helps but still leads to weird behaviour and a crash). The solution would be to wait for one install to finish before starting the next one, but that doesn't work. Unfortunately it looks like this plugin is just not usable (the dev also seems unresponsive), so I will switch back to the old one which at least allows for batch installs.

This does mean that #25 is not as close to being resolved as I hoped - no possibility of background/silent installs right now as far as I can see.

**Comment by ImranR98** [comment]
"Solved" in https://github.com/ImranR98/Obtainium/releases/tag/v0.5.5-beta
