### ISSUE TITLE
Sourceforge app has no version detection, shows version as 'files'

### ISSUE THREAD

**Issue by deadcombo** [ImranR98/Obtainium#471]
Hello,

Obtainium version 0.11.31-beta

https://sourceforge.net/projects/android-ports-for-gnu-emacs

This is the app in question. Version tracking is greyed out. Version is listed as 'files' in the app list. I don't understand if something's gone wrong or if it's the way the repository is structured.

Thank you.

**Comment by ImranR98** [comment]
It's because of the versioning format used by the repo - it's not a "standard format" that Obtainium recognizes, so version detection can't work for it and is automatically disabled.

That said, I found another bug while looking into this. Sourceforge is currently returning the wrong APK URL list - will be fixed in the next release.
