### ISSUE TITLE
Updates on github available although newest versions are installed 

### ISSUE THREAD

**Issue by topcaser** [ImranR98/Obtainium#477]
Hi, for the github apps omweather and solxpect from woheller69, obtainium says, that an update is available. If I click on update, the update available button appears at once again. What can I do?

**Comment by ImranR98** [comment]
For omweather, the developer has tagged the GitHub release as `B0.9` while the actual app version installed with that APK is `1.0`. Obtainium sees this difference and thinks there is an update. Nothing can be done to fix this since it is caused by incorrect information from the developer, but you can work around the problem by disabling version detection for the App. Same for the other one.

For more info on version detection, see https://github.com/ImranR98/Obtainium/issues/404#issuecomment-1492007484.

**That said, I'd recommend that you stop using Obtainium for these Apps because the developer is no longer uploading APKs to GitHub.** For example, omweather's latest version is `V1.5` from last week but Obtainium falls back to `B0.9` from February because it was the last release with an APK.
