### ISSUE TITLE
Fix "Reset Version Detection" button (and make it easier to find)

### ISSUE THREAD

**Issue by NaeemBolchhi** [ImranR98/Obtainium#479]
![Screenshot_20230419-112016_Obtainium](https://user-images.githubusercontent.com/42773187/232974089-73f6d767-18e2-4fe3-bea5-4b82cc313b60.png)

Please add a button here somewhere for reinstalling the latest available version, whether it is considered an "update" or not.

I tried updating the app but missed the install diaogue by mistake. Obtainium thinks I've installed the update and won't recognize that I'm still on the older version. Giving me a button to simply reinstall the latest available apk would be great to resolve this issue.

**Comment by ImranR98** [comment]
> Obtainium thinks I've installed the update and won't recognize that I'm still on the older version.

This is a known issue as noted in the README file (there are already open issues about it):
> - App installs happen asynchronously and the success/failure of an install cannot be determined directly. This results in install statuses and versions sometimes being out of sync with the OS until the next launch or until the problem is manually corrected.

For Apps with version detection, you can fix this by closing and re-opening Obtainium, or even just navigating from the apps page to the app details page.

For Apps with no version detection (like Iceraven), you can use the "Reset Install Status" option which is in the "more" menu on the Apps page (the three dots icon on the bottom right). But it looks like that button is disabled due to a bug which will be fixed in the next release. I'll also add the button to the main App detail page so it is easier to find instead of being hidden in the "more" menu.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.11.33-beta
