### ISSUE TITLE
Add Sourcehut as repo provider

### ISSUE THREAD

**Issue by DePingus** [ImranR98/Obtainium#483]
I was trying to add Cheogram's repo to Obtanium but it can't find any releases on the main page or on the refs page where the releases are listed. 

https://git.singpolyma.net/cheogram-android

**Comment by ImranR98** [comment]
Are there actually apks hosted on this site?

**Comment by ImranR98** [comment]
Doesn't look like it, so we can't add this.

**Comment by ImranR98** [comment]
Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.0-beta

Note that the official SourceHut URL seems to be https://git.sr.ht/ so that is the only one that will be automatically recognized when you type it into the Add App URL input. To use other sites (like your https://git.singpolyma.net/), you can manually select "SourceHut" from the Source Override dropdown that should show up after you input the URL.

**Comment by m-delc** [comment]
> Added: https://github.com/ImranR98/Obtainium/releases/tag/v0.13.0-beta
> 
> Note that the official SourceHut URL seems to be https://git.sr.ht/ so that is the only one that will be automatically recognized when you type it into the Add App URL input. To use other sites (like your https://git.singpolyma.net/), you can manually select "SourceHut" from the Source Override dropdown that should show up after you input the URL.

I an trying to do this exact thing. I would like to add Cheogram to Obtanium. Manually selecting "SourceHut" from the Source Override drop down does not cause the link/source to be found within Obtanium.

**Comment by ImranR98** [comment]
Right, I should have been more clear in that comment. https://git.singpolyma.net/ could contain any number of repos, so you do have to specify the repo as https://git.singpolyma.net/cheogram-android.
