### ISSUE TITLE
App not updated

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#505]
I tried to update but after updated, it still showing as to update.
App link:https://github.com/revanced/revanced-manager ![Screenshot_20230430-121527](https://user-images.githubusercontent.com/101601874/235339692-ad36ebc4-b5d9-4aa7-a23b-aa3a84ff44e4.png)

**Comment by ImranR98** [comment]
One of those rare edge cases where version detection fails and the failure is not automatically detected (see #477). Seems to be new (ReVanced did not have this problem before). Caused by the tag saying `0.1.0` while the actual version says `1.0.0`. Nothing can be done, just turn off version detection.
