### ISSUE TITLE
Fix HTML Link Sorting

### ISSUE THREAD

**Issue by jcperil** [ImranR98/Obtainium#510]
I want to track MuPDF releases. As far as I know, the only official source that hosts apk files is https://mupdf.com/releases/index.html.

The webpage shows that the latest version is v1.22.0. However, when I add the above HTML source in Obtanium, it incorrectly detects that the latest version is v1.15.0.

<img src="https://user-images.githubusercontent.com/89805719/235344969-dc897620-83bc-45bd-9458-2b7e50c0026e.jpg" height="250px" />

Is there a way to fix this? Am I not doing it right?

**Comment by ImranR98** [comment]
The HTML source is very basic. Since there's no way to tell how links on a page might be arranged, how they relate to each other, or how the versioning might work, we just grab the lowest APK link on the page and call it a day. The MuPDF page lists releases latest to oldest, so the lowest (oldest) link ends up being returned.

We can add a toggle to reverse the ordering of links (to select the topmost one).

**Comment by ImranR98** [comment]
Actually, I forgot that the HTML source was already modified to sort the links alphabetically before picking one, so the problem in your case has nothing to do with version numbers. The real issue it that this page has several APKs with differing naming schemes, for example:
- `mupdf-x.y-android.apk`
- `mupdf-x.y-android-mini-<arch>.apk`
- `mupdf-x.y-android-zz-<arch>.apk`
- `mupdf-android-viewer-x.y-universal.apk`
- etc.

This is fine as long as the naming schemes are all identical up to the version number `x.y`. In those cases, sorting the links will ensure that they always go from the lowest version to the highest (with exceptions - see below). Then Obtainium picks the last item on the list - the latest one.

The problem is that fourth naming scheme which says `mupdf-android-viewer-x.y` instead of just `mupdf-x.y`. It always gets sent to the last position because numbers are "higher" than the letter `a` in sorting.

You can fix this using the APK filter. Something like `mupdf-[0-9]` should work.

Even then, there is another bug. The sorting is done one character at a time, so comparing version numbers fails. For example, sorting versions `2`, `9`, and `22` would result in `[2, 22, 9]` because the number `22` is being treated as a list of characters and not a number. This will be fixed in an upcoming release and you should be able to add MuPDF after that (using the APK filter).

**Comment by ImranR98** [comment]
> You can fix this using the APK filter. Something like `mupdf-[0-9]` should work.

Of course the regex would need to more complicated to pick a specific architecture or variant APK.

**Comment by jcperil** [comment]
As I am looking for the `mupdf-1.22.0a-android-viewer.apk`, the following expression seems to be working.

```
mupdf-[0-9]\.[0-9]{2}\.[0-9][a-z]-android-viewer.apk
```

But looking at their release history, MuPDF team seems to change the apk names quite often. Please close this as you see fit.

**Comment by ImranR98** [comment]
Fixed the sorting so your regex should work now: https://github.com/ImranR98/Obtainium/releases/tag/v0.12.2-beta

**Comment by no-usernames-left** [comment]
> As I am looking for the `mupdf-1.22.0a-android-viewer.apk`, the following expression seems to be working.
> 
> ```
> mupdf-[0-9]\.[0-9]{2}\.[0-9][a-z]-android-viewer.apk
> ```
> 
> But looking at their release history, MuPDF team seems to change the apk names quite often. Please close this as you see fit.

MuPDF seems to have broken in Obtainium a few weeks ago, and neither this regex nor the JSON on the crowdsourced app config page is currently working.
