### ISSUE TITLE
Jenkins (Self-hosted) as a source

### ISSUE THREAD

**Issue by BingoKingo** [ImranR98/Obtainium#514]
Some app's nightly version is distributed on Microsoft App Center, could you add it?
e.g. [TigerInTheWall ](https://install.appcenter.ms/users/tigerbeanst/apps/rnshareclean/distribution_groups/tigerinthewall_test_build)

And Jenkins (self-hosted)?
e.g. [NeoChat](https://binary-factory.kde.org/view/Android/job/NeoChat_Release_android-arm64/)

**Comment by ImranR98** [comment]
To add any source, we need to be able to get an APK download URL and a version number (or some version analogue), for at least the latest version (some Sources have fallback).

This can definitely by done for Jenkins as they have an API (just append `/lastSuccessfulBuild/api/json` to the job URL). The build number can be used as a "version" and you could even fallback to previous builds.

For MS App Center though, the API looks like it needs authentication and I haven't looked into what kinds of details you can get out of it. Web scraping won't work as the site needs JS.

So I'm changing this issue to be Jenkins only; this should be split into 2 issues anyways. You can create another issue for MS App Center but it would be a low priority as it would need some extra work since there are currently no sources that require an API key (only GitHub where it is optional).

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.12.2-beta
