### ISSUE TITLE
F-Droid Search

### ISSUE THREAD

**Issue by martin-braun** [ImranR98/Obtainium#526]
I would really love to see this coming, because no F-Droid client offers to copy the F-Droid Repo URL properly, so searching needs to be done via website. It would be preferable to have F-Droid results included in the result set.

Thanks in advance.

**Comment by ImranR98** [comment]
There is no search API available for F-Droid: https://f-droid.org/docs/All_our_APIs/

They do have a single JSON file with a list of all available apps, but it's 34MB so it wouldn't be a good idea to download it automatically. I guess it could be opt-in but that would need new UI to distinguish between this and other search methods, and wouldn't be a good experience at all.

But it looks like F-Droid's own search page is easy to scrape (example https://search.f-droid.org/?q=markor) so that could be used instead. Just note that this search method might break or be removed in the future as web scraping is unreliable.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.12.3-beta

**Comment by martin-braun** [comment]
Thanks a lot. That's what I thought to be honest. Sure it is unreliable, but if it doesn't get changed regularly, it should be good. I got a feeling this won't happen anytime soon given the fact their client is ancient as well. ;)

**Comment by martin-braun** [comment]
@ImranR98 We got an answer by Sylvia from the F-Droid team: 

> Not really officially documented I believe, but https://search.f-droid.org/api/search_apps?q=<your_query> works (found it while looking through the code of [F-Droid / Website Search · GitLab](https://gitlab.com/fdroid/fdroid-website-search), which powers the search).
> 
> There are some other APIs available on [All our APIs | F-Droid - Free and Open Source Android App Repository 1](https://f-droid.org/docs/All_our_APIs/).
> 
> [@uniqx](https://forum.f-droid.org/u/uniqx) Is it worth to consider documenting this search URL?

It works very well, here I searched for the `Coffee` app: https://search.f-droid.org/api/search_apps?q=coffee

Could you please re-open this issue? It would be great to build this API into Obtainium. :)
