### ISSUE TITLE
When updating an app word "Progress" moves to the left and to the right according to progress %number width.

### ISSUE THREAD

**Issue by hariskar** [ImranR98/Obtainium#540]
It is a minor annoyance in an otherwise great program!

**Comment by ImranR98** [comment]
Yeah, I guess "Progress" doesn't need to be there - the % is enough.

**Comment by hariskar** [comment]
No progress should be there in my opinion but should move somewhat to the left so it does not move.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.1-beta

**Comment by NaeemBolchhi** [comment]
![Screenshot_20230527-205139_Obtainium](https://github.com/ImranR98/Obtainium/assets/42773187/6f4be6e2-fe5c-401b-8211-0d23087b31f2)

This looks very out of place. Everything being right aligned looked good and better than this, even with the movement. Instead of the percent moving, now the percentage character moves.

I think returning to the right aligned setting would be good. And to make the movements stop, see if you can use a monospace font for the numbers.
