### ISSUE TITLE
About APKPure

### ISSUE THREAD

**Issue by BabyOilJohnson** [ImranR98/Obtainium#555]
Is it good to add as a source, because of its security background. I'm just saying and don't hatred me.

**Comment by ImranR98** [comment]
Is there any specific security issue you're referring to or just the fact that it's a third party source? Either way it's good to be concerned about security, thanks for bringing it up.

That said unless there's a specific security issue/scandal with this source, i think it's okay to keep because the main point of obtainium is to automate things that users would otherwise have to do manually. It's still up to the user to decide whether they want to trust any particular source.
