### ISSUE TITLE
Enhancment: Repo 'Profile' pictures

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#57]
Idea for future once all the important stuff is stable. No rush [Perhaps someone else can contribute]
Loading and cauching the repo Icon for each app.
Can be a circle to the left of the title and would just help identify apps easily.

**Comment by ImranR98** [comment]
This was actually something I was going to add initially, but it's hard to reliably extract an image from the sources. Like some repos have an icon in their README, but others have a banner graphic, and others have nothing.

It would be better and more reliable to extract App icons directly from the Apps after they are installed, but that would require using actual App IDs (like `com.example.app`) instead of the current generated IDs. This would be done as part of #14, so if/when that issue is resolved, this one should be simple to do.

But yeah right now the most important thing is finding a good plugin for #25 🥺

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/issues/14#issuecomment-1279898918

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.6.0-beta
