### ISSUE TITLE
Bug bug reading version

### ISSUE THREAD

**Issue by xunil89** [ImranR98/Obtainium#601]
some apps have a bug on reading the installed version, I attach screenshots

**Comment by xunil89** [comment]
![IMG_20230602_072544_970](https://github.com/ImranR98/Obtainium/assets/14961235/ec093615-abdf-4ee5-8772-bd5b55f0331d)
![IMG_20230602_072544_872](https://github.com/ImranR98/Obtainium/assets/14961235/60912cff-7335-4779-ae93-cd0b73b83696)

**Comment by ImranR98** [comment]
Can't reproduce this on my end. Do you have any APK or release title filter? Also could you try removing and re-adding the app?

**Comment by ImranR98** [comment]
Actually I see the issue. For some reason, you have disabled version detection for this App. Either that, or it was disabled automatically due to a versioning issue that is no longer there - this could happen if you were previously on a beta release of Simplex. You should either turn version detection back on, or manually mark the app as updated (tick icon on the bottom left).
