### ISSUE TITLE
Issue with recognizing Molly-FOSS

### ISSUE THREAD

**Issue by Ftreghst** [ImranR98/Obtainium#613]
The app does not recognize the FOSS variant of [Molly](https://github.com/mollyim/mollyim-android)  as the latest version. While it does correctly show v.6.20.5-1-FOSS as installed, it only shows v.6.20.5-1 (non-FOSS) as the latest version and offers to update. This happens if you installed Molly-FOSS prior to adding it to Obtainium. If you instead try to use Obtainium to download Molly-FOSS, it allows you to select the FOSS version, but is unable to install it. 

Obtainium also seems to default to "No version detection" with Molly, despite "Standard version detection" being selected (after the first install, standard version detection is not selectable). P.S. Thank you for all your hard work on this app, it's excellent.

**Comment by ImranR98** [comment]
When version detection is enabled, Obtainium tries to grab the real version string provided by the App itself. It then compares this to the latest version string from GitHub to decide whether or not there is an update (Note: the GitHub version string is the release tag). The advantage of version detection is that you can install/uninstall/update apps from outside of Obtainium, and those changes will automatically get picked up when you open Obtainium later.

The main limitation of version detection is that it only works with Apps that use common versioning formats like `1.20.3` or `2023.04` or `2.4-beta2`, etc. When Obtainium sees that it cannot find a "standard format" that is common between the currently installed app and GitHub, it disables version detection for that App. This happens with Molly because of the `-1-FOSS` part of the version string (not standard).

When version detection is disabled, Obtainium ignores the version reported by the OS (except when the app is first added). It just relies on the string provided by GitHub. Sometimes this results in incorrect info, such as when an App has been updated outside of Obtainium. In your case, the problem is that the App was already installed when added, and the installed version had the "FOSS" suffix, while the version reported from GitHub did not.

This is why apps with no version detection have a button to manually "Mark as Updated", which will replace the installed version with the latest one. This should be enough to solve your problem as long as you only use Obtainium to update the app going forward.

> If you instead try to use Obtainium to download Molly-FOSS, it allows you to select the FOSS version, but is unable to install it.

Not sure what you mean by "unable to install" - I was able to pick the FOSS APK and install it on my phone. I'm guessing your existing install is from F-Droid?
