### ISSUE TITLE
Use regex to detect version in download URL

### ISSUE THREAD

**Issue by ncaat** [ImranR98/Obtainium#628]
Some HTML sources such as <https://retroarch.com/?page=platforms> only provide the version as part of the download URL and not in the filename. I suggest adding the additional option to specify a search and replace regex that matches the version in the URL and outputs the correct version. The version detection should fall back on the default if the output is empty. POC:
```sh
$ echo https://buildbot.libretro.com/stable/1.15.0/android/RetroArch_aarch64.apk | perl -pe 's/.+\/(\d+(\.\d+)*)\/.+/\1_GIT/'
1.15.0_GIT
```
I believe that this feature would allow version detection to work on a lot more HTML sources and possibly also on apps that have weird versioning from other sources, so I suggest adding it to all sources.

**Comment by ImranR98** [comment]
The HTML source now uses the entire link (specifically a hash of it) as a "version" instead of just the APK filename. The APK filter also now applies to the whole link instead of the file name. Of course version detection is still disabled for this source (as it was before) since the hashed link is a pseudo-version used for update tracking, not the actual app version.

https://github.com/ImranR98/Obtainium/releases/tag/v0.13.12-beta
