### ISSUE TITLE
Failure to Detect Update If Only Version Code Changed

### ISSUE THREAD

**Issue by E0697** [ImranR98/Obtainium#658]
This is happening in a 3rd party f-droid repo: [DivestOS Official](https://divestos.org/apks/official/fdroid/repo?fingerprint=E4BE8D6ABFA4D9D4FEEF03CDDA7FF62A73FD64B75566F6DD4E5E577550BE8467)
The app is: us.spotco.malwarescanner

For the last couple of updates, only the version code changed, and Obtainium doesn't detect the updates properly.

**Comment by ImranR98** [comment]
For most Apps, APKs with the same version number but different version codes are usually differ in things like CPU architecture, proprietary libraries, etc. For update checking, we care about new version numbers (indicating a newer version of the app with new changes) as opposed to higher version codes (indicating a different APK variant but not necessarily a newer "version"). So it makes sense to give the user a choice here instead of automatically picking the highest version code APK.

Just wanted to clarify that. The next version will have a new toggle to "Pick highest version code APK" for F-Droid Third Party Repo Apps, but this would be false by default and can be enabled for specific Apps where needed.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.15-beta

**Comment by E0697** [comment]
That's great! Thanks a lot.
