### ISSUE TITLE
Source-Specific Search Options 

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#688]
there should also be a 'only display results supporting v8a architechture' or 'only display results with a .apk', or 'only display results above 100 github stars', etc..

**Comment by ImranR98** [comment]
This is not feasible for a lot of apps since icons are not easy to find in the source (which is not even directly available for many sources). Each icon would also need to be downloaded which would make searching take more time and data. Same goes for the architecture and APK filters (which is part of why even the automatic architecture filtering when adding apps is optional with a manual fallback).

The "above X stars" thing is doable.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.13.19-beta
