### ISSUE TITLE
Add a discover tab with latest apps from Fdroid and Izzyondroid

### ISSUE THREAD

**Issue by S-Sajith** [ImranR98/Obtainium#702]
I have migrated from the other fdroid clients , but one thing I miss from the other clients is the ability to discover newly added apps to fdroid and izzyondroid , maybe add a tab in the bottom nav bar named discover which lists newly added apps in the fdroid and izzyondroid ( maybe display an RSS feed of fdroid and izzyondroid apps ? )

**Comment by ImranR98** [comment]
I'd rather not encourage f-droid as a source since so many people have issues later when they try mixing updates between f droid apks and apks from other sources. For a more general recommendations list, see #68

**Comment by candroid-man** [comment]
I have a different idea.

You could basically search or browse for apps you want, and when you go to install it, it will go to the source instead of downloading the app from the repo. It would essentially be Droid-ify or Neo Store, but instead of downloading apps from the F-Droid repo, it would go further and try to get the source .apk from GitHub or wherever else automatically. So you get the benefits of having an app store, while also getting everything from the original source.
