### ISSUE TITLE
Http 520 Error on AuroraOSS Page

### ISSUE THREAD

**Issue by GitGitro** [ImranR98/Obtainium#709]
Hi, Aurora Store moved their site to auroraoss.com and when i try to add the source as html it throws `error:` and nothing more.
I've managed somehow to get the response code and it's 520, so something with how the app sends the request (maybe?). 
I was thinking to add a new source for aurora for this two urls: `https://auroraoss.com/AuroraStore/Stable/` and `https://auroraoss.com/AuroraStore/Nightly/` but I'm not capable with flutter, so could you look into that please? Thank you

**Comment by ImranR98** [comment]
Adding this page as a source won't really make a difference. It's a very simple HTML page that would be perfectly handled by the existing HTML source if not for the 520 error.

From what I can find online, a 520 error looks like it's being caused by Cloudflare. I tried messing with request headers but can't find a way to fix it yet. Looks like they're probably trying to prevent web scraping (and given that it's Cloudflare idk if finding a workaround is realistic.

**Comment by ImranR98** [comment]
Going forward http errors will show up instead of just an empty string - found that bug.

**Comment by ImranR98** [comment]
If it works in Postman that's a good sign - might help to look at the headers and try replicating it.

**Comment by ImranR98** [comment]
Hmm, using those headers doesn't seem to make a difference.

**Comment by 0slav** [comment]
I've given it a go and for me the problem seems to be user-agent.
`curl 'https://auroraoss.com/AuroraStore/Stable/'` fails
`curl -A 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:115.0) Gecko/20100101 Firefox/115.0' 'https://auroraoss.com/AuroraStore/Stable/'` works
Any user-agent except blacklisted ones like curl seems to work.

**Comment by D3SOX** [comment]
Why not add a field for a custom user agent in the HTTP source?

**Comment by abuchachos** [comment]
Hello, 

Oddly enough, I ran into the exact same issue as the original poster, looking for the exact same package. I just wanted to update this issue to add that whichever user agent string is being used currently, is again returning an error from Cloudflare's anti-bot/captcha feature.

I agree with @D3SOX, that if it is not too much trouble, it would be a GREAT feature to allow for custom headers or custom user agent when adding an HTML source. Not only would this solve this problem permanently, but also other potential problems with automated access to HTML sources.

Thanks for the great work, and great app!  

![Screenshot_20231126-234246](https://github.com/ImranR98/Obtainium/assets/45379148/f5e27441-bacd-4821-8f5f-85b4e9273c60)
![IMG_20231126_234433_907](https://github.com/ImranR98/Obtainium/assets/45379148/3e46d375-29ae-4563-9279-0fd53ddc78a2)

**Comment by ImranR98** [comment]
Minor update: The next release will include the ability to specify request headers, but that doesn't fix this issue (no clue why - there might be something going on with cookies?)

**Comment by KaKi87** [comment]
I made the request at Aurora to remove CloudFlare.

Having you the Obtainium maintainers & contributors struggle handling their server is unacceaptable, especially among open source projects.

**Comment by DarkCrypt** [comment]
The CloudFlare issue at AuroraOSS is fixed. See Aayush's response in GitLab issue [1052](https://gitlab.com/AuroraOSS/AuroraStore/-/issues/1052#note_1778388859).
