### ISSUE TITLE
Sync

### ISSUE THREAD

**Issue by Neucher** [ImranR98/Obtainium#716]
Any chance to get Sync ? Maybe via WebDAV

**Comment by ImranR98** [comment]
A webdav based solution (or similar) is unlikely as it would require data to be stored/loaded in a completely different way compared to how it is now (along with having to resolve conflicts etc).

Instead a better "sync" solution would be something like that proposed in issue #600, where an export file is continuously updated in a user-accessible location, and this file can then be synced by some other means (like Syncthing or NextCloud). This is not actual synchronization, since external changes to that file would not be picked up by Obtainium.

Another approach (which I'm thinking might be best) would be for Obtainium to place it's data in the `/Android/media` folder instead of `/Android/data` - that folder is accessible to other apps that have permission to manage storage. Then you could have true sync. It might even remove the need for an import/export function if the user can pick where to store their files.
