### ISSUE TITLE
Adding an html link which redirects to the latest version of an app freezes obtainium 

### ISSUE THREAD

**Issue by ThatMazes** [ImranR98/Obtainium#729]
Ive been trying to add a couple of links which are always the same but are redirecting towards the latest version of an app (sort of like a dynamic link). Every time I try doing that, obtainium loads for a few seconds, then proceeds to completely freeze.

**Comment by ImranR98** [comment]
You need to add a link to a webpage that contains a link to the APK. Every time the link changes, you get an update notification.

You can't add a fixed APK direct link because if the link never changes, how would Obtainium know when it has been updated? You can't redownload the whole APK every time for update checking (impractical).

The reason the app freezes is because it's trying to parse the link as an HTML page when it's actually a whole APK file.

**Comment by 1xFF** [comment]
Would it be feasible to use the file name for version detection? From what I understand its a link like
`https://website.com/app/download` and not
`https://website.com/app/app-release.apk`

The reason I ask is I was looking into #750 and the second source request does exactly this (https://drone-hacks.com/download)
These sorts of sources are so obscure that it isn't really practical to individually add support, but an agnostic source like HTML that deals with these may be useful

If need be I can add this to a new issue.
