### ISSUE TITLE
broken apps saying update is required

### ISSUE THREAD

**Issue by RustoMCSpit** [ImranR98/Obtainium#740]
https://codeberg.org/Bazsalanszky/Infinity-For-Lemmy
https://github.com/godotengine/godot/releases

**Comment by ImranR98** [comment]
The first one is a case of developer error. They've tagged the release as 0.0.7 while the actual APK provided gives its version as 0.0.6. You can either ask the dev to fix this or turn off standard version detection for this app.

The second case is more complicated. They've released an older version 13hrs ago while the latest version is 2 weeks old. Obtainium just grabs the newest one because the GitHub releases API doesn't tell you what the developer marked as "latest" (doing so would require another API call and that was decided against - see #534). When ProtonMail had this issue, it was "fixed" by manually comparing the versions and picking the highest one. But this can only be done with apps that follow a standard, predictable tagging scheme which this one does not. Not sure how to fix this to be honest. The only solution I can think of involves making a second API request which is unacceptable especially for GitHub. Might just have to wait for the next release of Godot when the issue should fix itself.

**Comment by ImranR98** [comment]
There is now a toggle to work around the issue on a per-app basis (meaning we avoid doubling the number of API calls for all apps). Hadn't thought of that earlier. https://github.com/ImranR98/Obtainium/releases/tag/v0.14.0-betaa

**Comment by RustoMCSpit** [comment]
> There is now a toggle to work around the issue (for the second app mentioned above) on a per-app basis (meaning we avoid doubling the number of API calls for all apps). Hadn't thought of that earlier. https://github.com/ImranR98/Obtainium/releases/tag/v0.14.0-betaa

make it automatic to apps that are trying to fall back, after detecring jt the app sgould change color or somethjng isk

**Comment by ImranR98** [comment]
I don't see how it could be done automatically.
