### ISSUE TITLE
obtainium update available

### ISSUE THREAD

**Issue by privacyonly** [ImranR98/Obtainium#76]
![Screenshot_20221030_115207](https://user-images.githubusercontent.com/72265774/198863153-0eff2da7-3d5d-48b9-ac6b-a6ce3aec457d.jpg)

obtianium 0.6.2

**Comment by privacyonly** [comment]
not sure what happened, but the update is gone now.

I just see that error a lot.

close maybe?

**Comment by ImranR98** [comment]
Could you go into the Obtainium app settings and see if the version is actually 0.6.2?
After that could you try deleting the file in `/Android/data/dev.imranr.obtainium/files/dev.imranr.obtainium-v0.6.2-beta-0.apk` if it exists, then trying again?

**Comment by privacyonly** [comment]
yes 0.6.2, when I update using github apk, not obtainium, and then using mobile data and tried to update it from obtainium, that message came out, I didn't do anything, connect wifi, update again, it is all normal.

can't try what you suggested because error is gone.

**Comment by ImranR98** [comment]
Just found what causes this (ran into it myself). There was a half-downloaded APK already stored (something must have interrupted the download), so the next time you try to install that App, Obtainium sees the existing (broken) APK and tries to install it, causing the error. This happens because existing APKs are always used if possible to avoid having to re-download things). The way to fix this would be to automatically delete the existing APK if it fails to install, but that would require being able to catch install errors, which the current installer plugin doesn't let us do.

There's no workaround for now aside from just forcing Apps to be re-downloaded even if the APK already exists. Unfortunately this means new APKs have to be re-downloaded every time, but that's not too bad since it's only useful if you uninstall and re-install an App, which is a lot less common than downloads getting interrupted due to bad connections, etc.

Will do this in the next version. This issue will be closed since it is technically resolved, even though it is a workaround. Definitely something to keep in mind if a better installer plugin is found.
