### ISSUE TITLE
apkpure error 

### ISSUE THREAD

**Issue by Spp595** [ImranR98/Obtainium#762]
ClientException with SocketException: Failed host lookup: 'd.m.apkpure.com' (OS Error: No address associated with hostname, errno = 7), uri=https://d.m.apkpure.com/b/APK/com.supercell.clashofclans?version=latest: [com.supercell.clashofclans]

**Comment by 1xFF** [comment]
Thats because "d.m" isn't a proper subdomain, if you click on the link you get the same error in your browser.

It looks like you tried copying the APK download link but also got the mobile subdomain added somehow.
Apkpure source goes off of the main page of the app, not the download link so the url would look like this:

https://apkpure.com/clash-of-clans-android/com.supercell.clashofclans

**Comment by Spp595** [comment]
> Thats because "d.m" isn't a proper subdomain, if you click on the link you get the same error in your browser.
> 
> It looks like you tried copying the APK download link but also got the mobile subdomain added somehow. Apkpure source goes off of the main page of the app, not the download link so the url would look like this:
> 
> https://apkpure.com/clash-of-clans-android/com.supercell.clashofclans

Strange, I had a regular link copied from my pc

**Comment by 1xFF** [comment]
Yeah that's really odd, I have no clue how they could get combined like that.
