### ISSUE TITLE
[Feature request] Support multiple sources

### ISSUE THREAD

**Issue by h1toru** [ImranR98/Obtainium#780]
Allow multiple sources for a single app and an option to choose which sources to download the app. This feature will be helpful because some app(s) have a different version on a different sources.

**Comment by ImranR98** [comment]
This isn't feasible because there is no way to compare "versions" across sources because Obtainium isn't grabbing versions, it's grabbing GitHub tags, release dates, file names, etc. - anything that is unique pre-release and can act as a stand-in for actual versions. Also, different sources may have APKs signed with different keys (like F-Droid) which will cause a lot of update issues. On top of that, some extra options are only available with specific sources and may not carry over to other ones (what happens if someone adds a github app with prereleases included then adds f-droid as a second source).
