### ISSUE TITLE
Bad version comparing, newer version is announced, when it is older than current one

### ISSUE THREAD

**Issue by ceskyDJ** [ImranR98/Obtainium#808]
Hi, thanks for doing really great job! The app grows very quickly and I think it's very close to stable release.

I found a weird behavior about version comparison. When I have installed VLC v3.5.4, Obtainium thinks it's older version than Latest (3.5.3 from the source Obtainium uses). So, Obtainium constantly gives notification about possible update of VLC to 3.5.3, which is older version than I have (3.5.4). Could you look at it, please?

Screenshots:
![Screenshot_20230823_103200](https://github.com/ImranR98/Obtainium/assets/48548230/25003ac5-4522-4684-a133-2065cd4aa949)
![Screenshot_20230826_155356_Habits](https://github.com/ImranR98/Obtainium/assets/48548230/1da8cc32-19d9-4f7e-9eb9-68f3f9476757)

**Comment by ImranR98** [comment]
See #801. The VLC site is very unreliable and will be removed as a source in the next release.

**Comment by ceskyDJ** [comment]
This is a more general problem, see:
![Screenshot_20230826_174144](https://github.com/ImranR98/Obtainium/assets/48548230/4517528c-2e2b-4595-8c6c-8947b565a675)

**Comment by ImranR98** [comment]
No, the VLC issue is due to their website being inconsistent and randomly switching between the last couple of versions. The Etar issue is completely different - the latest version with APKs available is 1.0. You have "fallback to older releases" enabled so when no APKs are found on more recent releases, it falls back to 1.0. See #279, #764.

**Comment by ceskyDJ** [comment]
Oh, I'm sorry, I probably formed it badly from the beginning. My problem is that Obtainium offers update to **older** version than I have already installed. So, it's absolutely correct to show "Latest Version:" as "v1.0" (or maybe it should be "Latest available version" or "Available version", but it's not as a big problem), but it should not offer to update to that version "Update" button below. VLC has similar problem - I have installed version 3.5.4, Obtainium found 3.5.3 as the newest, so it shouldn't offer an update. It's that simple. Are you understand now or you need to even better describe it?

**Comment by ceskyDJ** [comment]
When this will be solved, I think VLC's version magic won't be a problem any more. Obtainium will offer update only, when VLC links a newer version, so there will be no update spam or something similar.

**Comment by ImranR98** [comment]
Obtainium only looks at whether or not the versions are equal to determine if there is an update, it does not compare numbers to see which is higher.

This is because a "version" can be any unique per-release identifier, not just actual numbers. For some apps, the source might not provide version numbers at all. I've seen apps use commit hashes as github tags, for example.

**Comment by ceskyDJ** [comment]
I know it's not easy to compare two versions and determine which is older. You work with release dates and other time information, don't you? I thought it could be used for non-standard versions. Otherwise, for "standard" versions like X.Y.Z... is pretty good comparable, because it should be built on the system, that newer version gives a bigger number, when you do weighted sum over items. Of course, there are different versioning schemes, too. Another often used one is YYYYMMDD.X, which is well comparable, too. But yeah, you can't do general comparison at all. I think there is some kind of release date, that could be used for unsupported version forms. I don't have any statistics, how it really is (maybe you have, in this case it would be great to share, I'm very excited to see that data), so these are just some thoughts from not very experienced user in this area.

**Comment by ceskyDJ** [comment]
The major problem I see here is that when Obtainium will be completely automatically update tracked apps, this could cause problems. When some 3rd parties (e.g. Google Play) will update app to newer version than Obtainium has available, it downgrades the app back to the older version. It's not a theoretical thing, I use Obtainium just for a little time and something like this (but fortunately without automatic updating) happened). I'd love to have Obtainium with fully automatic updates (it'd save my time needed for manual activating updates), but it could (in current state) cause problems, so I try to warn before it will be a real problem. Another good thing of solving this issue will be at least getting better situation with VLC and those "problematic" apps.

I think Obtainium is really good app and I'm a lot happier now than before I started to use it, so I just try to help (although not directly) with its development, so it could be even better and work as a great daily driver for so many users. So, don't understand this as a kind of attack, but just as a stream of thinks that maybe could help you improve Obtainium, please.

**Comment by ImranR98** [comment]
Sure, I definitely appreciate the input 🙂

Just not sure it's worth the added complexity. It would only work for apps with "standard" versions, leading to inconsistent behaviour. It would also cause problems for users who do want to downgrade (see #107). It would also mislead users into thinking that Obtainium is tracking the latest version from the source, when in reality their app is being updated in some other way like google play. I think the solution to your issue is to avoid tracking an app in Obtainium if it is already being managed by google play. Besides, Obtainium cannot silently/background update an app if it was last installed/updated by another app like Play (this is an Android rule for security reasons).

**Comment by ceskyDJ** [comment]
It sounds fair. So, we'll know, how it will be working for a longer time period and more users :).
