### ISSUE TITLE
Disclaimer Idea, If Git Repos stop releases

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#83]
Many apps have Git repos that they used to release on, but have stopped. 
Some repos may now release on Git now, but stop later in favour of F-droid only or their own Repo. 

This will result in people not getting updates without knowing. 

A disclaimer warning of this in app would be good something like: 

Repos may without warning decide to only release on F-droid. Therefore it is advisable to keep an F-droid client as a fallback.
_________________________________ 

Alternatively, you could build in a way for Obtainium to compare versions on f-droid to Gits and prefer the newest APK. 

I imagine this could be implemented in the 'Add App' menu. 
You could have the input line for the app link and an optional 2nd line called 'Fallback link' 
With the explanation: Incase primary link stops releasing (F-droid suggested). 

People would put in a github link in line 1 and F-droid in line 2.
_________________________________ 

If you didn't want that method, maybe you could have a way for Obtanium to pull F-droid links from Git Repos and automatically do that fallback work without the users input. But then there should be an option for people who don't want that, to turn it off.

**Comment by ImranR98** [comment]
- Generally not a good idea to mix F-Droid APKs with those from other sources since they may be incompatible (in general, I don't especially want to recommend or use F-Droid as a fallback).
- The App version that Obtainium extracts from App Sources are not real package versions, but just strings that usually contain the version (for example, Mullvad version 2022.2 shows up as `android/2022.2` on GitHub). Sometimes this doesn't contain the version at all (see https://github.com/recloudstream/cloudstream/releases) but it's a good enough alternative.
    - During update checking, if the version string extracted is in any way different from what was already stored, that means the App has an update.
    - This means that comparing versions between sources would be an issue since version strings from each source may not be the same (Mullvad VPN is an example - on F-Droid it's just `2022.2`). 
    - If version strings between sources are different, Obtainium would think there was an update when there was none.
    - Even if the version strings followed the same format, there would be a problem if one source was updated slightly earlier than the other. If GitHub shows the latest version is `2022.2` but F-Droid still has `2022.1`, how do you know which is newer? You can't just do a numerical comparison since these are not real versions, and may not just contain numbers (as with Mullvad or even CloudStream for a worse example).
    -  Not sure how this could be resolved unless sources start providing real package versions (the version that shows up on an App's settings page - this is currently only available after downloading the APK, so not usable for update checking).
- "Additional options", like the pre-release toggle or release filtering, are also different between sources and would be complicated or impossible to resolve reliably.

I think users should be responsible for deciding what Apps to track from what sources. A developer's decision to stop releasing on a given source is not something Obtainium needs to fix.

**Comment by S7venLights** [comment]
Okay makes sense, oh well maybe just a warning/disclaimer for people to check F-droid from time to time since there's no other way people will be notified if they stop getting updates from Git sources.
