### ISSUE TITLE
Failed Background Update Checks Keep Retrying Indefinitely

### ISSUE THREAD

**Issue by Couchy** [ImranR98/Obtainium#838]
I noticed a strange behavior with Obtanium recently - often times there's a flickering notification badge on the app icon, but no actual notification. Then I opened the app and manually checked for updates and got this error. It seems like Obtanium was making a ton of requests in the background, maybe causing that notification badge to appear on and off repeatedly.
![1693442521535](https://github.com/ImranR98/Obtainium/assets/597166/b7150905-26f9-4084-b934-2389ecabe6f7)

**Comment by ImranR98** [comment]
> often times there's a flickering notification badge on the app icon, but no actual notification.

Android wouldn't show a badge if there was no notification. The notification is silent, meaning it doesn't show an icon or make any sound, but you should still see it if you pull down the notification bar.

Obtainium shows a separate notification for each app it checks, which is what causes the flickering. I'm thinking of getting rid of this since it doesn't really offer much, mostly just annoying.

> Then I opened the app and manually checked for updates and got this error.

This error shows up when you're making too many requests to GitHub (which is common when you don't have an API key). What's strange to me is that you only have 6 apps, and GitHub's rate limit for unauthenticated requests is much higher (30 requests per 30 minutes or something like that). Were you manually checking for updates or doing a lot of other request-heavy things (like adding apps) before this? Might be good to attach the app logs (which you can find at the bottom of the settings page) so I can check if anything looks wrong.

**Comment by Couchy** [comment]
I saw it happening again and caught the notification this time. It said "Checking for updates". I clicked "share" on the log, not sure if it did anything. Seems to be looping here with "Could not find a suitable release":
![Screenshot_2023-08-30-21-47-42-908_dev imranr obtainium](https://github.com/ImranR98/Obtainium/assets/597166/dcef30e1-8335-4797-b7ba-7b9e34c69fb9)

**Comment by ImranR98** [comment]
Clicking share should open the Android share menu. From there you can click 'copy' and paste it into a comment here.

The looping makes sense - whenever an update check fails, it is retried 4 times. The first attempt is after 1 second, second attempt after 4 seconds, then 9, and 16. The fact that your screenshot shows a 2 second wait twice, combined with the fact that you ran out of the rate limit, makes me think it isn't stopping after 4 attempts like it should. Full log would be helpful.

**Comment by Couchy** [comment]
Unfortunately, the share button does nothing for me. Could be due to my flavor of Android (using MIUI 14 on Poco F3). I can try to get a logcat next time it happens. You might be able to repro yourself by unchecking "Include prereleases" for Obtanium.

**Comment by ImranR98** [comment]
> MIUI 14

Yep, that's probably it. Some people can't install apps at all through Obtainium on some versions of MIUI.

> You might be able to repro yourself by unchecking "Include prereleases" for Obtanium.

Yep, trying that now.

**Comment by ImranR98** [comment]
Confirmed - the count does not increment.

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.6-beta
