### ISSUE TITLE
Obtanium Should Update Last

### ISSUE THREAD

**Issue by S7venLights** [ImranR98/Obtainium#84]
When updating a number of Apps including Obtainium, the APKs are downloaded but if Obtainium is installed before the other apps,android shuts down the obtanium during install and then on re-opening obtanium, the other apps that didn't install are marked as being on the latest version. 

Obtanium should maybe list itself as the last app to install somehow or could it be updated independantly of the other apps in another menu?

After this happened to me, I share copied the URls of the apps that didn't update, deleted them from Obtanium and re-imported them. 
But one of them https://github.com/ElishaAz/Vosk-Voice-IME (Sayboard)
Is now not installing updates, it keeps marking itself as on the latest version when I istall but it is not.
I remove sayboard, restart Obtanium,  add sayboard and install,  but it just flashes and marks istelf as on 2.01

**Comment by S7venLights** [comment]
PS I like the %progress toast notifications

**Comment by ImranR98** [comment]
This should have already been fixed in an earlier update, but I guess not. Will look into it.
Also when installing just updates the version number and doesn't show an install prompt, it means that version was already installed. You can confirm this in the Sayboard settings.

**Comment by S7venLights** [comment]
The version 2.0.1 wasn't installed, I confirmed in App manager and the new features aren't present. 
The other apps did update only Sayboard is stuck

**Comment by ImranR98** [comment]
I just downloaded and installed the latest Sayboard APK manually, and it still shows version 2.0.0. Looks like the devs used the v2.0.1 tag but accidentally uploaded an old APK. Either that, or the APK is new but they did not increment the version number and build number (probably this, since the App does have some theme support which was supposedly just added). Either way, that's why Obtainium thinks it's the same version (as far as the OS is concerned, it is). Something they will have to fix.

**Comment by ImranR98** [comment]
As for the other Apps, still need to look into it as Obtainium should be the last to update.

**Comment by ImranR98** [comment]
Wait a minute. Obtainium moves to the end of the list, which means it is the last install prompt that pops up. The install prompts usually stack on top of each other so the last one to pop up is actually the first one the user clicks (since the others are underneath). Dumb mistake on my part. Will fix in a bit.

**Comment by ImranR98** [comment]
Should now be fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.6.4-beta

Thanks for finding this. Just realized it probably affects anyone who upgrades to v0.6+ from previous versions and would affect all Apps 😰

**Comment by S7venLights** [comment]
😎 glad to help
