### ISSUE TITLE
Cannot update an app (conflict: <package_name>)

### ISSUE THREAD

**Issue by fellinir** [ImranR98/Obtainium#841]
Wanted to update [Otraku](https://github.com/lotusgate/otraku) to the latest version
![App](https://i.imgur.com/koPH4WI.png)

but some new error appeares when trying to actually update the app, after fetching the apk (not seen before whatsoever)
![Error](https://i.imgur.com/ZNfTHPq.png)

They confirmed me the package name has not changed.

OS: A13 LOS
Obtainuim: 0.14.4
Phone: OnePlus 5T

**Comment by fellinir** [comment]
@JohnBetaro hey thank you so much to check on your side. Yep, the dev confirmed he touched the key.

**Comment by Pinaz993** [comment]
After switching to this from F-Droid's official client, I had several apps I could not update. There was a toast (or some other ephemeral UX element) that simply said `conflict`. Thanks to this issue and Side Of Burritos' complaints about how F-Droid signs apps, I was able to figure out that I simply needed to uninstall the apps and install them from Obtanium to allow it to update them from now on.

Perhaps, since this might be a somewhat common problem, when a signature conflict happens, you can check and see if F-Droid is the one who signed the app, and if so, explain the situation to the user. I don't know if that is feasible or not. (correlating sources with F-Droid projects seems non-trivial)  However, a small toast that pops up at the bottom of the screen, tells you next to nothing, and then disappears without a trace does not seem to live up to your own excellent standards of user communication, @ImranR98.
