### ISSUE TITLE
Relative intemediate links in HTML Source do not work correctly

### ISSUE THREAD

**Issue by rusty-snake** [ImranR98/Obtainium#848]
**Describe the bug**

The new intermediateLinkRegex of the HTML Source does not work correctly with relative links.

**To Reproduce**
1. Add `https://dist.torproject.org/torbrowser/`
2. intermediateLinkRegex `12\.5\.3/$` (hardcoded version for testing)
3. Try to add app and get "not found".
4. Try again with a `http://` and PCAPDroid, see that `dist.torproject.org/12.5.3/` is requested. Correct would be `dist.torproject.org/torbrowser/12.5.3/`.

**Screenshots and Logs**
If applicable, add screenshots, logs, and any other artifacts (like some/all files under `/Android/data/dev.imranr.obtainium/`) that you think may help troubleshoot the issue.

**Please complete the following information:**
 - Device: Pixel 6
 - OS: GrapheneOS
 - Obtainium Version 0.14.7

**Additional context**

What do you think about adding a torbrowser source that uses `dist.torproject.org` in the background if `https://www.torproject.org/download/` is requested?

**Comment by ImranR98** [comment]
Bug fixed: https://github.com/ImranR98/Obtainium/releases/tag/v0.14.8-beta

In general, App-specific Sources should be kept to a minimum (only added if there's no way to do it with the HTML Source). Note, you can already add `https://www.torproject.org/download/` under the HTML Source and it will work since APKs are hosted there too.
