### ISSUE TITLE
Add new version detection using REGEX for HTML sources

### ISSUE THREAD

**Issue by taki-eddine-47** [ImranR98/Obtainium#861]
**Prerequisites**

- [x] Please ensure your request is not part of an existing issue.

**Describe the feature**
I have a nginx server contains some APKs.
By using the HTML, I want to add a regex to detect the version,
and an option to override the author name (currently Obtainium uses the domain name).

**For example:**
retroarch-1.15.0-arm64-v8a.apk

- Author: `RetroArch`
- Version Detection: `Regex`
- Regex: `-([^-]+)-arm64-v8a.apk`
- **Note:** The first group `$1` is the version number.

**Additional context**
<img src="https://github.com/ImranR98/Obtainium/assets/25118467/3e801fba-0cd8-45a8-a537-8dfb192b920b" alt="Obtainium" width="300" />
<img src="https://github.com/ImranR98/Obtainium/assets/25118467/d7336e71-209f-454d-897c-8374ab2500ac" alt="System" width="300" />

**Comment by ImranR98** [comment]
Interesting, idea. Could probably use the whole link instead of the filename to account for cases like `example.com/v1.2.3/app.apk`.

Could also have a "trim characters" option. For example:
- URL is `example.com/api/2.3.1/app/3.4.5/app.apk`
- You can't just use `([0-9]+\.)*[0-9]+` since that would match both the API version `2.3.1` and App version `1.2.3`
- You could use `app/([0-9]+\.)*[0-9]+`
- You could then specify that the first 4 characters of the match be trimmed off
- Both positive and negative numbers could be used for trimming from the front/back
- Not sure how to present this in the UI in a way that makes sense

**Comment by taki-eddine-47** [comment]
Thank you.
About your example, we can avoid using other parameters to trim (prefix or suffix) by always looking for the first group `$1` of the regex by wrapping the version expression in `()`:

URL: example.com/api/2.3.1/app/3.4.5/app.apk
Regex: `app/(([0-9]+\.)*[0-9]+)`

![image](https://github.com/ImranR98/Obtainium/assets/25118467/7c52cf9f-e7a6-4432-b073-ac9db46424b9)
![image](https://github.com/ImranR98/Obtainium/assets/25118467/d872f834-b97a-4f23-833c-5b9d90f5e785)
![image](https://github.com/ImranR98/Obtainium/assets/25118467/021ed42f-31b1-4e52-b065-fd9685be7a36)

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.11-beta

**Comment by taki-eddine-47** [comment]
Thank you for taking the time to implement this feature.
I tested it, and it works wonderfully.

<img src="https://github.com/ImranR98/Obtainium/assets/25118467/ee8b054f-14ba-4232-b47f-ba722744a6af" width=400 />

**Comment by darrenhaken** [comment]
Can someone explain what’s the best way to use Obtainium with Retroarch? I followed a guide on Retro Game Corps but it didn’t work. I assume this feature helps
