### ISSUE TITLE
Change app data location

### ISSUE THREAD

**Issue by JohnBetaro** [ImranR98/Obtainium#872]
Hi, instead of automatic backup that will require extra coding and testing, why don't we just move the app's data from `Android/data` to `Android/media`, this way it will be accessible for other apps to sync it and upload it to the cloud using tools like Rclone, I hope you'll consider adding it in the near future because it is a pain to do it manually every time we change anything.

**Comment by ImranR98** [comment]
I tried this but it looks like you need extra permissions to access your own folder in `/Android/media`. I tried doing more research but haven't figured out what's needed yet (the current Flutter plugin we use to get the storage directory doesn't have support for it).

I think instead of focusing on `/media` specifically, it makes more sense to stick to issue #600 which lets the user pick their own directory for the same purpose. I'm looking into this, probably this plugin could be used: https://pub.dev/packages/shared_storage
