### ISSUE TITLE
It keeps displaying the update symbol, but not actually updating.

### ISSUE THREAD

**Issue by OkeyF** [ImranR98/Obtainium#899]
specifically https://github.com/KhoalaS/Infinity-For-Reddit/releases/tag/v5.10.0

No idea what it is, but only certain applications do it.

**Comment by OkeyF** [comment]
like, when I click update it "installs" then comes back.

**Comment by ImranR98** [comment]
This is happening because the version tag on GitHub is `v5.10.0` but the actual version of the APK is `2023.31.0`. These both look like the same "standard" version format, so Obtainium detects the app's real version, compares it to the number from GitHub, and thinks there's a new update (from `2023.31.0` which is installed to `5.10.0` which GitHub says it has).

To work around this, you can disable version detection in the settings for this app. Then it won't try to compare the OS-reported version with the GitHub-reported one. The downside is that if you update this app externally, the change will not be noticed by Obtainium.
