### ISSUE TITLE
Obtainium displaying an update when i am already using latest version

### ISSUE THREAD

**Issue by xd003** [ImranR98/Obtainium#923]
I already have the latest version of a app. I just happen to download and install it from github moments ago before adding it to Obtainium. Now obtainium is indicating that an update is available for this app but i am already using the latest version.

![Screenshot_20230922_082924](https://github.com/ImranR98/Obtainium/assets/26503185/9530ed2b-79fd-401f-932b-da91df446c73)

 - Device: Iqoo Neo 7
 - OS: Funtouch OS
 - Obtainium Version: 0.14.17

**Comment by ImranR98** [comment]
This isn't a bug, it's due to the app having a weird versioning scheme (`...GMS.233515`). Since the app was already installed, the installed version was auto-detected. It differs from the version reported by GitHub, hence the update notification.

Just mark the app as updated (checkmark button on the bottom left) and it shouldn't happen again (unless you update the app externally, which is not supported for apps with version detection disabled).
