### ISSUE TITLE
Notification spam

### ISSUE THREAD

**Issue by MatsG23** [ImranR98/Obtainium#974]
**Describe the bug**
Obtainium sent me an notification with an connection error for each app I have stored. That makes a lot of notifications.

**To Reproduce**
I am a unsure how to reproduce this. I have seen that bug for the first time ever and it has occurred while the app was closed.

**Screenshots and Logs**
![Screenshot_20231008-130500](https://github.com/ImranR98/Obtainium/assets/60609373/f526953f-6d1f-4d58-93be-f629d0d2e4bc)

**Please complete the following information:**
 - Device: Pixel 6a
 - OS: GrapheneOS TQ3A.230901.001.2023100300 (based on A13)
 - Obtainium Version: 0.14.24-beta

**Additional context**
I was offline. It could be that I went offline while Obtainium was searching for app updates in the background.

**Comment by ImranR98** [comment]
Will be fixed in the next release by:
- grouping errors of the same type
- Not attempting updates if neither wifi nor mobile data is enabled

**Comment by ImranR98** [comment]
https://github.com/ImranR98/Obtainium/releases/tag/v0.14.25-beta

If you're not connected to any networks, Obtainium will now skip update checking (and retry in 15 minutes or the next update interval, whichever is earlier). Note that if you are connected to some network but without internet access, you'll still get error notifications (one per hostname now instead of per app). That's a limitation of the Flutter plugin we use (for an actual internet check we'd have to pick some server to try connecting to).
